### ISSUE TITLE
Generic regex rules

### ISSUE THREAD

**Issue by keith** [realm/SwiftLint#123]
As we've been expanding our usage of SwiftLint we've added a lot of simple regex rules to conform to our style guide. I'm not sure what the long term plans are to handle custom rules but it might be nice to provide a way for users to add regex rules in their `.swiftlint.yml`. For example:

```yml
regex:
  - (^[^\\s]+\\s+@objc|@objc[^\\n_])
```

This would create multiple rules (once https://github.com/realm/SwiftLint/pull/106 is merged) at runtime.

There are a few issues I can see with this, specifically around them not being customizable. I'm not sure how the warning/error message would be generated and things like `NSRegularExpression` options wouldn't be unusable.

I just wanted to get some feedback on this idea before putting time into it. Let me know your thoughts!

**Comment by jpsim** [comment]
SwiftLint's strength IMO comes from its contextual knowledge of the AST, which is why regex-based rules also typically check the syntax type of its matched tokens. So ideally, the ability to define custom rules in the configuration file should also expose that.

How about providing more information for new rules?

```yaml
custom_rules:
  ObjCRule:
    message: @objc should be avoided
    regex: (^[^\\s]+\\s+@objc|@objc[^\\n_])
    match_tokens: identifier
    severity: warning
```
