### ISSUE TITLE
Rule to forbid(or warn about) disabling specific rules

### ISSUE THREAD

**Issue by toshi0383** [realm/SwiftLint#1308]
Sometimes people disable any rules because they just don't know how to fix it.

e.g.
```
// ("_" is a white space)
// swiftlint:disable trailing_whitespace
____
____// code_
____
```

I thought it would be useful if SwiftLint can detect when an "important rule" is disabled.

Basic idea is like this.

1. Detect disabled important rules in .swiftlint.yml

```.swiftlint.yml
important_rules:
  - trailing_whitespace
  - nested
disabled_rules:
  - trailing_whitespace
  - nested
```

Error Message:
```
'disabled_rules' cannot contain [trailing_whitespace, nested] since it's listed in 'important_rules'
```

2. Detect disabled important rules in each files

```.swiftlint.yml
important_rules:
  - trailing_whitespace
```

```a.swift
// swiftlint:disable:next trailing_whitespace
```

Error Message:
```
'trailing_whitespace' should not be disabled. (important_rules)
```

3. Ignore disable important_rules command
```swift
// swiftlint:disable important_rules <= ignored
```

If you guys feel happy with this idea, maybe I can work on a PullRequest.

**Comment by jpsim** [comment]
I'm not sure how I feel about this. I have a hard time thinking of _any_ rule in SwiftLint that should never be disabled...

**Comment by norio-nomura** [comment]
IMO, I feel it is too complicated. Can not meet your requirements with custom rules?
```yaml
custom_rules:
  force_unwrapping_is_important:
    name: "`force_unwrapping` should not be disabled."
    regex: "swiftlint:disable[^\n]+force_unwrapping"
    serverity: error
    match_kinds:
      - comment
```
