### ISSUE TITLE
"included" is ignored in custom rule

### ISSUE THREAD

**Issue by nigelflack** [realm/SwiftLint#1349]
I'm experimenting with using SwiftLint to implement custom rules to pick up poor programming from 3rd-parties. The "included" parameter seems to be being ignored.

Here is my original .swiftlint.yml:

```
disabled_rules:
  - trailing_whitespace
  - trailing_newline

line_length: 200

custom_rules:
  no_network_in_vc:
    included: ".*ViewController.swift"
    name: "No Network in VC"
    regex: "(URL)"
    message: "Network code is not allowed in view controllers."
    severity: error
```

(there is a "let url = URL(..." line in the ViewController)

This worked as expected, so then I tested to ensure the rule was only applied to view controllers. I created a file "SomeClass.swift" with a similar "let url..." statement and ran swiftlint - it was applied to that class as well. The .swiftlint.yml file is in the same folder as the .xcworkspace. I get the same result whether I run on the command line or in Xcode.

As a further test, when I change the included line to:

```
    included: "index.html"
```

this still matches in both files (there is no index.html file in this project).

This seems broken?
