### ISSUE TITLE
Enhancement: Better differentiate uses of "included" and "excluded"

### ISSUE THREAD

**Issue by nigelflack** [realm/SwiftLint#1353]
I'd like to propose an enhancement relating to the "included" and "excluded" configuration keywords.

In the global configuration (i.e. not per-rule configuration) "included" and "excluded" refer to file paths:

```
included: # paths to include during linting. `--path` is ignored if present.
  - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
```

In per-rule configuration, "excluded" refers to tokens (I'm not sure if included is supported here):

```
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
```

In custom rules, "included" refers to file paths again, and "excluded" does not appear to be supported. "match_kinds" is used for tokens:

```
custom_rules:
  pirates_beat_ninjas: # rule identifier
    included: ".*.swift" # regex that defines paths to include during linting. optional.
    name: "Pirates Beat Ninjas" # rule name. optional.
    regex: "([n,N]inja)" # matching pattern
    match_kinds: # SyntaxKinds to match. optional.
      - comment
      - identifier
```

I'd propose making these more consistent through updating the names to something like:

include_paths
exclude_paths
include_tokens
exclude_tokens

Any thoughts?
