### ISSUE TITLE
Rule for enforcing no hardcoded string for identifiers.

### ISSUE THREAD

**Issue by RishabhTayal** [realm/SwiftLint#1377]
I am using R.swift in my project which gives strong type for resources such as image names, segue identifiers, nib names, storyboard names. Is there a way to enforce that there is no hard coded string used in these cases in the code? 

For e.g. I don't want people to use something like this: `UIImage(named: "some-image")`.

**Comment by RishabhTayal** [comment]
If someone can help me write the regex, I can create a PR for this feature.

**Comment by RishabhTayal** [comment]
I am creating a pull request https://github.com/realm/SwiftLint/pull/1777 for this. It's a WIP.

**Comment by PlagsiOS** [comment]
Hello, did you find such a rule? I need a similar rule for checking hardcoded strings in buttons, labels, textfield and textviews.  I can't find anything

**Comment by mildm8nnered** [comment]
> Hello, did you find such a rule? I need a similar rule for checking hardcoded strings in buttons, labels, textfield and textviews. I can't find anything

@PlagsiOS - you can probably write this yourself using custom rules (see the README). For example, `UIImage(named: "` should be easy to write a regex for, and similarly for the other cases.

```
custom_rules:
  use_identifiers_for_uiimage_names:
    included: ".*.swift"
    name: "Use Identifiers for UIImage Names"
    message: "Use identifiers instead of strings for UIImage names"
    regex: UIImage\(named\:\s*\"
    severity: warning
```
