### ISSUE TITLE
Allow individual rules to exclude certain paths

### ISSUE THREAD

**Issue by ileitch** [realm/SwiftLint#1385]
I'd like to use the new `implicitly_unwrapped_optional` rule, however our tests contain many valid uses of implicitly unwrapped optionals (mostly because XCTest requires you to populate vars in `setUp` as the constructor cannot be overriden).

I'd only like this rule to be performed on our application code. I've tried the following however it has no affect:

```
implicitly_unwrapped_optional:
  included:
    - Foo
  excluded:
    - Foo/Tests
```
