### ISSUE TITLE
Adding custom rule with an exception

### ISSUE THREAD

**Issue by jayesh15111988** [realm/SwiftLint#1408]
I am trying to add a custom rule to enforce no space after opening parentheses. Custom rule is defined as follows
```
no_space_after_opening_parentheses:
        name: "No space after opening parentheses"
        message: "Please avoid using space after opening parantheses"
        regex: "(\(\s+)"        
```

However, I want to avoid Swiftlint from warning me when opening brace is followed by newline. Is there any way to avoid warning by doing something like this?

`excludingPattern: "(\(\n)"`
