### ISSUE TITLE
custom rules stops working in 0.18.1

### ISSUE THREAD

**Issue by Sega-Zero** [realm/SwiftLint#1449]
Before update to 0.18.1, this was working fine:
```yaml
  use_uiimage_enums:
    name: "Use UIImage enums!"
    regex: "UIImage\(named\:"
    severity: error
    match_kinds:
    - identifier

  skip_uiimage_init:
    name: "Remove .init!"
    regex: "UIImage\.init\("
    severity: error
    match_kinds:
    - identifier
```

After upgrade it is not working anymore. Changed to this:
```yaml
  use_uiimage_enums:
    name: "Use UIImage enums!"
    regex: '\QUIImage(named:\E'
    severity: error
    match_kinds:
    - identifier

  skip_uiimage_init:
    name: "Remove .init!"
    regex: '\QUIImage.init(\E'
    severity: error
    match_kinds:
    - identifier
```

first rule works. second rule doesn't!

Plus, it looks like swiftlint totally ignores `"` character in any form.
these rules doesn't work:
```yaml
  use_typed_segues:
    name: "Use Segues.swift enums!"
    regex: '\Q.performSegue(withIdentifier:\E\s?\"'
    severity: error
    match_kinds:
    - identifier
```
```yaml
  use_typed_segues:
    name: "Use Segues.swift enums!"
    regex: '\Q.performSegue(withIdentifier:\E\s?\x22'
    severity: error
    match_kinds:
    - identifier
```
```yaml
  use_typed_segues:
    name: "Use Segues.swift enums!"
    regex: '\Q.performSegue(withIdentifier: \E[^\.\S]'
    severity: error
    match_kinds:
    - identifier
```

None of it catches the string:
```swift
self.performSegue(withIdentifier: "", sender: nil)
```
But all of them should.

**Comment by norio-nomura** [comment]
`regex` does not require that the string contains double quotes.
try following:
```yaml
  use_uiimage_enums:
    name: "Use UIImage enums!"
    regex: 'UIImage\(named\:'
    severity: error
    match_kinds:
      - identifier
  skip_uiimage_init:
    name: "Remove .init!"
    regex: 'UIImage\.init\('
    severity: error
    match_kinds:
      - identifier
      - keyword
```

**Comment by norio-nomura** [comment]
You can check what `match_kinds` are needed for your custom rule by using `sourcekitten`:
```terminal.sh-session
$ brew install sourcekitten
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 044bd974e4 to 5c82e0d552.
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Downloading https://homebrew.bintray.com/bottles/sourcekitten-0.17.2.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring sourcekitten-0.17.2.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/sourcekitten/0.17.2: 28 files, 10.7MB
$ sourcekitten syntax --text "UIImage.init()"
[
  {
    "type" : "source.lang.swift.syntaxtype.identifier",
    "offset" : 0,
    "length" : 7
  },
  {
    "type" : "source.lang.swift.syntaxtype.keyword",
    "offset" : 8,
    "length" : 4
  }
]
```

**Comment by Sega-Zero** [comment]
Adding `keyword` did the trick for `UIImage.init` rule, but then why did that rule was working on previous versions with just a `identifier`?

Also, couldn't get `use_typed_segues` rule working even with `- keyword`.

**Comment by norio-nomura** [comment]
You specified `"` at tail of `regex`.
`"` is recognized as string by SourceKit.
```terminal.sh-session
$ sourcekitten syntax --text '.performSegue(withIdentifier: ""'
[
  {
    "type" : "source.lang.swift.syntaxtype.identifier",
    "offset" : 1,
    "length" : 12
  },
  {
    "type" : "source.lang.swift.syntaxtype.identifier",
    "offset" : 14,
    "length" : 14
  },
  {
    "type" : "source.lang.swift.syntaxtype.string",
    "offset" : 30,
    "length" : 2
  }
]
```
config is:
```yaml
  use_typed_segues:
    name: "Use Segues.swift enums!"
    regex: '\.performSegue\(withIdentifier\:\s*"'
    severity: error
    match_kinds:
      - identifier
      - identifier
      - string
```
