### ISSUE TITLE
Specify line to highlight in Custom Rules

### ISSUE THREAD

**Issue by Jeehut** [realm/SwiftLint#1459]
Is there a way to **specify the line that should be highlighted** when defining custom rules? It seems like it's always simply highlighting the line where the regex match begins, but that's sometimes very confusing. Here's an **example use case**:

I have this **custom rule**:
```yaml
custom_rules:
  vertical_whitespace_closing_braces:
    included: ".*.swift"
    regex: '\n[ \t]*\n[ \t]*[)}\]]'
    name: "Vertical Whitespace before Closing Braces"
    message: "Don't include vertical whitespace (empty line) before closing braces."
    severity: warning
```

And this **code**:
```swift
class MyClass {
    func someMethod() {
        // some code
    }

}

```

**Currently** the warning shows off in here:

```swift
class MyClass {
    func someMethod() {
        // some code
    } // <-- WARNING: Vertical Whitespace before Closing Brace Violation: Don't include vertical whitespace (empty line) before closing braces.

}

```

This is **very confusing** though as the rule actually refers to the second closing brace. Thus, the following would be **better**:

```swift
class MyClass {
    func someMethod() {
        // some code
    }

} // <-- WARNING: Vertical Whitespace before Closing Brace Violation: Don't include vertical whitespace (empty line) before closing braces.

```

I imagine that one could **use a capture within the regex** to give SwiftLint instructions which part of the match should be highlighted, for example my regex from above could then be:

```yaml
    regex: '\n[ \t]*\n[ \t]*([)}\]])'
```

But I'm also open to **other solutions**. For example one could also say that everything enclosed in `(?:regex)` could be ignored when it comes to highlighting. This way the regex would look like this:

```yaml
    regex: '(?:\n[ \t]*\n)[ \t]*([)}\]])'
```
