### ISSUE TITLE
Rule Request: Vertical Whitespace between Cases

### ISSUE THREAD

**Issue by Dschee** [realm/SwiftLint#1517]
This is a rule request. I'm willing to implement this myself and send a PR, but before doing that I'd like to know if the rule is wanted or not. To explain the desired rule, I'd like to first post the **custom rule** we are already using in our projects:

```yaml
  vertical_whitespace_between_cases:
    included: ".*.swift"
    regex: '[^\n){][ \t]*\n[ \t]*(?:case[^:(\n]+|default):(?:\\s*\/(\/\*).*)?'
    name: "Vertical Whitespace Between Cases"
    message: "Include a vertical whitespace (empty line) between cases in switch statements."
    severity: warning
```

I felt like this rule might be useful for other projects as well, which is why I'm posting it. What do you think about it? For us it helps a lot to prevent common issues and enforce a shared style.

**Rationale**

We had this discussion a few times, the common ground we were all happy with is this: When using switch-case there should be a newline before a new case begins except for the last case, because there's already a closing parentheses and indentation there as visual clues.

A few examples:

```swift
let x = 5

// ❌ not acceptable
switch x {
case 0..<5:
    // some code
case 5..<10:
    // some code
default:
    // some code
}

// ❌not acceptable
switch x {
case 0..<5:
    // some code

case 5..<10:
    // some code

default:
    // some code

}

// ✅ acceptable
switch x {
case 0..<5:
    // some code

case 5..<10:
    // some code

default:
    // some code
}
```
