### ISSUE TITLE
Rule Request: Vertical Whitespace Opening/Closing Braces

### ISSUE THREAD

**Issue by Dschee** [realm/SwiftLint#1518]
This is a rule request. I'm willing to implement this myself and send a PR, but before doing that I'd like to know if the rule is wanted or not. To explain the desired rule, I'd like to first post the **custom rule** we are already using in our projects:

```yaml
  vertical_whitespace_opening_braces:
    included: ".*.swift"
    regex: '[{(\[][ \t]*\n[ \t]*\n'
    name: "Vertical Whitespace after Opening Braces"
    message: "Don't include vertical whitespace (empty line) after opening braces."
    severity: warning
  vertical_whitespace_closing_braces:
    included: ".*.swift"
    regex: '\n[ \t]*\n[ \t]*[)}\]]'
    name: "Vertical Whitespace before Closing Braces"
    message: "Don't include vertical whitespace (empty line) before closing braces."
    severity: warning
```

I felt like these rules might be useful for other projects as well, which is why I'm posting it. What do you think about it? For us it helps a lot to prevent common issues and enforce a shared style.

**Rationale**

We had this discussion a few times, the common ground we were all happy with is this: The main reason to use newlines is to have a visual clue about which parts of the code belong together. These rules together ensure you never have a newline where you should already use an indentation which is a good visual clue already, in this case due to an opening parentheses at the end of a line and a closing at the beginning.

A few examples:

```swift
let x = 5

// ❌ not acceptable
if x == 5 {

    print("x is 5")

}

// ❌not acceptable
if x == 5 {

    print("x is 5")
}

// ❌not acceptable
if x == 5 {
    print("x is 5")

}

// ✅ acceptable
if x == 5 {
    print("x is 5")
}
```
