### ISSUE TITLE
New Rule: Optional Property Write

### ISSUE THREAD

**Issue by Dschee** [realm/SwiftLint#1519]
This is a rule request. I'm willing to implement this myself and send a PR, but before doing that I'd like to know if the rule is wanted or not. To explain the desired rule, I'd like to first post the **custom rule** we are already using in our projects:

```yaml
optional_property_write:
    included: ".*.swift"
    regex: '\S+!\.\S+\s*=[^=]\s*'
    name: "Writing Properties on Optionals"
    message: "Don't use ! to write into properties on optionals – use ? instead."
    severity: warning
```

I felt like this rule might be useful for other projects as well, which is why I'm posting it. What do you think about it? For us it helps a lot to prevent common issues and enforce a shared style.

**Rationale**

When assigning a value to a property of a type, some people used the `!` syntax which will lead to a crash. In nearly all cases it is better to use `?` instead to ensure the app doesn't crash due to this single property assignment. In cases where the existence of the variable is required, the `if let` or `guard let` syntax should be used anyways.

A few examples:

```swift
let label: UILabel?

// ❌ not acceptable
label!.text = "someString"

// ✅ acceptable
label?.text = "someString"
```
