### ISSUE TITLE
Support tabs in vertical parameter alignment rule

### ISSUE THREAD

**Issue by DevAndArtist** [realm/SwiftLint#1573]
My swift files are formatted using AppCode and tabs. Therefore only a few spaces are added automatically when necessary:

```swift
private func snap(label: UILabel,
				  below otherView: UIView,
				  offsetBy value: CGFloat) -> [NSLayoutConstraintInterface] {
```

In Xcode, AppCode and SublimeText these labels are aligned. Tab and ident width is 4.

SwiftLint version: 0.18.1
If I'm not mistaken, GitHub uses a tab width of 8.

**Comment by DevAndArtist** [comment]
Well I managed to solve the problem using `smart tabs` in AppCode which matches the behavior of Xcode as well. You can consider this issue as resolved. 🙈

**Comment by marcelofabri** [comment]
I'm glad that you figured this out, but anyway we probably should support tabs as well

**Comment by DevAndArtist** [comment]
@marcelofabri I'm confused, some tabs works other don't. Now I bumped into that issue in Xcode as well.

### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report

* SwiftLint version: 0.24.0
* Installation method used: CocoaPods
* Configuration file:

```yml
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - fatal_error_message
  - force_unwrapping
  - sorted_imports
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - switch_case_on_newline
  - attributes
  - no_extension_access_modifier
  - implicit_return

# rule identifiers to exclude from running
disabled_rules: 
  - colon
  - closure_parameter_position
  - opening_brace
  - file_length
  - implicit_return
  - private_over_fileprivate

# paths to ignore during linting
excluded: 
  - Pods

identifier_name:
  # excluded via string array
  excluded: 
    - px
    - s
    - f
    - ec
    - wb
    - tv
    - av
    - fn

large_tuple: 4

cyclomatic_complexity: 20

nesting:
  type_level: 2

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

attributes:
  always_on_same_line: ["@IBAction", "@IBOutlet", "@IBInspectable"]
  always_on_line_above: ["@IBDesignable", "@UIApplicationMain", "@discardableResult", "@objc"]
```

* Xcode version: Version 9.1 (9B55)
* Code that reproduces the issue:
```swift
struct Test {
	init(x _: Int,
		 y _: Int,
		 z _: Int) {
		print("""
		y and z lines are indeded by Xcode via `control + i`
		Vertical Parameter Alignment Violation: Function parameters should be aligned \
		vertically if they're in multiple lines in a declaration. (vertical_parameter_alignment)
		""")
	}
}
```
