### ISSUE TITLE
custom_rules regex not picking up newline correctly

### ISSUE THREAD

**Issue by omerfarukyilmaz** [realm/SwiftLint#1743]
I could not get this custom rule working. Either I am doing the regex wrong, or swiftlint does regex differently. My regex works [here](https://regex101.com/r/1zjHO6/4/)

I want to force a newline after an extension declaration.

Valid:
extension A {

  func temp() {
  }

}

Invalid:

extension B {
  func temp() {
  }

}

custom_rules:
extension_declaration_missing_newline:
regex: 'extension .+\n.'
name: "Extension Declaration Missing Newline"
message: "Enter a newline after opening brackets {"
severity: error''

> swxftlint version
`0.21.0`

PS. Love SwiftLint :) I would have gone insane with inconsistent code if it weren't for SwiftLint. So many thanks and props to you all!

**Comment by marcelofabri** [comment]
@omerfarukyilmaz There's some quotes in invalid places (after `extension_declaration_missing_newline` and `error`.

I was able to get a violation with this configuration:

```yml
custom_rules:
    extension_declaration_missing_newline:
    regex: 'extension .+\n.'
    name: "Extension Declaration Missing Newline"
    message: "Enter a newline after opening brackets {"
    severity: error
```

**Comment by omerfarukyilmaz** [comment]
Yeah sorry those misplaced quotes are proof of my poor attempt to format correctly in markdown.

Yes, I was able to get a a violation as well but correcting the swift file, as in adding a second newline which should make it valid and_not_ cause a violation *still* causes a violation.

What I mean is, when I made the rule with multiple \n's (\n\n\n), the violation is still triggered.

I hope I was clear  enough.

**Comment by marcelofabri** [comment]
I've change it to:

```yml
custom_rules:
    extension_declaration_missing_newline:
    regex: 'extension .+\n\n'
    name: "Extension Declaration Missing Newline"
    message: "Enter a newline after opening brackets {"
    severity: error
```

And it didn't trigger 🤔 

This is the file:

```swift
extension B {
    func temp() {
    }
}
```
