### ISSUE TITLE
Custom Rules in nested configuration

### ISSUE THREAD

**Issue by ornithocoder** [realm/SwiftLint#1815]
### New Issue Checklist

- [x] I updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report

I'm using a custom rule to validate the name of my Quick Specs (I want them to end with `Tests`, e.g. `AppCordinatorTests`). For that, I implemented a simple custom rule and placed it in the `.swiftlint.yml` that I have inside the Tests directory. It didn't work. So I moved the custom rule to the top level `.swiftlint.yml` and it worked.

Apparently custom rules don't work if placed in nested configurations.

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.22.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

```yml
# ...

custom_rules:
  quickspec_class_name:
    name: "Invalid Test Class Name"
    regex: "class\\s+(.*)[^Tests]:\\s+QuickSpec"
    message: "A test class name must end with 'Tests'"
    severity: error
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? Yes, I am.

* Which Xcode version are you using (check `xcode-select -p`)? Xcode 9b6 (App and Command Line)

```swift
// This triggers a violation:
class Foo: QuickSpec { }

// Doesn't trigger a violation:
class FooTests: QuickSpec { }
```
