### ISSUE TITLE
Shorthand Operator always expects += availability

### ISSUE THREAD

**Issue by jshier** [realm/SwiftLint#1828]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report

Pursuant to discussion in [1182](https://github.com/realm/SwiftLint/issues/1182#issuecomment-328199526), it appears the Shorthand Operator rule always expects the `+=` convenience operator to be available, even inside a custom definition of `+=` itself. 

##### Complete output when running SwiftLint, including the stack trace and command used
```
./Pods/SwiftLint/swiftlint --lenient
String+DetailFormatting.swift:20:9: warning: Shorthand Operator Violation: Prefer shorthand operators (+=, -=, *=, /=) over doing the operation and assigning. (shorthand_operator)
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? *0.22*
* Installation method used (Homebrew, CocoaPods, building from source, etc)? *CocoaPods*
* Paste your configuration file:

```yml
included:
  - App
  - Watch
  - Watch Extension
excluded:
  - App/Pods
disabled_rules:
  - file_length
  - function_body_length
  - function_parameter_count
  - line_length
  - nesting
  - todo
  - type_body_length
  - valid_docs
  - force_try
  - trailing_whitespace
  - force_cast
  - notification_center_detachment
  - type_name
  - identifier_name
opt_in_rules:
  - empty_count
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents. *No*
* Which Xcode version are you using (check `xcode-select -p`)? *8.3.3*
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
extension NSAttributedString {
    static func + (lhs: NSAttributedString, rhs: NSAttributedString) -> NSAttributedString {
        let result = NSMutableAttributedString()
        result.append(lhs)
        result.append(rhs)
        return result
    }

    static func += (lhs: inout NSAttributedString, rhs: NSAttributedString) {
        lhs = lhs + rhs // Shorthand Operator Violation
    }
}
```
