### ISSUE TITLE
Shebang being autocorrected with operator whitespace rule

### ISSUE THREAD

**Issue by Mazyod** [realm/SwiftLint#1894]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report

```bash
(swiftlint-autocorrect-fixes) [132] % swiftlint autocorrect --path .devtools --config ../.swiftlint.yml
Loading configuration from '../.swiftlint.yml'
Correcting Swift files at path .devtools
Correcting 'carthage-deps-check.swift' (1/2)
Correcting 'nslocalizedToLocalized.swift' (2/2)
/.../.devtools/carthage-deps-check.swift:1:7 Corrected Operator Usage Whitespace
/.../.devtools/carthage-deps-check.swift:1:11 Corrected Operator Usage Whitespace
Done correcting 2 files!
```

```diff
@@ -1,4 +1,4 @@
-#!/usr/bin/swift
+#!/usr / bin / swift
 
 import Foundation
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
* Paste your configuration file:

```yml
disabled_rules:
  - void_return # KEEP
  - unused_closure_parameter # KEEP
  - trailing_comma # KEEP
  - nesting # KEEP
  - closure_parameter_position # KEEP
  - for_where
  - force_try
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length
  - function_parameter_count
  - todo
  - trailing_whitespace
  - type_body_length
  - identifier_name

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - first_where
  - multiline_parameters
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - vertical_whitespace
  - fatal_error_message
  - implicit_return
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - custom_rules
  - line_length

reporter: "xcode"
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage

object_literal:
  color_literal: false

line_length:
  error: 250
  warning: 180
  ignores_comments: true
  ignores_function_declarations: true

overridden_super_call:
  severity: warning
  excluded: []
  included:
    - "*" # include the default methods that require calling super.
    - mapping(map:)

vertical_whitespace:
  max_empty_lines: 2

type_name:
  min_length: 3
  max_length: # warning and error
    warning: 50
    error: 60
  excluded: iPhone # excluded via string
  
custom_rules:
  localized_not_NSLocalized: # rule identifier
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    name: ".localized instead of NSLocalized" # rule name. optional.
    regex: "(NSLocalizedString)" # matching pattern
    message: "Use .localized instead of NSLocalized" # violation message. optional.
    severity: warning # violation severity. optional.
```
