### ISSUE TITLE
multiline_parameters - doesn't pick up nested function calls

### ISSUE THREAD

**Issue by allen-zeng** [realm/SwiftLint#1923]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report
When there is a nested function call to as the parameter of another function call, the `multiline_parameters` rule doesn't treat the nested call as a parameter on its own:
```swift
callingFunc1(callingFunc2(p1, p2: p2),
    p3: p3, p4: p4)
```

The expected correct structure should be either one of the following:
```swift
callingFunc1(
    callingFunc2(p1, p2: p2),
    p3: p3,
    p4: p4)

callingFunc1(callingFunc2(p1, p2: p2), p3: p3, p4: p4)
```

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ echo "callingFunc1(callingFunc2(\np1,\np2: p2),\np3: p3)" | swiftlint --use-stdin 
Done linting! Found 0 violations, 0 serious in 1 file.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? **0.23.1**
* Installation method used (Homebrew, CocoaPods, building from source, etc)? **Homebrew or CocoaPods**, happens on both
* Paste your configuration file:

```yml
disabled_rules:
  - closing_brace
  - cyclomatic_complexity
  - force_cast
  - force_try
  - identifier_name
  - line_length
  - nesting
  - notification_center_detachment
  - todo
  - trailing_comma
  - trailing_whitespace
  - type_name
  - weak_delegate
  - file_length
excluded:
  - Carthage
  - Pods
colon:
  flexible_right_spacing: true
line_length: 400
type_body_length:
  - 2048
  - 2048
function_body_length:
  - 400
  - 400
force_try:
  severity: warning
reporter: "xcode"
large_tuple:
  - 4
  - 4
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - multiline_parameters
  - overridden_super_call
  - prohibited_super_call
  - vertical_parameter_alignment_on_call
```

* Which Xcode version are you using (check `xcode-select -p`)? **9.0**
