### ISSUE TITLE
Warning for non-existent `comments_space` rule

### ISSUE THREAD

**Issue by 3ph** [realm/SwiftLint#1934]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report

Getting lots of `comments_space` warning but there no such rule `comments_space`.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint

Loading configuration from '.swiftlint.yml'
configuration error: 'comments_space' is not a valid rule identifier
Valid rule identifiers:
type_name
empty_count
....
Linting 'XXX.swift' (15/163)
/Users/XXX.swift:569:1: warning: Space After Comment Violation: There should be a space after // (comments_space)
/Users/XXX.swift:881:1: warning: Space After Comment Violation: There should be a space after // (comments_space)
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.23.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)? CocoaPods
* Paste your configuration file:

```yml
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# If you need help with rules run $ swiftlint

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - explicit_failure_calls
  - extension_access_modifier
  - fatal_error_message
  - first_where
  # - file_header
  - force_cast
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - multiline_parameters
  - multiple_empty_lines
  - nesting
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_nil_coalescing
  - sorted_imports
  - syntactic_sugar
  - vertical_parameter_alignment_on_call
  - vertical_whitespace

disabled_rules: # rule identifiers to exclude from running
  # - force_try
  # - class_delegate_protocol
  - function_parameter_count
  - type_body_length
  - comments_space
  - todo
  - cyclomatic_complexity
  # - discarded_notification_center_observer
  # - conditional_returns_on_newline

file_length:
  warning: 1500
  error: 3000

function_body_length:
  warning: 150
  error: 300

line_length:
  warning: 180
  error: 350
  ignores_comments: true
  ignores_urls: true

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

identifier_name:
  allowed_symbols: "_"
  excluded: "_"
  min_length: 1
  max_length:
    warning: 90
    error: 1000

type_name:
    min_length: 1

implicitly_unwrapped_optional:
  mode: all_except_iboutlets

large_tuple:
  warning: 4
  error: 5

type_body_length:
  warning: 1000
  error: 1000

trailing_comma:
  mandatory_comma: true

number_separator:
  minimum_length: 8

private_outlet:
  allow_private_set: true

colon:
  severity: error
comma: error
empty_count: error
legacy_constant: error
legacy_constructor: error
opening_brace: error
trailing_newline: error
trailing_semicolon: error

custom_rules:
  comments_space: # From https://github.com/brandenr/swiftlintconfig
    name: "Space After Comment"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning
  explicit_failure_calls:
      name: “Avoid asserting ‘false’”
      regex: ‘((assert|precondition)\(false)’
      message: “Use assertionFailure() or preconditionFailure() instead.”
      severity: warning
  multiple_empty_lines:
     name: "Multiple Empty Lines"
     regex: '((?:\s*\n){3,})'
     message: "There are too many line breaks"
     severity: error

```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents. NO
* Which Xcode version are you using (check `xcode-select -p`)? XCode 9.1
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a violation:
//violation
```
