### ISSUE TITLE
malloc_error when working with Carthage

### ISSUE THREAD

**Issue by showgp** [realm/SwiftLint#1971]
### New Issue Checklist

- Already updated SwiftLint to the latest version.
- I searched for existing issues but didn't found any infomation about this.

##### Complete output when running SwiftLint, including the stack trace and command used

Xcode Run Script Phase of my framework project:

```bash
swiftlint autocorrect
swiftlint
```

when building the framework, carthage output this:

```
Loading configuration from '.swiftlint.yml'
configuration error: 'missing_docs' is not a valid rule identifier
Valid rule identifiers:
array_init
attributes
block_based_kvov
class_delegate_protocol
closing_brace
closure_end_indentation

...

void_return
weak_delegate
xctfail_message
Linting Swift files in current working directory
Linting 'MultiPageView.swift' (1/3)
Linting 'PageControlStyle.swift' (2/3)
Linting 'MultiPageViewTests.swift' (3/3)
Done linting! Found 0 violations, 0 serious in 3 files.
swiftlint(25299,0x70000d959000) malloc: *** error for object 0x70000d955e80: Non-aligned pointer being freed (2)
*** set a breakpoint in malloc_error_break to debug
/Users/raymond/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/MultiPageView/0.0.7/Build/Intermediates.noindex/ArchiveIntermediates/MultiPageView/IntermediateBuildFilesPath/MultiPageView.build/Release-iphoneos/MultiPageView.build/Script-7127775B1FC92B1B006312BD.sh: line 3: 25299 Abort trap: 6           swiftlint
Command /bin/sh failed with exit code 134

** ARCHIVE FAILED **
```

### Environment

* SwiftLint version: 0.24.0
* Installation method used: Homebrew
* Paste your configuration file:

```yml
disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
#   - for_where
#   - force_unwrapping
opt_in_rules: # some rules are only opt-in
  - empty_count
  - missing_docs
  - closure_end_indentation
  - closure_spacing
  - force_unwrapping
  - implicitly_unwrapped_optional
  - operator_usage_whitespace
  - redundant_nil_coalescing

included:
  - ./

excluded:
  - Carthage
  - Pods
  - Demo

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

line_length: 120

type_body_length: 
  - 300 # warning
  - 400 # error

function_body_length: 15

function_parameter_count: 4

file_length:
  warning: 500
  error: 600

cyclomatic_complexity:
  warning: 5
  error: 10

type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string

identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - T
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
```
