### ISSUE TITLE
Can i create my own rule in swiftlint?

### ISSUE THREAD

**Issue by Shahbaz-Akram** [realm/SwiftLint#1992]

**Comment by kimdv** [comment]
Yeah sure, there is an option for making a [custom rule](https://github.com/realm/SwiftLint#defining-custom-rules) based on regex 😄

**Comment by Shahbaz-Akram** [comment]
I am writing this in .yml file but it don't apply. But disabled_rules rules are applying. 
`custom_rules:
    no_hiding_in_strings:
    match_kinds: string
    regex: "([n,N]inja)"
    pirates_beat_ninjas:
    excluded: .*Test\.swift
    included: .*\.swift
    match_kinds:
    - comment
    - identifier
    message: "Pirates are better than ninjas."
    name: "Pirates Beat Ninjas"
    regex: "([n,N]inja)"
    severity: error
`

**Comment by Shahbaz-Akram** [comment]
@kimdv  please guide me why it don't work.

**Comment by kimdv** [comment]
Can you provide your `.swiftlint.yml` file ?

**Comment by marcelofabri** [comment]
@Shahbaz-Akram please follow the issue template. It's there so we can properly help you.

**Comment by NMA-Dev** [comment]
I am also having the same issue. Here is my .swift.yml file:
```
custom_rules:
    pirates_beat_ninjas: # rule identifier
        included: ".*\\.swift" # regex that defines paths to include during linting. optional.
        name: "Pirates Beat Ninjas" # rule name. optional.
        regex: "([n,N]inja)" # matching pattern
        match_kinds: # SyntaxKinds to match. optional.
        - comment
        - identifier
        message: "Pirates are better than ninjas." # violation message. optional.
        severity: error # violation severity. optional.
    no_hiding_in_strings:
        regex: "([n,N]inja)"
        match_kinds: string

disabled_rules:
- trailing_newline
- opening_brace
- empty_count
- comma
- colon
- force_cast
- type_name
- variable_name_min_length
- trailing_semicolon
- force_try
- function_body_length
- nesting
- variable_name
- conditional_binding_cascade
- variable_name_max_length
- operator_whitespace
- control_statement
- legacy_constant
- line_length
- return_arrow_whitespace
- trailing_whitespace
# - closing_brace
- statement_position
- type_body_length
# - todo
- legacy_constructor
- valid_docs
- missing_docs
- file_length
- leading_whitespace
- redundant_optional_initialization
- unused_optional_initialization
- cyclomatic_complexity
- unused_optional_binding
- void_return
- implicit_getter
- unused_closure_parameter
- mark
- notification_center_detachment
- for_where
- vertical_whitespace
- empty_parameters
- discarded_notification_center_observer
- class_delegate_protocol
- syntactic_sugar
- function_parameter_count
- trailing_comma
- weak_delegate
- redundant_string_enum_value
- unused_enumerated
- empty_enum_arguments
- shorthand_operator
- empty_parentheses_with_trailing_closure
- closure_parameter_position
- redundant_discardable_let
- large_tuple
- vertical_parameter_alignment
- block_based_kvo
- compiler_protocol_init
- custom_rules
- discouraged_direct_init
- dynamic_inline
- fallthrough
- generic_type_name
- is_disjoint
- legacy_cggeometry_functions
- legacy_nsgeometry_functions
- multiple_closures_with_trailing_closure
- private_over_fileprivate
- private_unit_test
- protocol_property_accessors_order
- redundant_void_return
- superfluous_disable_command
- switch_case_alignment
- unneeded_break_in_switch
- valid_ibinspectable
- xctfail_message

opt_in_rules:
- closure_spacing
- yoda_condition

excluded: # Paths to exclude from the linter
- Pods
```

Also, I am on Xcode 9.2
