### ISSUE TITLE
Recursive config

### ISSUE THREAD

**Issue by SpeakyDre** [realm/SwiftLint#2010]
Hi,

I am trying to achieve a recursive configuration:
 - I have a swiftlint file for my project
 - I want to introduce a swiftlint config in my unit test that is different that the one of the main project

As stated in the README.md:
I set `use_nested_configs: true` value in the root `.swiftlint.yml` file.
<img width="513" alt="screen shot 2018-01-18 at 18 09 09" src="https://user-images.githubusercontent.com/33256980/35111101-bac65500-fc7a-11e7-8c5c-1643fec8ef20.png">
I created a different `.swiftlint.yml` file in my unit tests folder.
<img width="351" alt="screen shot 2018-01-18 at 18 10 07" src="https://user-images.githubusercontent.com/33256980/35111136-d583d214-fc7a-11e7-9f5d-b4f841464caa.png">

But it doesn't work.

What am I missing missing?

Thank you.

Best regards,
Audrey

**Comment by marcelofabri** [comment]
@SpeakyDre please fill the issue template, including both configuration files contents and how you're running SwiftLint. Thanks!

**Comment by SpeakyDre** [comment]
Dear @marcelofabri, thank you for your message.
```ruby
# Swiftlint configuration
# https://github.com/realm/SwiftLint
# https://github.com/realm/SwiftLint/blob/master/Rules.md
use_nested_configs: true

disabled_rules: # rule identifiers to exclude from running
  - block_based_kvo
  - class_delegate_protocol
  - trailing_whitespace
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - empty_parentheses_with_trailing_closure
  - for_where
  - implicit_getter
  - notification_center_detachment
  - private_over_fileprivate
  - private_unit_test
  - redundant_string_enum_value
  - shorthand_operator
  - unused_enumerated
opt_in_rules: # some rules are only opt-in
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - fatal_error_message
  - force_unwrapping
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - private_action
  - sorted_imports
  - unneeded_parentheses_in_closure_argument

included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
file_length:
  warning: 1000
  error: 1500
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
function_body_length:
  warning: 40
  error: 50
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
large_tuple:
  warning: 4
  warning: 5
line_length: 200
nesting:
  type_level:
    warning: 3
# they can set both implicitly with an array or they can set both explicitly
type_body_length:
  - 300 # warning
  - 400 # error
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
vertical_whitespace:
  max_empty_lines: 2

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
```


Here is the content of the nested swiftlint file:
```ruby
# Swiftlint configuration
# https://github.com/realm/SwiftLint
# https://github.com/realm/SwiftLint/blob/master/Rules.md

disabled_rules: # rule identifiers to exclude from running
  - block_based_kvo
  - class_delegate_protocol
  - trailing_whitespace
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - empty_parentheses_with_trailing_closure
  - for_where
  - implicit_getter
  - notification_center_detachment
  - private_over_fileprivate
  - private_unit_test
  - redundant_string_enum_value
  - shorthand_operator
  - unused_enumerated
opt_in_rules: # some rules are only opt-in
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - fatal_error_message
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - private_action
  - sorted_imports
  - unneeded_parentheses_in_closure_argument

included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
file_length:
  warning: 1000
  error: 1500
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
function_body_length:
  warning: 40
  error: 50
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
large_tuple:
  warning: 4
  warning: 5
line_length: 200
nesting:
  type_level:
    warning: 3
# they can set both implicitly with an array or they can set both explicitly
type_body_length:
  - 300 # warning
  - 400 # error
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
vertical_whitespace:
  max_empty_lines: 2

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
```


As you can see, I removed from the nested configuration the rule `force_unwrapping` because I don't care so much in my unit tests. But I still get the warning in the code.

I run swiftlint in the main target via a run script build phase:
```
"${PODS_ROOT}/SwiftLint/swiftlint"
```
The unit tests target doesn't have this build phase specified.


Thank you

**Comment by ornithocoder** [comment]
@SpeakyDre there's not need to recreate the entire swiftlint configuration file for the nested context. The file can contain the "diff" of the original configuration and the one you want to apply to that directory.

To give you an example, this is my configuration (for the entire bundle):

```yml
$ cat .swiftlint.yml
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - discouraged_object_literal
  - empty_count
  - explicit_init
  - fatal_error_message
  - file_length
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefixed_toplevel_constant
  - private_action
  - prohibited_super_call
  - redundant_nil_coalescing
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded:
  - Pods
  - ci
  - fastlane

custom_rules:
  quickspec_class_name:
    name: "Invalid Test Class Name"
    regex: "class\\s+(.*)[^Tests]:\\s+QuickSpec"
    message: "A test class name must end with 'Tests'"
    severity: error
  localized_string:
    excluded: "Extensions/Foundation/String.swift"
    name: "Localized String"
    regex: "NSLocalizedString(.*[^,], comment: .*[^)])"
    message: "Please use .localized instead"
    severity: warning
```

And the rules I want to enable and disable for the tests (nested config). Everything thing else keeps valid for the nested directory:

```yml
$ cat Tests/.swiftlint.yml
disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - line_length
  - type_body_length
  - type_name

opt_in_rules:
  - discouraged_direct_init
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - xctfail_message

discouraged_direct_init:
  types:
    - Bundle
    - UIDevice
    - UIWindow
```
