### ISSUE TITLE
Problem call from the Jenkins pipeline "undefined symbol: _T0SS10FoundationE11capitalizedSSfg"

### ISSUE THREAD

**Issue by ditansu** [realm/SwiftLint#2026]
### New Issue Checklist

- [ ] Updated SwiftLint to the latest version
- [ ] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report
It's correct work if  run in shell, but if start from Jenkins pipeline then get error 

##### Complete output when running SwiftLint, including the stack trace and command used

Jenkins console 
```bash
[ch-server] Running shell script
+ /usr/local/bin/swiftlint lint --reporter checkstyle
/usr/local/bin/swiftlint: symbol lookup error: /usr/local/bin/swiftlint: undefined symbol: _T0SS10FoundationE11capitalizedSSfg
```
Jenkins config cut 
```groovy 
def check_codestyle() {
 stage("check codestyle"){
      //start
      sh '/usr/local/bin/swiftlint lint --reporter checkstyle > checkstyle-result.xml'
      checkstyle canComputeNew: false, defaultEncoding: '', healthy: '', pattern: 'checkstyle-result.xml', unHealthy: ''
      slackSend( color: 'good', message: "Codestyle check is done :smiley:")
 }
}
```

### Environment

* SwiftLint version `0.24.2`
* Installation method used see https://github.com/realm/SwiftLint/issues/732
* Paste your configuration file:

```yml
excluded: # paths to ignore during linting.
  - Devops
  - Public
  - .build
identifier_name:
  min_length: 2
  max_length: 50

force_try:
  severity: warning 

line_length: 180

trailing_whitespace: 
  ignores_empty_lines: true 

colon:
  apply_to_dictionaries: false

disabled_rules:
  - nesting
  - unused_optional_binding

opt_in_rules:  
  - literal_expression_end_indentation
```
