### ISSUE TITLE
SwiftLint fails on circleCI and passes locally  because of force casting

### ISSUE THREAD

**Issue by Vadimkomis** [realm/SwiftLint#2087]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report
When I enable force casting as a rule in my linter it makes my build to fail on circleci. I installed the swiftlinter via cocoa pods. It keeps complaining about force casting as you can see below. I think it has something to do with the run script that for swxftlint. 
##### Complete output when running SwiftLint, including the stack trace and command used
```bash
Testing failed:
	Force Cast Violation: Force casts should be avoided. (force_cast)
	Force Cast Violation: Force casts should be avoided. (force_cast)
	Force Cast Violation: Force casts should be avoided. (force_cast)
** TEST FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/distiller/Library/Developer/Xcode/DerivedData/Freshly-aqfftomwdlyzfadmktypldmeqhgq/Build/Intermediates.noindex/Freshly.build/Debug-iphonesimulator/Freshly\ Dev.build/Script-DDBA23CD2021057C00E0D5AE.sh
(1 failure)
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
* Paste your configuration file:
```yml

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Packages
- Pods
- FreshlyTests
- FreshlyUITests
- Freshly/Controllers/
- Freshly/AppDelegate.swift
- Freshly/lib/
- Freshly/models/
- Freshly/style/
- Freshly/test-helpers/


opt_in_rules: # some rules are only opt-in


disabled_rules: # rule identifiers to exclude from running
- valid_docs   # /// is valid and used by Xcode
- cyclomatic_complexity
- identifier_name
- syntactic_sugar
- type_body_length
- function_body_length
- file_length
- vertical_parameter_alignment
- function_parameter_count
- implicit_getter
- force_try
- shorthand_operator
- type_name
- large_tuple
- trailing_whitespace
- opening_brace
- colon
- comma
- todo
- empty_parentheses_with_trailing_closure
- unneeded_break_in_switch
- unused_closure_parameter
- closure_parameter_position
- switch_case_alignment

line_length: 270

type_name:
min_length: 2


```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcode-select -p`)?
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a violation:
let foo = try! bar()
```
