### ISSUE TITLE
Question: Apply custom rule to detect space before braces

### ISSUE THREAD

**Issue by falnatsheh** [realm/SwiftLint#2213]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

I searched the issue list and found [this](https://github.com/realm/SwiftLint/issues/640) rule request that is related. I'm hoping this will be added sometime soon but for the time being I want to add custom rule that detect space before braces. 

 [This](https://regex101.com/r/pF8mY2/1) regex works fine when tested outside SwiftLint but I can't get it to work when I added as a custom rule: 

``` yaml
custom_rules:
  no_line_around_parentheses:
    regex:  '\\{\\h*\\R\\K\\h*\\R|\\R\\K\\h*\\R(?=\\h*\\})'
    message: New Line before or after a parentheses.

```

**Comment by SDGGiesbrecht** [comment]
@falnatsheh,

From the [YAML specification](http://yaml.org/spec/1.2/spec.html#id2776092):

> Note that escape sequences are only interpreted in double‐quoted scalars. In all other scalar styles, the `\` character has no special meaning [...]

Either remove the escapes, or switch to double quotes.

**Comment by falnatsheh** [comment]
I have tried both but still not luck. Is it possible that some part of the pattern is not supported? 

```yaml
custom_rules:
  no_line_around_parentheses:
    regex:  '\{\h*\R\K\h*\R|\R\K\h*\R(?=\h*\})'
    message: New Line before or after a parentheses.
```

```yaml
custom_rules:
  no_line_around_parentheses:
    regex:  "\\{\\h*\\R\\K\\h*\\R|\\R\\K\\h*\\R(?=\\h*\\})"
    message: New Line before or after a parentheses.
```

**Comment by SDGGiesbrecht** [comment]
@falnatsheh,

> Is it possible that some part of the pattern is not supported?

Apparently. You would have to look into [`NSRegularExpression`](https://developer.apple.com/documentation/foundation/nsregularexpression) to find the details, but removing `\K` worked for me:

```yaml
custom_rules:
  no_line_around_parentheses:
    regex:  '\{\h*\R\h*\R|\R\h*\R\h*\}'
    message: No scope should begin or end with an empty line.
```

(I also removed the last capture group. It has no real effect since SwiftLint reports just one index, not the whole range.)
