### ISSUE TITLE
SwiftLint has stdout and stderr flipped

### ISSUE THREAD

**Issue by kballard** [realm/SwiftLint#2228]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Bug Report

SwiftLint is printing status lines (e.g. "Linting 'foo' (23/50)") to stderr and printing the actual warnings to stdout. This is the exact opposite of what it should be doing, and seems the most likely cause of swiftlint errors not showing up for us in CI when building with fastlane.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint 2>/dev/null
…/path/to/Foo.swift:234:52: warning: Comma Spacing Violation: There should be no space before and one after any comma. (comma)
$ swiftlint lint >/dev/null
Loading configuration from '.swiftlint.yml'
Linting Swift files in current working directory
Linting 'Foo.swift' (1/470)
Linting 'Bar.swift' (2/470)
…
Done linting! Found 1 violation, 0 serious in 470 files.
```

### Environment

* SwiftLint version 0.25.1
* CocoaPods
* Paste your configuration file:

```yml
disabled_rules:
  - force_cast
  - notification_center_detachment
  - identifier_name
  - trailing_comma
  - type_name
  - trailing_whitespace
  - conditional_returns_on_newline
  - opening_brace
  - cyclomatic_complexity
  - todo
  - fallthrough
  - force_try
  - unneeded_parentheses_in_closure_argument
  - nesting
  - unused_closure_parameter
  - large_tuple
  - generic_type_name
opt_in_rules:
  - empty_count
  - closure_spacing
  - conditional_returns_on_newline
  - explicit_init
  - fatal_error_message
  - first_where
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - override_in_extension
  - private_over_fileprivate
  - private_unit_test
included:
  - ./
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Code/GraphQL/API.swift

# Rule Configuration
line_length: 200
function_body_length:
  warning: 200
  error: 400
type_body_length:
  warning: 1000
  error: 1500
file_length:
  warning: 1500
  error: 2000
function_parameter_count:
  warning: 10
type_name:
  min_length: 4
  max_length: 60
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
private_outlet:
  allow_private_set: true

reporter: "xcode"
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
 No
* Which Xcode version are you using (check `xcode-select -p`)? Xcode 9.2 (9C40b)
