### ISSUE TITLE
.swiftlint.yml is completely ignored

### ISSUE THREAD

**Issue by andrelind** [realm/SwiftLint#229]
I just can't get the .swiftlint.yml to load, I've tried to have it in the root folder of my project, in the built app folder, even in /usr/local/bin but it just won't load...!

I've tried with both a clean build from master branch as well as the 0.4.0 release

swftlint runs as it should but it doesn't ignore the /Pods and /Carthage folders :-(

My file
`excluded: # paths to ignore during linting. overridden by `included`.`
`	- Carthage`
`	- Pods`
`# parameterized rules can be customized from this configuration file`
`line_length: 200`
`# parameterized rules are first parameterized as a warning level, then error level.`
`type_body_length:`
`	- 300 # warning`
`	- 400 # error`
`# parameterized rules are first parameterized as a warning level, then error level.`
`variable_name_max_length:`
`	- 40 # warning`
`	- 60 # error`
`# parameterized rules are first parameterized as a warning level, then error level.`
`variable_name_min_length:`
`	- 3 # warning`
`	- 2 # error`

**Comment by bensarz** [comment]
Having the same problem.
Is there a `brew` way of returning to 0.3.0?

**Comment by jpsim** [comment]
Are you running `swiftlint` from the same directory in which `.swiftlint.yml` is located?

When you run `swiftlint`, does it print something like "Loading configuration from 'config path'" to stderr?

If not, then it means the configuration file cannot be found. You can specify a path to your configuration file using the `--config [path to .swiftlint.yml]` command line flag.

**Comment by bensarz** [comment]
I have it setup properly as per the README instructions.
My file is named `.swiftlint.yml` and it is in the root directory of the project, side by side with the `.xcworkspace`.

I tried passing the path to `swiftlint` like this:

```
$ cd MyProject
$ swiftlint --config .swiftlint.yml
Unrecognized command: '--config'. See `swiftlint help`.
```

As you can see, I'm getting an error regarding unrecognized command.

**Comment by bensarz** [comment]
Ok, I'm obviously speaking before thinking here.

I ran this command successfully:

```
$ swiftlint lint --config .swiftlint.yml
```

There's the content of my `.swiftlint.yml` file:

```yaml
disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
  - line_length
  - nesting
#  - opening_brace
#  - operator_whitespace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
   - trailing_whitespace
#  - type_body_length
#  - type_name
#  - variable_name_max_length
#  - variable_name_min_length
#  - variable_name
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  - MyProject
  - MyProjectKeyboard
  - MyProjectTests
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods

file_length:
  - 1000
function_body_length:
  - 75
  - 100
type_body_length:
  - 400 # Warning
  - 500 # Error
```

I still get a bunch of these:

```
../Pods/Alamofire/Source/Alamofire.swift:28: warning: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
../Pods/Alamofire/Source/Alamofire.swift:356: warning: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
../Pods/Alamofire/Source/Alamofire.swift:360: warning: Trailing Whitespace Violation: Lines should not have trailing whitespace. (trailing_whitespace)
```

The `Pods` folder should be ignore as well as the `Trailing Whitespace` rule.
