### ISSUE TITLE
toggle_bool rule is not a valid rule identifier

### ISSUE THREAD

**Issue by wousser** [realm/SwiftLint#2440]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug
Loading configuration from '.swiftlint.yml'
configuration error: 'toggle_bool' is not a valid rule identifier

Added toggle_bool rule to .swiftlint.yml, get erorr that it's not a valid rule identifier.
Rule: https://github.com/realm/SwiftLint/blob/master/Rules.md#toggle-bool

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
Loading configuration from '.swiftlint.yml'
configuration error: 'toggle_bool' is not a valid rule identifier
configuration error: 'identical_operands' is not a valid rule identifier
Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.27.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

```yml
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- fastlane

disabled_rules:
- line_length
#- type_body_length
- trailing_whitespace
#- todo
#- vertical_whitespace
#- file_length
opt_in_rules: # some rules are only opt-in
- control_statement
- empty_count
- trailing_newline
- colon
- comma
- empty_string
#- private_action
#- private_outlet
- redundant_type_annotation
- sorted_first_last
- switch_case_on_newline
- toggle_bool
- override_in_extension
#- attributes
- fatal_error_message
#- force_unwrapping
- identical_operands

force_cast: warning

force_try:
  severity: warning

type_body_length:
- 300 # warning
- 400 # error

file_length:
  warning: 500
  error: 800

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
- 3
- 4

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube)

```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
No
* Which Xcode version are you using (check `xcode-select -p`)? 10.0 (10A255)
* Do you have a sample that shows the issue? -
