### ISSUE TITLE
configuration error: '________' is not a valid rule identifier

### ISSUE THREAD

**Issue by hg-andy-kim** [realm/SwiftLint#2449]
### New Issue Checklist

- [v] Updated SwiftLint to the latest version
- [v] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug
i got a configuration error from recently rules.

##### Complete output when running SwiftLint, including the stack trace and command used
```
configuration error: 'closure_body_length' is not a valid rule identifier
configuration error: 'static_operator' is not a valid rule identifier
configuration error: 'toggle_bool' is not a valid rule identifier
configuration error: 'identical_operands' is not a valid rule identifier
configuration error: 'unused_import' is not a valid rule identifier
configuration error: 'unused_private_declaration' is not a valid rule identifier
configuration error: 'collection_alignment' is not a valid rule identifier
```
```bash
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.27.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
CocoaPods
* Paste your configuration file:
```yml
# 자세한 설명은
# https://github.com/realm/SwiftLint/blob/master/Rules.md
# 에서 참고 부탁드립니다!


## 검사할 파일 목록 #############################

included: # 포함할 파일 목록
- ../Src

excluded: # 제외할 파일 목록. `included`보다 우선순위 높음
- ../Carthage
- ../Pods
- ../Library
# - ../Src/Util/CommentManager.swift #warning이 많으면 다시 주석해제. 추후 룰 적용이 완료되면 삭제.



## 룰 #######################################

disabled_rules: # 제외할 룰
  #당장은 사용하지 않을 것이지만 추후 사용할 룰
  - cyclomatic_complexity # function의 순환복잡도가 제한되어있음. (ControlFlow사용의 제한) #warning작업이 완료되면 제거.
  - multiple_closures_with_trailing_closure #2개 이상의 클로져를 넘기는 경우에는 Trailing Closure 문법이 사용되지 않아야한다. #어느정돌 리팩토링 작업이 이루어 진 후 논의.
  - identifier_name # 네이밍 변경 후 제거 필요.
  - type_name # 네이밍 변경 후 제거 필요.

opt_in_rules: # 추가할 룰(기본 룰을 제외하고)
  #metrics
  - closure_body_length # Closure의 body는 너무 많은 라인으로 커지면 안됨.

  #idiomatic
  - discouraged_optional_boolean # Boolean형은 optional을 사용하지 않는것을 선호함.
  - fatal_error_message # FatalError call을 할때는 메시지를 넣어야함.
  - force_unwrapping # Force unwrapping은 피해야한다.
  - implicitly_unwrapped_optional # 가능하면 Implicity unwrapped optional은 피하라. (타입명시할때 Type!으로 선언되는 경우.)
  - pattern_matching_keywords # 다양한 패턴의 조합을 튜플을 이용하여 결합하라.
  - redundant_nil_coalescing # nil 병합 연산자는 왼쪽연산자가 nil일 경우가 있을 경우에만 사용. 오른쪽 연산자에 nil을 넣어서 사용하는것은 불필요함.
  - static_operator # 연산자는 static function으로 선언되어야함.
  - strict_fileprivate # fileprivate는 피해야함.
  - toggle_bool # someBool.toggle() 이 someBool = !someBool 보다 선호됨.
  - unavailable_function # 구현되지 않은 function은 unavailable로 표기되어야함.
  - untyped_error_in_catch # catch문에서 error변수는 type casting없이 사용될 수 없음.


  #lint
  - anyobject_protocol # class 전용 protocol은 class를 사용하는것 보다 AnyObject를 사용하는것이 선호됨.
  - array_init # Array를 변환할때 Array(seq)보단 seq.map { $0 }을 선호.
  - empty_xctest_method # 비어있는 XCTest 메소드는 피해야함.
  - identical_operands # 두개의 같은 피연산자를 비교하는것은 실수일 것으로 예상됨.
  - lower_acl_than_parent # 가까운 부모보다 낮은 ACL을 갖도록 선언해야함.
  - overridden_super_call # 몇몇의 override된 메소드들은 항상 super 메소드를 호출해야함.
  - override_in_extension # extension은 override 선언을 하면 안됨.
  - private_action # IBAction은 private여야 한다
  - private_outlet # IBOutlet은 상위 레이어에서의 UIKit 누수를 방지하기 위해 private으로 선언되어야 한다.
  - prohibited_super_call # 몇몇 메소드들은 super 호출을 하지말라.
  - required_enum_case # 특정한 프로토콜을 충족하는 Enum은 특정한 case들을 구현해야함.
  - unused_import # 모든 import된 모듈들은 컴파일시 사용되어야 함.
  - unused_private_declaration # Private 선언된 변수들은 그 파일안에서 사용되어야 함.
  - yoda_condition # 비교연산자의 왼쪽에 변수, 상수는 오른쪽에 위치해야함.


  #performance
  - contains_over_first_not_nil # contains가 first(where:) != nil를 사용하는것 보다 더 선호됨.
  - empty_string # 빈 스트링을 비교할때는 isEmpty를 사용하는것이 선호됨.
  - first_where # 컬렉션에서 .filter{ }.first보다 .first(where:)가 선호됨.
  - sorted_first_last # min() 혹은 max() 사용을 sorted().first 혹은 sorted().last 사용하는것 보다 선호함.


  #style
  - closure_spacing # 클로져는 각각의 중괄호({ }) 사이에 한칸의 공백만 있어야한다.
  - collection_alignment # literal로 선언된 collection의 모든 요소들은 세로로 정렬이 되어야함.
  - conditional_returns_on_newline # 조건문에서의 return은 다음줄에 선언되어야함.
  - empty_enum_arguments # associated type의 enum의 argument가 사용되지 않으면 생략 될 수 있다.
  - implicit_return # Closure에서 implicit return이 선호된다.
  - literal_expression_end_indentation # Array와 Dictionary의 literal선언의 끝은 literal선언의 시작부분과 같은 들여쓰기가 되어있어야함
  - modifier_order # Modifier의 순서는 일관성 있어야 함.
  - multiline_arguments # function arguments들은 같은라인에 존재하거나 한 라인에 하나만 있어야 한다.
  - multiline_function_chains # Function Chaining은 한줄에 하나씩 부르거나 같은라인에 모두 호출해야함.
  - multiline_parameters # Function 과 method 파라미터는 같은라인에 있거나 라인당 하나씩 있어야 한다.
  - operator_usage_whitespace # Operator들이 사용될때에는 operator사이에 한개의 whitespace로 쌓여 있어야함.
  - single_test_class # Test 파일은 한개의 QuickSpec 또는 XCTest Test Class를 포함해야한다.
  - sorted_imports # Imports들은 정렬되어야 함.
  - switch_case_on_newline # Switch문 안에 있는 case들은 항상 새로운 라인에 있어야함.
  - unneeded_parentheses_in_closure_argument # closure argument들을 선언할때에는 괄호()가 불필요함.
  - vertical_parameter_alignment_on_call # Method call을 할때 여러라인으로 적게 되는 경우, 파라미터들은 수직으로 정렬되어야함.


#보류 한 opt-in rule

  #idiomatic
#  - convenience_type # static 변수만 사용하는 경우 caseless enum을 사용하는것이 선호됨.

  #lint
  #performance
#  - empty_count # count == 0 보다 isEmpty로 empty체크하는것을 선호함


# 사용하지 않는 opt-in rule

  #idomatic
#  - discouraged_optional_collection # 비어있는 Collection을 사용하는 것이 Optional Collection을 사용하는 것 보다 더 선호됨.
#  - discouraged_object_literal # Prefer initializers over object literals
#  - explicit_acl # 모든 선언은 ACL이 명시적으로 선언되어야함.
#  - explicit_enum_raw_value # Enum의 raw value는 명시적으로 할당되어야함.
#  - explicit_top_level_acl # 최상위 선언에는 명시적으로 ACL keyword가 붙어야함.
#  - explicit_type_interface # 프로퍼티들은 type이 명시되어야함.
#  - extension_access_modifier # Extension에 Access Modifier를 붙이는것이 선호됨.
#  - file_name # 파일명은 파일안에 선언해놓은 타입 혹은 extension과 일치해야한다.
#  - function_default_parameter_at_end # default 파라미터들은 parameter들의 끝에 위치되는것이 선호됨.
#  - no_extension_access_modifier # Extension에는 Access Modifier를 붙이지 않는 것을 선호.
#  - no_grouping_extension # Extension을 코드를 Grouping하는 용도로 사용하지 말아야 함.
#  - object_literal # image와 color init호출 보다 Object literal 사용을 선호함.
#  - redundant_type_annotation # 변수에 불필요한 타입선언은 필요없다.

  #lint
#  - missing_docs # 선언부에는 반드시 선언부에 대한 문서작성을 해야함.
#  - prohibited_interface_builder # Interface Builder를 이용해서 View를 생성하는것을 피해라.
#  - quick_discouraged_call # Quick의 description 혹은 context에서는 call 하지말라.
#  - quick_discouraged_focused_test # Focused test를 하지말라. 그렇지 않으면 focused 되어있는 동안 다른 test들이 동작하지 않을 것이다.
#  - quick_discouraged_pending_test # Pending test를 하지말라. 그렇지 않으면 pending되어있는동안 다른 test들이 동작하지 않을 것이다.

  #style
#  - prefixed_toplevel_constant # 최상위의 상수들은 prefix로 k를 붙여야함.
#  - closure_end_indentation # 클로져의 끝부분은 클로져의 시작라인과 같은 들여쓰기를 써야함.
#  - file_header # 헤더 주석은 프로젝트 패턴과 일치해야함
#  - let_var_whitespace # let과 var는 공백행으로 된 다른 문자로 구분되어야 함.
#  - number_separator # 큰 10진수의 숫자를 표기할때 1000 단위로 underscore(_) 를 사용해야함.
#  - trailing_closure # Trailing closure 문법은 사용가능할때마다 사용해야함.
#  - nimble_operator # matcher function을 사용하는 것 보다 Nimble operator를 오버로딩 하는것이 선호됨


## 룰 - Optional Binding 관련 ###########

force_cast:
  severity: error
force_try:
  severity: error
force_unwrapping:
  severity: error
implicitly_unwrapped_optional:
  severity: error
# 경고 및 에러 둘 다 존재하는 룰의 경우 값을 하나만 지정하면 암시적으로 경고 수준에 설정됨


## 룰 - 라인수 제한 설정 ######################

function_body_length:  #default - warning : 40, error : 100 #리뷰 필요
  - 300 #리뷰 필요 에러 제거 후 변경 필요.
  - 500 #리뷰 필요 에러 제거 후 변경 필요.

type_body_length:   #default - warning : 200, error : 350  #리뷰 필요
  - 300 # 경고    #리뷰 필요
  - 400 # 에러    #리뷰 필요

# 파일의 라인수 제한
file_length:    #default - warning : 400, error : 1000     #리뷰 필요
  warning: 2000  #리뷰 필요
  error: 3000    #리뷰 필요

## 룰 - 글자수 제한 설정 ######################

# 한 라인에 글자수 제한
line_length:   #default - warning : 120, error : 200         #리뷰 필요
  - 300 # 경고           #리뷰 필요
  - 400 # 에러           #리뷰 필요

# 타입의 글자수 제한
type_name:
  min_length:
    warning: 0   #default : 3
    error: 0     #default : 0
  max_length:
    warning: 40   #default : 40
    error: 50     #default : 1000
  excluded:
    - iPhone

# 변수/enum의 case 글자수 제한
identifier_name:
  min_length:
    warning: 0
    error: 0
  excluded:
    - id
    - URL

## 보고 유형 #################################

# xcode, json, csv, checkstyle, junit, html, emoji 중 선택 가능
reporter: "xcode"

```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
no
* Which Xcode version are you using (check `xcode-select -p`)?
Version 10.1 (10B61)
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a violation:
let foo = try! bar()
```
