### ISSUE TITLE
Rule Request: no-print

### ISSUE THREAD

**Issue by fjcaetano** [realm/SwiftLint#2484]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

1. Why should this rule be added? Share links to existing discussion about what
   the community thinks about this.
> Leftover logs in production can cause security breaches in any app. Also, logging to the console has performance drawbacks on iOS.
2. Provide several examples of what _would_ and _wouldn't_ trigger violations.
> Any calls to `print`, `debugPrint` or `dump` would trigger a warning violation.
3. Should the rule be configurable, if so what parameters should be configurable?
> I cannot think of anything that should be configurable at this moment.
4. Should the rule be opt-in or enabled by default? Why?
   See [README.md](../README.md#opt-in-rules) for guidelines on when to mark a rule as opt-in.
> Considering how it could pose as a security violation, I do believe `no-print` should be enabled by default.

If this RFC is approved, I'm more than happy to work on it and open a PR.

**Comment by fassko** [comment]
@fjcaetano You achieve it with custom rule, for instance:

```
custom_rules:
  disable_print:
    included: ".*\\.swift"
    name: "print usage"
    regex: "((\\bprint)|(Swift\\.print))\\s*\\("
    message: "Prefer os_log over print"
    severity: error
```

I was actually searching excatly for this and I do agree that this could make it's way to library itself as built-in rule. I found answer for this here: https://stackoverflow.com/a/50531401/964492
