### ISSUE TITLE
Custom Rule not working

### ISSUE THREAD

**Issue by kalmeshnfk** [realm/SwiftLint#2507]
### Describe the bug
Added a Custom Rule for all hardcoded strings in the code except color codes that start with #. However, its not working.
 
```yml
# insert yaml contents here

whitelist_rules:
- custom_rules

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Pods

line_length: 300

custom_rules:
  no_hard_coded_strings:
    regex: '^[^#][a-zA-Z0-9][a-zA-Z0-9! ]+'
    match_kinds:
        - string
    message: "Hard-coded string is never a good practice"
    severity: warning

**Comment by jpsim** [comment]
I forget exactly the supposed behavior of `whitelist_rules` with `custom_rules`, but you might need to add your custom rule to the whitelist. Can you try that and report back?

```yaml
whitelist_rules:
  - custom_rules
  - no_hard_coded_strings

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Pods

line_length: 300

custom_rules:
  no_hard_coded_strings:
    regex: '^[^#][a-zA-Z0-9][a-zA-Z0-9! ]+'
    match_kinds:
        - string
    message: "Hard-coded string is never a good practice"
    severity: warning
```
