### ISSUE TITLE
False positive in rule explicit_type_interface with allowRedundancy

### ISSUE THREAD

**Issue by Dschee** [realm/SwiftLint#2636]
For this code

```swift
private let l10n = L10n.Communication.self
```

using this configuration

```yaml
explicit_type_interface:
  allow_redundancy: true
  excluded:
    - local
```

there shouldn't be any warnings, but there is.

Rationale: The usage of this rule here is mostly for improving readability, not performance of the compiler. We also try to prevent redundant type annotations, why explicitly writing the type here wouldn't be right. Thus this rules behavior must be changed.
