### ISSUE TITLE
Fileprivate constants should be excluded by the `identifier_name` rule.

### ISSUE THREAD

**Issue by Juice805** [realm/SwiftLint#2646]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

A `fileprivate` (or file level `private`) constant should be excluded from the `identifier_name` rule.

> In an exception to the above, variable names may start with a capital letter when they are declared static and immutable.

### Environment

* SwiftLint version: 0.30.1
* Installation method used: Portable
* Paste your configuration file:

```yml
# rules: https://github.com/realm/SwiftLint/blob/master/Rules.md
disabled_rules: # rule identifiers to exclude from running
opt_in_rules: # some rules are only opt-in
  - empty_count
  - missing_docs
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests
  - Package.swift
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests/
  - Tests/
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
indentation: tabs
line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
identifier_name:
  min_length: # only min_length
    error: 3 # only error
reporter: "emoji" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
```

* Do you have a sample that shows the issue?

```swift
// This triggers a violation:
fileprivate let DefaultMongoDBPort: Int = 27017

struct Test {
    init() {
        print(DefaultMongoDBPort)
    }
}
```
