### ISSUE TITLE
Xcode 10.2: swiftlint aborts in macOS 10.14.4 (libswiftCore.dylib)

### ISSUE THREAD

**Issue by Panajev** [realm/SwiftLint#2695]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Swiftlint crashes after being launched on macos 10.14.4.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
This copy of libswiftCore.dylib requires an OS version prior to 10.14.4.
[1]    88598 abort      swiftlint lint
```

```bash
$ swiftlint version
This copy of libswiftCore.dylib requires an OS version prior to 10.14.4.
[1]    90167 abort      swiftlint version
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.31.0, but I got this from homebrew info as the `swiftlint version` command crashes too.
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

```yml
disabled_rules: # rule identifiers to exclude from running
  - colon
  - control_statement
  - identifier_name
  - unused_optional_binding
  - notification_center_detachment
  - opening_brace
opt_in_rules: # some rules are only opt-in
  - empty_count
  - closure_spacing
  - fatal_error_message
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - NativeRoutingModule/NativeRoutingModule
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - XML
  - NativeRoutingModule/Pods
  - NativeRoutingModule/NativeRoutingModuleTests

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 195
# they can set both implicitly with an array
type_body_length:
  - 350 # warning
  - 450 # error
function_body_length:
  - 80 # warning
  - 140 # error 
# or they can set both explicitly
file_length:
  warning: 1250
  error: 2000
cyclomatic_complexity:
  - 16
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - url
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcode-select -p`)? Xcode 10.2 (/Applications/Xcode.app/Contents/Developer)
