### ISSUE TITLE
Can't compile and run SwiftLint (Illegal instruction: 4)

### ISSUE THREAD

**Issue by ppamorim** [realm/SwiftLint#2763]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Same as this bug report: https://github.com/realm/SwiftLint/issues/583

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
swiftlint lint
Loading configuration from '.swiftlint.yml'
Found a configuration for 'type_body_length' rule, but it is disabled on 'disabled_rules'.
Found a configuration for 'explicit_type_interface' rule, but it is disabled on 'disabled_rules'.
Linting Swift files at paths 
Linting 'CircularTransition.swift' (1/322)
//...
Linting 'CreateData.swift' (322/322)
Illegal instruction: 4
```

### Environment

* SwiftLint version: 0.32.0
* Installation method used: Homebrew
* Paste your configuration file:

```yml
disabled_rules:
  - identifier_name
  - line_length
  - todo
  - cyclomatic_complexity
  - type_body_length
  - file_length
  - function_body_length
  - function_parameter_count
  - nesting
  - block_based_kvo

  # Remove:
  - unused_closure_parameter
  - explicit_type_interface

opt_in_rules: # some rules are only opt-in
  - explicit_type_interface
  - force_unwrapping
  - implicit_return
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_string
  - contains_over_first_not_nil
  # - empty_count
  # - first_where

excluded:
  - Carthage
  - Pods

  - UnitTests
  - UITests
  - Frameworks
  - aws-sdk-ios
  - realm-cocoa
  - .*\\.c

force_cast: warning
force_try: warning

# - Force explicity type for every variable on the project, this is needed to let the Swift compiler more lightweight
explicit_type_interface: 
  severity: warning

type_body_length:
  - 1500 # warning
  - 2000 # error
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No.
* Which Xcode version: Only 10.2.1. It's a brand new MBP.
* Do you have a sample that shows the issue? Run 'swiftest' and bang. I am also not able to compile my project because SwiftLint crashes.

Console crash report:

[console_reports.zip](https://github.com/realm/SwiftLint/files/3191751/console_reports.zip)
