### ISSUE TITLE
Warnings and errors do not appear in Xcode 11 editor

### ISSUE THREAD

**Issue by gkmrakesh** [realm/SwiftLint#2935]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Swift lint warning and errors are not highlighted in the Xcode editor for the project created with old Xcode.

My project initially created with Xcode 9.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint --config ./Configurations/.swiftlint.yml
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.36.0

* Installation method used (Homebrew, CocoaPods, building from source, etc)?
CocoaPods

* Paste your configuration file:

```yml
opt_in_rules:
    - anyobject_protocol
    - contains_over_first_not_nil
    - attributes
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - discouraged_object_literal
    - discouraged_optional_boolean
    - empty_count
    - empty_string
    - empty_xctest_method
    - first_where
    - force_unwrapping
    - identical_operands
    - last_where
    - legacy_random
    - let_var_whitespace
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - operator_usage_whitespace
    - overridden_super_call
    - prohibited_super_call
    - redundant_nil_coalescing
    - redundant_type_annotation
    - sorted_first_last
    - toggle_bool
    - unowned_variable_capture
    - untyped_error_in_catch
    - unused_declaration
    - unused_import
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_between_cases
    - yoda_condition

disabled_rules:
    - file_length
    - todo
    - type_body_length
    - weak_delegate
    - trailing_whitespace

excluded:
    - Pods
    - Configurations

# configurable rules can be customized
# idiomatic
force_cast:
    severity: warning
force_try: 
    severity: warning
empty_count:
    severity: warning
shorthand_operator:
    severity: warning
unused_declaration:
    severity: warning

# metrics
closure_body_length:
    warning: 20
line_length:
    warning: 400
    error: 600
function_body_length:
    warning: 20
cyclomatic_complexity:
    warning: 6
function_parameter_count:
    warning: 6
large_tuple: 
    warning: 5
nesting:
    type_level:
        warning: 3
    statement_level:
        warning: 5

# style
identifier_name:
    min_length:
        warning: 1
    max_length:
        warning: 40
    allowed_symbols:
        - "_"
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcode-select -p`)?
Xcode 11.1
Build version 11A1027

* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

[IntroReduxStarter.zip](https://github.com/realm/SwiftLint/files/3794515/IntroReduxStarter.zip)
