### ISSUE TITLE
Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed

### ISSUE THREAD

**Issue by cristianbaluta** [realm/SwiftLint#2937]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I updated to Catalina and xcode 11.1 and swiftlint doesn't run anymore.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file /private/tmp/swiftlint-20191025-96834-1hxdwg2/.build/checkouts/SourceKitten/Source/SourceKittenFramework/library_wrapper.swift, line 39
Illegal instruction: 4
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.36.0
* Installation method used (Homebrew)
* Paste your configuration file:

```yml
#Last change with swiftlint version 0.27.0
whitelist_rules:
    - class_delegate_protocol
    - closing_brace
    - colon
    - comma
    - compiler_protocol_init
    - control_statement
    - custom_rules
#    - cyclomatic_complexity
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - explicit_init
    - file_length
    - force_try
#    - force_cast
#    - force_unwrapping
    - function_body_length
    - function_parameter_count
    - implicit_getter
    - large_tuple
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_nsgeometry_functions
    - legacy_constant
    - legacy_constructor
    - line_length
#    - nesting
    - object_literal
    - opening_brace
    - operator_whitespace
    - overridden_super_call
#    - private_outlet
    - prohibited_super_call
    - redundant_nil_coalescing
    - redundant_optional_initialization
    - redundant_string_enum_value
    - redundant_void_return
    - return_arrow_whitespace
    - statement_position
    - switch_case_on_newline
    - syntactic_sugar
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - type_body_length
    - type_name
    - unused_closure_parameter
    - unused_optional_binding
    - valid_ibinspectable
    - vertical_whitespace
    - weak_delegate

included:
    - xxx
    - xxxTests
    - xxxUITests
    - Watch Extension
    - Shared
excluded:
    - Pods
function_parameter_count:
    warning: 8
    error: 8
function_body_length:
    warning: 90
    error: 100
large_tuple:
    warning: 5
    error: 5

# rules that have both warning and error levels, can set just the warning level
line_length: 170
type_body_length:
  warning: 600
  error: 700
file_length:
  warning: 1800
  error: 2000
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)

```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcode-select -p`)? 11.1 /Library/Developer/CommandLineTools
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a violation:
Don't think it matters
```
