### ISSUE TITLE
Rule Request: [explicit_init] - avoid using `let cl: Class = .init()`

### ISSUE THREAD

**Issue by jendaz** [realm/SwiftLint#2960]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

Please describe the rule idea, format
this issue's title as `Rule Request: [Rule Name]` and describe:

Improve rule `explicit_init` to force user to use `let cl = Class()` instead of `let cl: Class = .init()`

1. Why should this rule be added? Share links to existing discussion about what
   the community thinks about this.

> Code is more readable when you initialize with class name instead of .init() only

2. Provide several examples of what _would_ and _wouldn't_ trigger violations.

> NO:
```
let view: UIView = .init(frame: .init(origin: .init(x: 0, y: 0), size: .init(width: 50, height: 50)))
```
> YES:
```
let view = UIView(frame: CGRect(origin: CGPoint(x: 0, y: 0), size: CGSize(width: 50, height: 50)))
```

3. Should the rule be configurable, if so what parameters should be configurable?

> I guess no.

4. Should the rule be opt-in or enabled by default? Why?
   See [README.md](../README.md#opt-in-rules) for guidelines on when to mark a rule as opt-in.

> I guess it should be enabled by default.

**Comment by jendaz** [comment]
I've created a simple custom rule for that:
```
init_with_class_name:
        name: "Init With Class Name"
        regex: "(=\\s*\\.init\\()"
        message: "There should be init function with class or structure name. EG: let cl = Class() instead of let cl: Class = .init()"
        severity: warning
```
