### ISSUE TITLE
Included and Excluded Rule in Swift YAML

### ISSUE THREAD

**Issue by sachinvas** [realm/SwiftLint#3109]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

My Project Setup is as below:
1. Have many different in-house Pods which are private
2. Using the git branches in Podfile to resolve those Pods
3. I am also using many other third party Pods.

The issue which we are facing is about the Included and Excluded rule. As per the SwiftLint, the excluded rule takes precedence over the included rule. 

I have to add the Pods folder to the excluded rule as I don't want to run for the third party libraries. However, I want to include all my in-house Pods. 

Because the excluded rule takes precedence over the included rule, all my in-house Pods are getting excluded.

### Environment

* SwiftLint version - 0.39.1
* Installation method used - CocoaPods
* Paste your configuration file:

```yml
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - UnitTests
  - Pods/
included:
  - IN_HOUSE_APP
  - Pods/IN_HOUSE_POD_1
  - Pods/IN_HOUSE_POD_2
  - Pods/IN_HOUSE_POD_3
  - Pods/IN_HOUSE_POD_4
  - Pods/IN_HOUSE_POD_5
  - Pods/IN_HOUSE_POD_6
  - Pods/IN_HOUSE_POD_7
  - Pods/IN_HOUSE_POD_8
  - Pods/IN_HOUSE_POD_9
  - Pods/IN_HOUSE_POD_10
disabled_rules:
  - line_length
  - function_body_length
  - type_body_length
  - identifier_name
opt_in_rules:
  - closure_spacing
  - closure_end_indentation
  - closure_body_length
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_is_empty
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - fallthrough
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - multiline_function_chains
  - no_extension_access_modifier
  - operator_usage_whitespace
  - private_action
  - private_outlet
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_type_annotation
  - sorted_first_last
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_declaration
  - unused_import
  - vertical_whitespace_opening_braces
  - discouraged_optional_collection
  - enum_case_associated_values_counts
  - file_types_order
  - legacy_multiple
  - legacy_random
  - indentation_width
force_cast: error          # [NG] as
force_unwrapping: error    # [NG] value!
indentation: 2
file_length:
  - 2500
  - 3000
```

* Are you using Nested Configuration? - NO
* Which Xcode version are you using? - Xcode 11.3.1
* Do you have a sample that shows the issue? NO
