### ISSUE TITLE
type_contents_order rule custom order does not work

### ISSUE THREAD

**Issue by jessesquires** [realm/SwiftLint#3128]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Defining a custom order for `type_contents_order` does not work.

https://realm.github.io/SwiftLint/type_contents_order.html

Rule was introduced in #2296

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
Loading configuration from '.swiftlint.yml'
Linting Swift files at paths 
...
Done linting! Found 0 violations, 0 serious in 10 files.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 
**`0.39.1`**

* Installation method used (Homebrew, CocoaPods, building from source, etc)?
**Homebrew**

* Paste your configuration file:

```yml
opt_in_rules:
  - type_contents_order:
      order:
        - case
        - type_alias
        - associated_type
        - subtype
        - type_property
        - instance_property
        - ib_outlet
        - ib_inspectable
        - initializer
        - deinitializer
        - subscript
        - type_method
        - view_life_cycle_method
        - ib_action
        - other_method
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? 
**No**

* Which Xcode version are you using (check `xcodebuild -version`)?

```
Xcode 11.3.1
Build version 11C504
```

* Do you have a sample that shows the issue?  **Yes**

```swift
// Does not trigger any violations:

public class Testing {

    init() { }

    var x: Int = 0

    typealias Test = Void
}
```
