### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by Pratik-Sodha** [realm/SwiftLint#3134]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
Abort trap: 6           mint run swiftlint swiftlint --path ${TARGET_PATH} --config ${SRCROOT}/.swiftlint.yml
Command PhaseScriptExecution failed with a nonzero exit code
```

### Environment

* `realm/SwiftLint@0.39.1`
* Homebrew, MIntfile,Carthage_ 
* Configuration file:

```yml
targetTemplates:
  Application:
    type: application
    platform: iOS
    scheme:
      gatherCoverageData: true

  Framework:
    type: framework
    platform: iOS
    scheme:
      gatherCoverageData: true
    prebuildScripts: &prebuildScripts
      - script: |
          mint run swiftformat swiftformat ${TARGET_PATH}
        name: SwiftFormat
      - script: |
          mint run swiftlint swiftlint --path ${TARGET_PATH} --config ${SRCROOT}/.swiftlint.yml
        name: SwiftLint
    dependencies:
      - carthage: RxAtomic
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxOptional

  Tests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: Main
      - carthage: RxTest
      - carthage: RxBlocking
    settings:
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Main.app/Main"

  Extension:
    type: app-extension
    platform: iOS
    prebuildScripts: *prebuildScripts
```

* Version 11.3.1 (11C505)
