### ISSUE TITLE
Redundant type annotation rule ignores nested types

### ISSUE THREAD

**Issue by iby** [realm/SwiftLint#3146]
### New Issue Checklist

- [x ] Updated SwiftLint to the latest version
- [ x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Redundant type annotation ignores nested types, for example, the following static property doesn't get picked up, while others are:

```swift
fileprivate static let version: AnnouncementStore.Attribute = AnnouncementStore.Attribute("Version")
```

### Environment

* SwiftLint version: 0.39.1
* Installation method used: Homebrew
* Paste your configuration file:

```yml
# https://realm.github.io/SwiftLint/rule-directory.html
# https://github.com/realm/SwiftLint#configuration
# swiftlint rules

included: source

disabled_rules:
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - duplicate_imports
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - nesting
  - opening_brace
  - private_over_fileprivate
  - redundant_discardable_let
  - type_body_length
  - type_name
  - unused_closure_parameter
  - unused_setter_value # https://github.com/realm/SwiftLint/issues/2585
  - weak_delegate

opt_in_rules:
  redundant_type_annotation

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  ignores_comments: false

vertical_whitespace:
  max_empty_lines: 2

switch_case_alignment:
  indented_cases: true
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations): No
* Which Xcode version are you using: Xcode 11.3, Build version 11C29
* Do you have a sample that shows the issue: See above.
