### ISSUE TITLE
False positive `implicit_getter` violation when mentioning word "set" in a comment in custom getter of a read-write var

### ISSUE THREAD

**Issue by yas375** [realm/SwiftLint#3149]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Mentioning word "set" (without parentheses) in a **comment** in a `get` of a read-write var with both get and set defined triggers SwiftLint to think that this is a read-only property.

<img width="819" alt="image" src="https://user-images.githubusercontent.com/217368/77595323-1560f380-6eb6-11ea-838f-a6277fb23a6f.png">

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint --path Test.swift --no-cache --enable-all-rules
Loading configuration from '.swiftlint.yml'
Linting Swift files at paths Test.swift
Linting 'Test.swift' (1/1)
/Users/yas/code/caremobile/Test.swift:3:9: warning: Implicit Getter Violation: Computed read-only properties should avoid using the get keyword. (implicit_getter)
Done linting! Found 1 violation, 0 serious in 1 file.
```

### Environment

* SwiftLint 0.39.1
* Installation method used: Homebrew
* Paste your configuration file:

```yml
excluded:
  - Pods

opt_in_rules:
  - array_init
  - contains_over_first_not_nil
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_collection_literal
  - overridden_super_call
  - sorted_first_last
  - yoda_condition

disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - multiple_closures_with_trailing_closure
  - nesting # consider
  - notification_center_detachment
  - operator_whitespace
  - todo # fix
  - type_body_length
  - type_name # consider
  - weak_delegate # fix

statement_position:
  statement_mode: uncuddled_else
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?No

* Which Xcode version are you using (check `xcodebuild -version`)?
Xcode 11.4
Build version 11E146

* Do you have a sample that shows the issue? 
Yes:

**Test.swift**
```swift
extension Test {
    var foo: Bool {
        get {
            bar?.boolValue ?? true // Comment mentioning word set which triggers violation
        }
        set {
            bar = NSNumber(value: newValue as Bool)
        }
    }
}
```

If I don't mention word "set" in the comment then it seem to work fine.
I don't recall seeing this issues prior to updating to Xcode 11.4.

Hope it helps.
