### ISSUE TITLE
`let_var_whitespace ` cannot be fixed

### ISSUE THREAD

**Issue by tlb-xiongju** [realm/SwiftLint#3166]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I am applying both `implicit_return` and `let_var_whitespace` to my project.
I got a code block like as following:

```swift
extension WalletState: Reducible {
    public static var reducer: (Action, WalletState?) -> WalletState { { action, state in
        var nextState = state ?? .init()
        
        switch action {
        default:
            break
        }
        
        return nextState
        }
    }
}
```
and Swiftlint keeps showing `let_var_whitespace` warning, but when I add a whitespace line upon `var nextState = state ?? .init()` and build the project, Swiftlint auto fix the code back to what it looks like above.
I also tried write the code like this:

```swift
extension WalletState: Reducible {
    public static var reducer: (Action, WalletState?) -> WalletState {
        return { action, state in

            var nextState = state ?? .init()
        
            switch action {
            default:
                break
            }
        
            return nextState
        }
    }
}
```
when I build the project, it got back.

what's wrong?

Thanks~

### Environment

* SwiftLint: 0.39.1
* Installation method: CocoaPods
* Paste your configuration file:

```yml
excluded:
  - Carthage
  - Pods
  - .bundle

disabled_rules:
  - force_cast
  - force_try
  - unused_closure_parameter
  - unused_optional_binding
  - unused_capture_list
  - valid_docs
  - superfluous_disable_command
  - todo
  - xctfail_message
  - conditional_returns_on_newline 
  - discouraged_object_literal
  - discouraged_optional_collection
  - empty_xctest_method
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - file_name
  - file_types_order
  - force_unwrapping
  - implicitly_unwrapped_optional
  - no_grouping_extension
  - prefixed_toplevel_constant
  - required_enum_case
  - switch_case_on_newline
  - trailing_closure 
  - strict_fileprivate
  - prohibited_interface_builder
  - multiline_arguments_brackets
  - multiline_parameters_brackets
  - missing_docs
  - nslocalizedstring_key
  - object_literal
  - required_deinit
  - strong_iboutlet
  - vertical_whitespace_between_cases
  - xct_specific_matcher
  - type_contents_order
  - unowned_variable_capture
  - indentation_width

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_grouping_extension
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_deinit
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

trailing_whitespace:
  ignores_empty_lines: true 
  ignores_comments: true

type_name:
  min_length:
    warning: 2
  max_length:
    warning: 45
    error: 60
  excluded:
    - X # coordinator
    - Y # coordinator

variable_name:
  min_length:
    warning: 2
  max_length:
    warning: 30
    error: 45
  excluded:
    - a # sort
    - b # sort
    - i # loop1
    - j # loop2
    - k # loop3
    - x # coordinator
    - y # coordinator
    - z # coordinator (3d)
    - d # delta
    - t # time
    - _ # ignore

cyclomatic_complexity:
  warning: 10
  error: 15
  ignores_case_statements: true 

file_length:
  warning: 500
  error: 800

type_body_length:
  warning: 500

function_body_length:
  warning: 50

large_tuple:
  warning: 4

custom_rules:
  custom_todo:
    included: ".*\\.swift"
    name: "Todo"
    regex: "\\b(?:TODO)(?::|\\b)"
    match_kinds:
      - comment
    message: "TODOs should be resolved."
    severity: warning
```
