### ISSUE TITLE
`discarded_notification_center_observer` sometimes conflicts with `implicit_return`

### ISSUE THREAD

**Issue by hstdt** [realm/SwiftLint#3170]
### New Issue Checklist

- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)
- [x] Updated SwiftLint to the latest version

### Describe the bug

Once I fixed the warning `implicit_return`, another warning `discarded_notification_center_observer` appeared.

![image](https://user-images.githubusercontent.com/10215098/78416614-8e054400-765c-11ea-870b-d5a44c9ecc7b.png)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?  **0.39.1**
* Installation method used (Homebrew, CocoaPods, building from source, etc)? **Homebrew**
* Paste your configuration file:

```yml
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - cyclomatic_complexity
  - nesting
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - force_cast
  - shorthand_operator
  - unused_closure_parameter
  - todo
opt_in_rules:
    - array_init
    - closing_brace
    - closure_end_indentation
    - closure_spacing
    - closure_parameter_position
    - discouraged_object_literal
    - empty_count
    - empty_string
    - explicit_init
    - implicit_return
    - let_var_whitespace
    - literal_expression_end_indentation
    - operator_usage_whitespace
    - overridden_super_call
    - private_action
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - redundant_nil_coalescing
    - required_enum_case
    - trailing_semicolon
    - single_test_class
    - sorted_first_last
    - statement_position
    - file_length
    - switch_case_on_newline
    - vertical_parameter_alignment_on_call
    - yoda_condition
    - cyclomatic_complexity
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? **NO**
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)? **Xcode 11.4**
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
extension NSManagedObjectContext {

    /// Adds the given block to the default `NSNotificationCenter`'s dispatch table for the given context's objects-did-change notifications.
    /// - returns: An opaque object to act as the observer. This must be sent to the default `NSNotificationCenter`'s `removeObserver()`.
    func addObjectsDidChangeNotificationObserver(_ handler: @escaping (ObjectsDidChangeNotification) -> Void) -> NSObjectProtocol {
        return NotificationCenter.default.addObserver(forName: NSNotification.Name.NSManagedObjectContextObjectsDidChange, object: self, queue: nil) { note in
            let wrappedNote = ObjectsDidChangeNotification(note: note)
            handler(wrappedNote)
        }
    }

    func addObjectsDidChangeNotificationObserver1(_ handler: @escaping (ObjectsDidChangeNotification) -> Void) -> NSObjectProtocol {
        NotificationCenter.default.addObserver(forName: NSNotification.Name.NSManagedObjectContextObjectsDidChange, object: self, queue: nil) { note in
            let wrappedNote = ObjectsDidChangeNotification(note: note)
            handler(wrappedNote)
        }
    }

}
```
