### ISSUE TITLE
explicit_acl not working in extension

### ISSUE THREAD

**Issue by makleso6** [realm/SwiftLint#3186]
### New Issue Checklist

- [*] Updated SwiftLint to the latest version
- [*] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

**explicit_acl** not working in extension
<img width="1293" alt="Снимок экрана 2020-04-24 в 12 29 11" src="https://user-images.githubusercontent.com/9068221/80197382-3a689380-8627-11ea-8559-7dfd3f8a6b9b.png">
(MacOS 10.15.4, Xcode 11.4, swiftlint  0.39.2)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.39.2
* Installation method used (Homebrew, CocoaPods, building from source, etc)? - CocoaPods
* Paste your configuration file:

```yml
excluded:
  - Pods
  - Library
  - Core
  - scripts

custom_rules:
  one_linefeed:
    regex: "(?<=\n)(([ \t]*\n)|(\n)){2,}"
    message: "Only one linefeed available."
    name: "One linefeed."

  disable_print:
    included: ".*\\.swift"
    name: "print verboten"
    regex: "((\\bprint)|(Swift\\.print))\\s*\\("
    message: "Prefer Log over print"
    severity: error
  
  disable_nslog:
    included: ".*\\.swift"
    name: "NSLog verboten"
    regex: "((\\bNSLog))\\s*\\("
    message: "Prefer Log over NSLog"
    severity: error

whitelist_rules:
  - class_delegate_protocol
  - closing_brace
  - colon
  - comma
  - compiler_protocol_init
  - control_statement
  - discouraged_direct_init
  - dynamic_inline
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - generic_type_name
  - implicit_getter
  - inert_defer
  - is_disjoint
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - mark
  - no_fallthrough_only
  - notification_center_detachment
  - opening_brace
  - operator_whitespace
  - private_over_fileprivate
  - protocol_property_accessors_order
  - redundant_set_access_control
  - redundant_void_return
  - redundant_string_enum_value
  - return_arrow_whitespace
  - shorthand_operator
  - statement_position
  - switch_case_alignment
  - syntactic_sugar
  - trailing_comma
  - trailing_semicolon
  - unneeded_break_in_switch
  - unused_enumerated
  - weak_delegate
  - xctfail_message
  - custom_rules

  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - identical_operands
  - sorted_first_last
  - switch_case_on_newline
  - toggle_bool
  - untyped_error_in_catch
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - yoda_condition

  - literal_expression_end_indentation
  - explicit_top_level_acl
  - explicit_acl

```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  -

* Which Xcode version are you using (check `xcodebuild -version`)?
Xcode 11.4
Build version 11E146

* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
extension AppDelegate: UIApplicationDelegate {
// should trigger
        func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
        return true
    }
}
```
