### ISSUE TITLE
Add support for Homebrew on Linux

### ISSUE THREAD

**Issue by Jeehut** [realm/SwiftLint#3204]
I just tried to use SwiftLint in a GitHub action running on Ubuntu (which is 10x cheaper than macOS) and for this I tried to use Homebrew (yes, it actually _is_ available on Linux nowadays, see https://docs.brew.sh/Homebrew-on-Linux !). But I ran into this error:

```bash
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
Error: undefined method `installed?' for OS::Mac::Xcode:Module
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:18:in `xcode_installed_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:10:in `block in <class:XcodeRequirement>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:60:in `instance_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:60:in `block in satisfied?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:191:in `yielder'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:60:in `satisfied?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:456:in `block in expand_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:222:in `block in prune?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:220:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:220:in `prune?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:210:in `block (2 levels) in expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in `each_key'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:209:in `block in expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:208:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:208:in `expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1570:in `recursive_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:450:in `expand_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:388:in `compute_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:148:in `verify_deps_exist'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:141:in `prelude'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:328:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:261:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:259:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:259:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
##[error]Process completed with exit code 1.
```

From what it looks like, the Homebrew formula expects Xcode to be installed and also macOS from being the operating system. While I can understand that that's the use case for most of the people, I think there's no reason really holding off from also supporting Linux in the Homebrew formula as Linux support is already there. We could make installation so much easier with Homebrew support.

Here's the GitHubt Actions job I tried to run (helps reproducing the issue):

```yaml
  swiftlint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Install SwiftLint
      run: brew install swiftlint
    - name: Run SwiftLint
      run: swiftlint --strict
```

When I change `ubuntu-latest` to `macos-latest` everything works fine, but having Linux support would save a lot of 💰. 😉

**Comment by Cyberbeni** [comment]
You don't need to use homebrew, I have a GitHub Action for this that caches the build, so you don't have to rebuild it every time. (Saving you more $)

```
name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install SwiftLint
      uses: Cyberbeni/install-swift-tool@v2
      with:
        url: https://github.com/realm/SwiftLint
        version: '*' # This will resolve to the highest version number tag
    - name: Lint
      run: swiftlint
```
