### ISSUE TITLE
prefer_zero_over_explicit_init with autocorrect breaks code

### ISSUE THREAD

**Issue by schjonhaug** [realm/SwiftLint#3318]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The use of `prefer_zero_over_explicit_init` breaks code in some cases.

### Environment

* Configuration file:

```yml
disabled_rules:
  - line_length
  - redundant_type_annotation
  - file_types_order
  - type_contents_order
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - explicit_self
  - fatal_error_message
  - file_name
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_grouping_extension
  - nslocalizedstring_key
  - number_separator
  - discouraged_object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - toggle_bool
  - trailing_comma
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
deployment_target:
  iOS_deployment_target: 10.0
trailing_comma:
  mandatory_comma: true
number_separator:
  minimum_length: 5
excluded:
  - Challenge/Frameworks

```

Example file:

```
import Foundation

func test() {
    let path = CGMutablePath()
    path.move(to: CGPoint(x: 0, y: 0))
    path.addLine(to: CGPoint(x: 2, y: 2))
}
```

turns into

```
import Foundation

func test() {
    let path = CGMutablePath()
    path.move(to: CGPoint.zero
    path.addLine(to: CGPoint(x: 2, y: 2))
}

```

when running `swiftlint autocorrect`

Something similar is happening when running it on `super.init(frame: CGRect(x: 0, y: 0, width: 0, height: 0))`. I then get `super.init(frame: CGRect.zero`.
