### ISSUE TITLE
Severity settings for the indentation_width rule doesn't have any effect

### ISSUE THREAD

**Issue by okycelt** [realm/SwiftLint#3346]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Severity settings for the `indentation_width` rule doesn't have any effect. Even after settings `severity` to `error` in `.swiftlint.yml`, all `indentation_width` violations are still shown as warnings. Setting `severity` to `error` for a few other random rules works as expected.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ mint run swiftlint lint
```

### Environment

* SwiftLint version: 0.40.2
* Installation method used: Mint (also tried Homebrew)
* Paste your configuration file:

```yml
disabled_rules:
  - line_length
  - todo

opt_in_rules:
  - anyobject_protocol
  - closure_end_indentation
  - explicit_init
  - indentation_width
  - multiline_arguments
  - multiline_parameters
  - multiline_parameters_brackets
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

indentation_width:
  severity: error
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?: No
* Which Xcode version are you using (check `xcodebuild -version`)?: 11.7 (11E801a)
