### ISSUE TITLE
Show Lint message in the wrong place

### ISSUE THREAD

**Issue by saeid-pm** [realm/SwiftLint#3395]
### New Issue Checklist

:white_check_mark: Updated SwiftLint to the latest version
:white_check_mark: I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### The bug

Everything was fine before I added `severity` to my custom rule but after adding `severity: error` the location of **Lint** message changed, then I  remove `severity` and also removed **SwiftLint**  from `pods` and reinstall it, but nothing happened!

**Issues**:

1. Show message at the top of screen(file)
<img width="1010" alt="Screen Shot 2020-10-27 at 9 22 13 PM" src="https://user-images.githubusercontent.com/6316912/97341661-99d78280-189a-11eb-9b53-a201839d28b5.png">

2. Don't show message when there are no Comments line in File.swift (`import ...` is first line of the file)

### Environment

* SwiftLint version: 0.40.3
* Installation method used: CocoaPods
* `.swiftlint.yml` file:

```yml
disabled_rules:
  - colon
  - comma
  - control_statement

custom_rules:
  ui_text_field:
    regex: "^(?!.*(?:txf)).* = UITextField().*"
    message: "UITextField() must start with 'txf'"
    #severity: error
```
* Xcode version: 12

**Comment by PaulTaykalo** [comment]
Custom rules with regexes has ".dotMatchesAllSymbols"

so ".*" will capture everything from the start of the file, so technically it is not wrong
```
custom_rules:
  ui_text_field:
    regex: "(?![^\n]*(?:txf))[^\n]* = UITextField()[^\n]*"
    message: "UITextField() must start with 'txf'"
```
