### ISSUE TITLE
Xcode ignoring swiftlint.yml in 0.41.0

### ISSUE THREAD

**Issue by Odrakir** [realm/SwiftLint#3428]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

After updating to 0.41 Xcode seems to be ignoring the configuration in `.swiftlint.yml`. This used to work fine in 0.40.1 and it still works in the command line.

### Environment

* SwiftLint version: 0.41.0
* Installation method used: homebrew
* Paste your configuration file:

```yml
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Templates

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
line_length:
  warning: 150
  error: 250
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

identifier_name:
  excluded: # excluded via string array
    - id
    - db
    - at
    - to

type_name:
  excluded: # excluded via string array
    - ID

custom_rules:
  no_ui_colors:
    excluded: ".*Colors.swift|.*ColorsTests.swift|.*UIColor+Extensions.swift"
    name: "Don't use Standard UIColors"
    regex: '[.]\b(systemBlue|systemGreen|systemIndigo|systemOrange|systemPink|systemPurple|systemRed|systemTeal|systemYellow|systemGray|systemGray2|systemGray3|systemGray4|systemGray5|systemGray6|black|blue|brown|cyan|darkGray|gray|green|lightGray|magenta|orange|purple|red|white|yellow)\b'
    message: "Only use the colors from the Design System"
    severity: warning

  no_color_initializers:
    excluded: ".*Colors.swift|.*ColorsTests.swift|.*UIColor+Extensions.swift"
    name: "Don't use standard color initializers"
    regex: 'UIColor\((?!hex|patternImage|hue)'
    message: "Only use the colors from the Design System using the Color initializer"
    severity: warning
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No
* Which Xcode version are you using (check `xcodebuild -version`)? 12.2 (beta 2)
* Do you have a sample that shows the issue? Not right now, I can try to build one if necessary
