### ISSUE TITLE
Custom regex rule not matching valid lines

### ISSUE THREAD

**Issue by cohilla** [realm/SwiftLint#3435]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I have a `custom-rule` which uses regex to define error messages, and the linter is not matching lines which do contain the pattern of the provided string. The regex is tested on multiple testers.

The rule is designed to catch anyone inheriting from *<StateMachineTaskHandler>*. 

##### Complete output when running SwiftLint, including the stack trace and command used

**omitted**

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.41.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)? source
* Paste your configuration file:

```yml
custom_rules:
  dependency_statemachine_task_handler_error: # rule identifier
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    excluded: "(.*Test.*)" # regex that defines paths to exclude during linting. optional
    name: "Dependency" # rule name. optional.
    regex: '^(public|private|internal|)*( )*(class|extension|protocol)[ a-zA-Z]*(:)[ a-zA-Z]*(StateMachineTaskHandler).*\{' # matching pattern
    capture_group: 0 # number of regex capture group to highlight the rule violation at. optional.
    message: "Not allowed." # violation message. optional.
    severity: error # violation severity. optional.
 
only_rules:
  -  custom_rules
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? no
* Which Xcode version are you using (check `xcodebuild -version`)? 12.0
* Do you have a sample that shows the issue? See below

```swift
// This does not trigger a violation (there are several others):
protocol GuidanceImageTaskHandlerInteractable: CodableStateMachineTaskHandlerInteractor<GuidanceImageTaskHandlerInput, GuidanceImageAction>, GuidanceImageDelegate {
```
