### ISSUE TITLE
SwiftLint leaks memory

### ISSUE THREAD

**Issue by MaxDesiatov** [realm/SwiftLint#3461]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

For some reason my `swiftlint` processes leak memory.

<img width="589" alt="Screenshot 2020-12-09 at 21 34 29" src="https://user-images.githubusercontent.com/112310/101691435-96711280-3a66-11eb-86e9-fac4244fabca.png">

##### Complete output when running SwiftLint, including the stack trace and command used

N/A, I'm using SwiftLint via [the VSCode extension](https://github.com/vknabel/vscode-swiftlint).

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.41.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
Homebrew
* Paste your configuration file:

```yml
disabled_rules:
  - trailing_comma
  - identifier_name
  - void_return
  - operator_whitespace
  - nesting
  - cyclomatic_complexity

line_length:
  - 100
  - 140

function_body_length:
  - 50

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
  - Example/Pods
  - Tests/CoreXLSXTests/XCTestManifests.swift
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
No
* Which Xcode version are you using (check `xcodebuild -version`)?
Xcode 12.2
Build version 12B45b
* Do you have a sample that shows the issue?
N/A, this happened with multiple different projects for me, but I'm not sure what exact code snippet triggers it.
