### ISSUE TITLE
Throwing unnecessary empty_count

### ISSUE THREAD

**Issue by lalkrishna** [realm/SwiftLint#3488]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I'm getting Empty Count Violation: 

> Prefer checking `isEmpty` over comparing `count` to zero. (empty_count)

for the below code.

```swift
guard let count = notify.object as? Int else { fatalError() }
if count == 0 {
}
```

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

```yml
#  SwiftLint Rules Configuration
#  https://github.com/realm/SwiftLint
#
# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
#  - colon
#  - comma
#  - control_statement
  - trailing_whitespace
  - unused_optional_binding
  - multiple_closures_with_trailing_closure
  - unused_capture_list
  
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # Find all the available rules by running: `swiftlint rules`

line_length: 200
function_body_length: 60

#type_body_length:
#  - 300 # warning
#  - 400 # error
## or they can set both explicitly
#file_length:
#  warning: 500
#  error: 1200

nesting:
   type_level: 3
identifier_name:
#  min_length: # only min_length
#    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - km
cyclomatic_complexity:
  ignores_case_statements: true
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 60

```
