### ISSUE TITLE
Custom rule for suggesting using comma instead of AND operator '&&' in control flow statements reports failure on incorrect line

### ISSUE THREAD

**Issue by deanharel** [realm/SwiftLint#3510]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Created a **custom rule** to catch instances of using the AND operator '&&' instead of a _comma_ in control flow statements.
Tested it on [Rubular](https://rubular.com/r/jVrrlXZSSIy0OP), verifying the regex behaves as expected. It does.
However, when I run SwiftLint the warning appeared on the **incorrect line**.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

Output:
```
Linting Swift files in current working directory
Linting 'TestFile.swift' (1/1)
/Users/deanharel/Developer/ios/SwiftLintPreferCommaCustomRuleTest/SwiftLintPreferCommaCustomRuleTest/TestFile.swift:8:9: warning: Prefer Comma Over And Operator in Control Flow Statements Violation: Control flow statement contains &&. Use comma instead. (prefer_comma_over_and_operator)
Done linting! Found 1 violation, 0 serious in 1 file.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? **0.42.0**
* Installation method used (Homebrew, CocoaPods, building from source, etc)? **Mint**
* Paste your configuration file:

```yml
# SwiftLint Configuration File
# Github: https://github.com/realm/SwiftLint
# Rule Directory: https://realm.github.io/SwiftLint/rule-directory.html


reporter: "xcode"

disabled_rules:
  - line_length
  - trailing_whitespace
  - todo


custom_rules:
  prefer_comma_over_and_operator:
    name: "Prefer Comma Over And Operator in Control Flow Statements"
    regex: "(if|guard|while)[\n ].+ &&"
    message: "Control flow statement contains &&. Use comma instead."
    severity: warning
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents. **NO**
* Which Xcode version are you using (check `xcodebuild -version`)? **Xcode 12.2 (12B45b)**
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`. **Yes**

##### Content:

expected warning line: 21 (`if level <= 0.05 && state != .charging && level != -1 { // level != -1 for simulator`)
actual warning line: 8 (`guard let freeSpace = (systemAttributes[FileAttributeKey.systemFreeSize] as? NSNumber)?.int64Value else {`)

```swift
import UIKit

@main final class AppDelegate: UIResponder, UIApplicationDelegate {}

func availableDiskSpace() -> Int64? {
    do {
        let systemAttributes = try FileManager.default.attributesOfFileSystem(forPath: NSHomeDirectory() as String)
        guard let freeSpace = (systemAttributes[FileAttributeKey.systemFreeSize] as? NSNumber)?.int64Value else {
            return nil
        }
        return freeSpace
    } catch {
        return nil
    }
}

func isBatteryCharged() -> Bool {
    UIDevice.current.isBatteryMonitoringEnabled = true
    let level = UIDevice.current.batteryLevel
    let state = UIDevice.current.batteryState
    if level <= 0.05 && state != .charging && level != -1 { // level != -1 for simulator
        return false
    }
    
    UIDevice.current.isBatteryMonitoringEnabled = false
    return true
}
```

##### File:
[SwiftLint_TestFile.zip](https://github.com/realm/SwiftLint/files/5912406/SwiftLint_TestFile.zip)
