### ISSUE TITLE
Some ignored files are being analyzed.

### ISSUE THREAD

**Issue by guidomb** [realm/SwiftLint#352]
I have the following `.swiftlint.yml` file and I am using version `0.5.5`

```yaml
disabled_rules: # rule identifiers to exclude from running
  - variable_name_max_length
  - trailing_whitespace
  - variable_name_min_length
  - variable_name
  - force_cast
  - type_body_length
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
line_length: 200
function_body_length: 30
```

For some reason one of the libraries included with Carthage, Cartography, is being analyzed by `swiftlint`. It only happens with this library in my local machine. If I clone the repo in another machine everything works fine.

Something to take into account is that I first tried swiftlint in my project when the exclude feature wasn't available. Maybe there is something that got corrupted when I updated to the latest version.

How is the proper way to fully uninstall swiftlint.
