### ISSUE TITLE
`identical_operands` triggered by `"\(lhs)" == "\(rhs)"`

### ISSUE THREAD

**Issue by AndreiArdelean1** [realm/SwiftLint#3524]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

`identical_operands` triggered by `"\(lhs)" == "\(rhs)"`

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.42.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
CocoaPods
* Paste your configuration file:

```yml
disabled_rules: # rule identifiers to exclude from running
    - line_length
    - force_cast # to be removed
    - force_unwrapping # to be removed
    - implicit_return # prefer $0 over return
    - file_length # to be removed for refactoring
    - type_body_length # to be removed for refactoring
    - unused_closure_parameter
    - trailing_whitespace
    - redundant_optional_initialization
    - function_body_length
    - function_parameter_count
    - shorthand_operator
    - trailing_comma
    - no_fallthrough_only
    - redundant_string_enum_value
    - deployment_target
    - large_tuple
    - cyclomatic_complexity
    - private_action
    - private_outlet
    - identifier_name
    - todo
    - type_contents_order
    
opt_in_rules: # some rules are only opt-in
    - weak_delegate
    - unavailable_function
    - nesting
    - operator_whitespace
    - closure_spacing
    - first_where
    - discouraged_direct_init
    - contains_over_first_not_nil
    - explicit_init
    - operator_usage_whitespace
    - overridden_super_call
    - prefixed_toplevel_constant
    - private_over_fileprivate
    - prohibited_super_call
    - redundant_nil_coalescing
    - yoda_condition
    - unused_enumerated
    - unused_optional_binding
    - empty_count
    - type_name
    - unused_import
    - comment_spacing
    - unused_declaration
    - computed_accessors_order
    - prefer_zero_over_explicit_init
    - prefer_self_type_over_type_of_self
    - expiring_todo
    - contains_over_range_nil_comparison
    - toggle_bool
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - empty_collection_literal
    - reduce_boolean
    - unused_capture_list
    - redundant_objc_attribute
    - identical_operands
    - last_where
    - unused_control_flow_label
    - vertical_whitespace_opening_braces
    - vertical_whitespace_closing_braces
    - vertical_whitespace_between_cases
#    - multiline_literal_brackets
    - legacy_random
    - inert_defer
    - collection_alignment
    - literal_expression_end_indentation

# Find all the available rules by running:
# swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
    - Project
    - Analytics
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
    - explicit_self

identifier_name:
    excluded:
        - id
        - URL
        - lhs
        - rhs
        - i
        - j
        - k
        - x
        - x0
        - x1
        - x2
        - y
        - y0
        - y1
        - y2
        - dx
        - dy
        - up
        - to
        - pg
    allowed_symbols: "_"

type_name:
    min_length: 3 # only warning
    max_length: # warning and error
        warning: 55
        error: 65

#cyclomatic_complexity:
#    ignores_case_statements: true

#file_length:
#    ignore_comment_only_lines: true

empty_count:
    severity: warning # explicitly

#shorthand_operator:
#    severity: warning # explicitly

nesting:
    type_level: 3
    function_level: 2
    always_allow_one_type_in_functions: true
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)?
 Xcode 12.4
 Build version 12D4e
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a violation:
extension StaticString: Equatable {
    public static func == (lhs: StaticString, rhs: StaticString) -> Bool {
        return "\(lhs)" == "\(rhs)"
    }
}
```
