### ISSUE TITLE
How to skip the linter on my SPM depedencies ?

### ISSUE THREAD

**Issue by Lapinou42** [realm/SwiftLint#3541]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I have an iOS project with severals libraries installed with SPM. One of them is Alamofire and ObjectMapper.
When I run swiftlint, I got many errors from ObjectMapper and Alamofire librairies. 
The script in run when I build my iOS project using my custom build script (the same as in the wiki).
How can I exclude them ? 

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? **0.42.0**
* Installation method used (Homebrew, CocoaPods, building from source, etc)? **Homebrew**
* Paste your configuration file:

```yml
# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - nesting

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - R.generated.swift

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

identifier_name:
  excluded: # excluded via string array
    - id
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? **No.**
* Which Xcode version are you using (check `xcodebuild -version`)? **12.4**
* Do you have a sample that shows the issue? **No.**
