### ISSUE TITLE
explicit_type_interface collides with redundant_type_annotation for Bool

### ISSUE THREAD

**Issue by kubalani** [realm/SwiftLint#3578]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

This bug exist in version 0.43 and is introduced by #3438 

The above change re-introduced the bug #2312 for `Bool` as `allow_redundancy`  is no longer honored.
The error doesn't repro in version older than 0.43

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

`Redundant Type Annotation Violation: Variables should not have redundant type annotation (redundant_type_annotation)`

### Environment

SwiftLint installed via brew

```yml
whitelist_rules:
  - redundant_type_annotation

  - explicit_type_interface

explicit_type_interface: # requires type annotation on everything but local variables and constants
  excluded:
    - local
  allow_redundancy: true # Ignores rule if it would result in redundancy
swiftlint_version: 0.43.1

```

To test execute 
```bash
if which swiftlint >/dev/null; then
    swiftlint --config --strict .swiftlint.yml
else
    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```

Xcode version 12.4

Swift code that triggers the warning
```swift
    private var isFirstLaunch: Bool = true
```
