### ISSUE TITLE
Swiflint not scanning all files on 2 different machines

### ISSUE THREAD

**Issue by rgg-shobeika** [realm/SwiftLint#3589]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

In our team and on one of our macs, swiftlint is not scanning the new files added to a specific branch while on other macs it's doing it correctly. Both macs have the same version of Xcode, swiftlint as well as the configuration. The swiftlint configuration sits on our git repo next to the code.

##### Complete output when running SwiftLint, including the stack trace and command used
```
Output from Mac-1:
Done linting! Found 0 violations, 0 serious in 793 files.
```

```
Output from Mac-2:
Done linting! Found 3 violations, 0 serious in 803 files.
```

### Environment

* SwiftLint version: 0.41.0
* Installation method used Homebrew
* Paste your configuration file:

```yml
excluded:
  - fastlane
  - Pods
  - Templates

only_rules:
  ### autocorrect rules ###
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - implicit_return
  - inclusive_language
  - joined_default_parameter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - literal_expression_end_indentation
  - mark
  - nimble_operator
  - opening_brace
  - operator_usage_whitespace
  - private_over_fileprivate
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_void_return
  - return_arrow_whitespace
  - sorted_imports
  - statement_position
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - vertical_whitespace
  - void_return
  - class_delegate_protocol
  - closure_parameter_position
  - compiler_protocol_init
  - control_statement
  - discarded_notification_center_observer
  - discouraged_direct_init
  - dynamic_inline
  - generic_type_name
  - is_disjoint
  - redundant_set_access_control
  - redundant_string_enum_value
  - switch_case_alignment
  - syntactic_sugar
  - unneeded_break_in_switch
  - unused_enumerated
  - valid_ibinspectable
  - vertical_parameter_alignment
  - weak_delegate
  - yoda_condition
  - comment_spacing # enforces one space after slashes for comments
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? NO
* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 12.4 Build version 12D4e
