### ISSUE TITLE
expiring_todo severity is not configurable

### ISSUE THREAD

**Issue by cuddergambino** [realm/SwiftLint#3590]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The expiring todo configuration does not take into account severity changes. For example, adding the following to `.swiftlint` does nothing.
```
expiring_todo:
  warning: reached_or_passed_expiry_severity
```
This is the line in a `.swift` file:
```
 // TODO: [04/01/2021] test
```
The compiler displays an error when a warning should be displayed.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```
Output:
```
 error: ExpiringTodo Violation: TODO/FIXME has expired and must be resolved. (expiring_todo)
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.43.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

```yml
### Rules directory: https://realm.github.io/SwiftLint/rule-directory.html
opt_in_rules:
  - expiring_todo

disabled_rules:
  - todo
  - trailing_comma

expiring_todo:
  warning: reached_or_passed_expiry_severity
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 12.4 Build version 12D4e
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules` `echo "// TODO: [04/01/2021]" | swiftlint line --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a violation:
// TODO: [04/01/2021]
```
