### ISSUE TITLE
Colon violation in SwiftUI when there is none

### ISSUE THREAD

**Issue by tijs** [realm/SwiftLint#3601]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The following code triggers a colon violation even though there is none:

```
Image()
    .frame(width: 22, height: 22, alignment: .center)
```

<img width="1030" alt="Screenshot 2021-04-16 at 11 30 12" src="https://user-images.githubusercontent.com/3108/115004904-9b781f80-9ea7-11eb-8ed3-912da44f98f8.png">

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint Kilowatt/SettingsViews/SettingsRowView.swift 
Linting Swift files at paths Kilowatt/SettingsViews/SettingsRowView.swift
Linting 'SettingsRowView.swift' (1/1)
/Users/tijs/Documents/Projects/Kilowatt/Kilowatt/Kilowatt/SettingsViews/SettingsRowView.swift:20:60: warning: Colon Violation: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals. (colon)
Done linting! Found 1 violation, 0 serious in 1 file.
```

### Environment

* SwiftLint version 0.42.0-rc.2
* Installation method used: homebrew
* Paste your configuration file:

```yml
disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - identifier_name
opt_in_rules: # some rules are only opt-in
  - empty_count
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
reporter: "xcode"

cyclomatic_complexity:
  ignores_case_statements: true
```

* Which Xcode version are you using:

Xcode 12.4
Build version 12D4e
