### ISSUE TITLE
SwiftLint analayze won't start in BigSur M1

### ISSUE THREAD

**Issue by iDevPro** [realm/SwiftLint#3631]
### New Issue Checklist

- [0.43.1 ] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug
swift analayze --compiler-log-path ~/Desktop/output.txt --config .swiftlint.yml --path path
error: unable to invoke subcommand: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-analayze (No such file or directory)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
* Paste your configuration file:

```yml
cat .swiftlint.yml 
disabled_rules: # rule identifiers to exclude from running
opt_in_rules: 
included:
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

force_cast: warning
force_try: warning
identifier_name: warning

cyclomatic_complexity:
    ignores_case_statements: true
    warning: 10
    error: 50
  
identifier_name:
    excluded:
        - id
        - ip
        - ok

type_name:
    excluded:
        - T

type_body_length:
  - 400 # warning
  - 450 # error

file_length:
  warning: 500

nesting:
    type_level: 3

line_length: 210

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
No

* Which Xcode version are you using (check `xcodebuild -version`)?
Xcode 12.5
Build version 12E262

* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// This triggers a violation:
let foo = try! bar()
```
