### ISSUE TITLE
SwiftLint Analyze fails with "Error: Could not read compiler invocations"

### ISSUE THREAD

**Issue by VidaHasan** [realm/SwiftLint#3634]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Whenever I run swiftlint analyze, I get error of 'Error: Could not read compiler invocations"
##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint analyze
```
Error: Could not read compiler invocations

### Environment

Version: 0.43.1
Installation Method: Homebrew 
* homebrew
* Paste your configuration file:

```yml
disabled_rules: # rule identifiers to exclude from running
- colon
- comma
- control_statement
- nesting
- comment_spacing
- identifier_name # probably want to put this back in.
opt_in_rules: # some rules are only opt-in
- empty_count
# Find all the available rules by running:
# swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
-[../redacted]
excluded: # paths to ignore during linting. Takes precedence over `included`.

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
- explicit_self


# configure
line_length: 350
cyclomatic_complexity: 11
function_parameter_count: 10
large_tuple: 3
type_name:
    min_length: 3 # only warning
    max_length: # warning and error
        warning: 160    
        error: 200
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? **No**
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)? **12.5 12E262**
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

No, the issue is specific to analyze. Other linting works fine
