### ISSUE TITLE
Rule Request: trojan_source

### ISSUE THREAD

**Issue by macdrevx** [realm/SwiftLint#3751]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New rule request

Please describe the rule idea, format
this issue's title as `Rule Request: [Rule Name]` and describe:

1. Why should this rule be added? Share links to existing discussion about what
   the community thinks about this.

A recent publication has brought attention to "trojan source" attacks. See discussion and links at https://forums.swift.org/t/is-swift-vulnerable-to-trojan-source-attacks/53205/5

2. Provide several examples of what _would_ and _wouldn't_ trigger violations.

Only the characters relevant to the attack would trigger a violation.

3. Should the rule be configurable, if so what parameters should be configurable?

No

4. Should the rule be opt-in or enabled by default? Why?
   See [README.md](../README.md#opt-in-rules) for guidelines on when to mark a rule as opt-in.

Enabled by default. It guards against security vulnerabilities and developers who *do* want to use these unicode features should be explicit about their intent.

Implementation via custom rule for reference:

```
custom_rules:
  trojan_source:
    regex: "[\u202A\u202B\u202D\u202E\u2066\u2067\u2068\u202C\u2069]"
    severity: error
    message: "Source should not contain characters that may be used in reordering attacks. https://trojansource.codes/trojan-source.pdf"
```
