### ISSUE TITLE
Swiftlint --fix adding weak to a non protocol value 

### ISSUE THREAD

**Issue by ppamorim** [realm/SwiftLint#3805]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues) 

Similar to https://github.com/realm/SwiftLint/issues/3611 but https://github.com/realm/SwiftLint/pull/3599 won't fix.

### Describe the bug

For the given variable:

```swift
private var fooDelegate: Bool = false
```

When running:

```bash
$ swiftlint --fix
```

Swiftlint is transforming `var` to `weak var` probably because it has `delegate` on the name, this is causing the compilation to fail.

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.45.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

```yml
disabled_rules:
  - identifier_name
  - line_length
  - todo
  - cyclomatic_complexity
  - type_body_length
  - file_length
  - function_body_length
  - function_parameter_count
  - nesting
  - block_based_kvo
  
  - unused_closure_parameter
  - explicit_type_interface
  - large_tuple
  - inclusive_language

opt_in_rules: # some rules are only opt-in
  - explicit_type_interface
  - force_unwrapping
  - implicit_return
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_string
  - contains_over_first_not_nil
  # - empty_count //Disabled due Realm conflict
  # - first_where //Disabled due Realm conflict

excluded:
  - Carthage
  - Pods

force_cast: warning
force_try: warning
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No
* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 13.2.1
* Do you have a sample that shows the issue? Described above.
