### ISSUE TITLE
Custom rule is slow

### ISSUE THREAD

**Issue by GritGem** [realm/SwiftLint#3926]
### Describe the bug

When using custom rule in swiftlint it takes 34s to analyse the file (custom rule and content are below).
Using swiftlint lint --benchmark: 34,672: custom_rules

When the same regex is used online on the the same content https://regex101.com/ it took only 0.4ms to find the match.

Seems that comment section in file (any text in that part of code) causing the issue. Longer text is causing much longer processing time. 

Am I doing something wrong with regex? Or is it caused by swiftlint custom rule behaviour? Since regex as such seems to be working fine and fast I am not sure where should I fix my issue.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version 0.47.0
* Installation method used  - Homebrew
* Paste your configuration file:

```yml
custom_rules:
  # Wrong:
  # MyClassTest {
  #    //missing [My-Class] usage
  # }
  # Correct:
  # MyClassTest {
  #    let myClass = MyClass()
  # }
  test_class_name_match_class_under_test:
    message: "TestClass should use the name of class under test"
    included: ".*Test.\\.swift"
    regex: 'class ([a-zA-Z0-9]+)Test.{0,1}: XCTestCase(?:(?!\1)(:?\n|.))*func'
```

* no nested configurations
* Xcode Version 13.3 (13E113)

ExpenseMetadataManagerTests.swift:
```swift
class ExpenseMetadataManagerTests: XCTestCase {

    //anything to analyze by regex - this will make it unusable slow
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex
    //anything to analyze by regex

    private lazy var manager = ExpenseMetadataManager()

    func test() {}
}```
