### ISSUE TITLE
Can't use own orders in type_contents_order

### ISSUE THREAD

**Issue by MaksimBezdrobnoi** [realm/SwiftLint#3997]
### New Issue Checklist

- [* ] Updated SwiftLint to the latest version
- [ *] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

If I copy orders from documentation and try to use them, type_contents_order stopped to work

example
type_contents_order:
    order: [
        [SwiftLintFramework.TypeContent.case],
        [SwiftLintFramework.TypeContent.typeAlias, SwiftLintFramework.TypeContent.associatedType],
        [SwiftLintFramework.TypeContent.subtype],
        [SwiftLintFramework.TypeContent.typeProperty],
        [SwiftLintFramework.TypeContent.instanceProperty],
        [SwiftLintFramework.TypeContent.ibInspectable],
        [SwiftLintFramework.TypeContent.ibOutlet],
        [SwiftLintFramework.TypeContent.initializer],
        [SwiftLintFramework.TypeContent.typeMethod],
        [SwiftLintFramework.TypeContent.viewLifeCycleMethod],
        [SwiftLintFramework.TypeContent.ibAction],
        [SwiftLintFramework.TypeContent.otherMethod],
        [SwiftLintFramework.TypeContent.subscript],
        [SwiftLintFramework.TypeContent.deinitializer]
    ]

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?  0.47.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Home-brew
* Paste your configuration file:

```yml
excluded:
    - Tools/
    - App/Derived

disabled_rules:
    - cyclomatic_complexity
    - function_body_length
    - legacy_hashing
    - multiple_closures_with_trailing_closure
    - opening_brace
  
opt_in_rules:
    - anonymous_argument_in_multiline_closure
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters_brackets
    - switch_case_on_newline
    - test_case_accessibility
    - vertical_whitespace_closing_braces
    - weak_delegate
    - type_contents_order
  
multiline_arguments:
    only_enforce_after_first_closure_on_first_line: true

line_length: 100

type_contents_order:
    order: [
        [SwiftLintFramework.TypeContent.case],
        [SwiftLintFramework.TypeContent.typeAlias, SwiftLintFramework.TypeContent.associatedType],
        [SwiftLintFramework.TypeContent.subtype],
        [SwiftLintFramework.TypeContent.typeProperty],
        [SwiftLintFramework.TypeContent.instanceProperty],
        [SwiftLintFramework.TypeContent.ibInspectable],
        [SwiftLintFramework.TypeContent.ibOutlet],
        [SwiftLintFramework.TypeContent.initializer],
        [SwiftLintFramework.TypeContent.typeMethod],
        [SwiftLintFramework.TypeContent.viewLifeCycleMethod],
        [SwiftLintFramework.TypeContent.ibAction],
        [SwiftLintFramework.TypeContent.otherMethod],
        [SwiftLintFramework.TypeContent.subscript],
        [SwiftLintFramework.TypeContent.deinitializer]
    ]

identifier_name:
    min_length: 2
    max_length: 50
    allowed_symbols: [_]

type_name:
    max_length: 50
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)? 13E113
