### ISSUE TITLE
`// swiftlint:disable:next` does not work if there are doc comments

### ISSUE THREAD

**Issue by wdg** [realm/SwiftLint#4032]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

`// swiftlint:disable:next` does not disable as expected.

Expectation
```swift
// swiftlint:disable:next cyclomatic_complexity
/// Returns a `Color` for a specific `fileType`
/// If not specified otherwise this will return `Color.accentColor`
public static func iconColor(fileType: FileType) -> Color {
```
Reality: SwiftLint triggers warning about cyclomatic_complexity

This works (kinda, but triggers another warning) 
```swift
/// Returns a `Color` for a specific `fileType`
/// If not specified otherwise this will return `Color.accentColor`
// swiftlint:disable:next cyclomatic_complexity
public static func iconColor(fileType: FileType) -> Color {
```
Triggers warning: `Orphaned Doc Comment Violation: A doc comment should be attached to a declaration. (orphaned_doc_comment)`

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint --strict
... SNAP ...
/Users/wesley/Code/Apps/MacOS/*/*/*/*/src/UI/FileIcon.swift:47:5: error: Orphaned Doc Comment Violation: A doc comment should be attached to a declaration. (orphaned_doc_comment)
/Users/wesley/Code/Apps/MacOS/*/*/*/*/src/UI/FileIcon.swift:48:5: error: Orphaned Doc Comment Violation: A doc comment should be attached to a declaration. (orphaned_doc_comment)
/Users/wesley/Code/Apps/MacOS/*/*/*/*/src/UI/FileIcon.swift:99:5: error: Orphaned Doc Comment Violation: A doc comment should be attached to a declaration. (orphaned_doc_comment)
/Users/wesley/Code/Apps/MacOS/*/*/*/*/src/UI/FileIcon.swift:100:5: error: Orphaned Doc Comment Violation: A doc comment should be attached to a declaration. (orphaned_doc_comment)
Done linting! Found 17 violations, 17 serious in 302 files.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.47.1

* Installation method used (Homebrew, CocoaPods, building from source, etcetera)?
Homebrew

* Paste your configuration file:

```yml

# Disabled rule, reason.
disabled_rules:
  - todo # New project, we have a lot of // TODO:
  - missing_docs

# Exclude triggering type names.
type_name:
  excluded:
    - ID

# Exclude triggering identifier names.
identifier_name:
  excluded:
    - id
    - vc
    # (short) File extensions:
    - c
    - m
    - h
    - js
    - md
    - py
    - go
    - ts
    - txt
    - sh
    - pf
    - r
    - q
    - tp
    - xl
    - hy
    - d
    - cs

# Opt in rules, we want it more stricter.
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - missing_docs
  - modifier_order
  - convenience_type
  - pattern_matching_keywords
  - modifier_order
  - identical_operands
  - empty_count
  - empty_string

# Custom configuration for nesting, this needs to be removed at some point.
nesting:
  type_level:
    warning: 2 # warning if you nest 2 level deep instead of 1
    error: 3 # error if you nest 3 level deep instead of 1

# Prefer spaces over tabs.
custom_rules:
  spaces_over_tabs:
    included: ".*\\.swift"
    name: "Spaces over Tabs"
    regex: "\t"
    message: "Prefer spaces for indents over tabs. See Xcode setting: 'Text Editing' -> 'Indentation'"
    severity: warning

  at_attributes_newlining:
    name: "Significant attributes"
    message: "Significant @attributes should be on an extra line"
    included: ".*.swift"
    regex: '(@objc\([^\)]+\)|@nonobjc|@discardableResult|@propertyWrapper|@UIApplicationMain|@dynamicMemberLookup|@_cdecl\([^\)]+\))[^\n]'
    severity: error

  multiple_empty_lines:
    included: ".*.swift"
    name: "Multiple Empty Lines"
    regex: '((?:\s*\n){3,})'
    message: "There are too many line breaks"
    severity: error

  comma_space_rule:
    regex: ",[ ]{2,}"
    message: "Expected only one space after ',"
    severity: error

  # Disable usage of // swiftlint:disable (rulename)
  swiftlint_file_disabling:
    included: ".*.swift"
    name: "SwiftLint File Disabling"
    regex: "swiftlint:disable\\s"
    match_kinds: comment
    message: "Prefer swiftlint:disable:next or swiftlint:disable:this"
    severity: warning

  # Disable Xcode placeholders like <#Description#>
  no_placeholders:
    included: ".*.swift"
    name: "No Placeholders"
    regex: "\\<#([a-zA-Z]+)#\\>"
    match_kinds: comment
    message: "Please do not use Xcode's placeholders."
    severity: warning
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
Nope

* Which Xcode version are you using (check `xcodebuild -version`)?
Xcode 14.0
Build version 14A5270f

* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.
See examples

```swift
// This triggers a violation:
let foo = try! bar()
```
