### ISSUE TITLE
nimble_operator converts `to(beNil())` to `== nil` and expectations are failed

### ISSUE THREAD

**Issue by yuri-qualtie** [realm/SwiftLint#4059]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

SwiftLint's rule `nimble_operator` in version `0.48.0` replaces `.to(beNil())` to `== nil` and as result expectations are failed with message - `expected to equal <nil>, got <nil> (use beNil() to match nils)`.

For example following test is passed:
```
                    it("test nil") {
                        var type: Int?

                        expect(type).to(beNil())
                    }
```

However after `swiftlint --fix --format` code changed and test is no longer passed.

```
                    it("test nil") {
                        var type: Int?

                        expect(type) == nil //////  expected to equal <nil>, got <nil> (use beNil() to match nils)
                    }
```

### Environment

* SwiftLint version - 0.48.0
* Homebrew
* Paste your configuration file:

```yml
excluded:
  - Pods
line_length: 150
disabled_rules:
  - discouraged_optional_collection
  - force_cast
  - force_try
  - implicitly_unwrapped_optional
  - unowned_variable_capture
  - explicit_enum_raw_value
  - nesting
opt_in_rules:
  - array_init
  - number_separator
  - unused_import
  - sorted_imports
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - anyobject_protocol
  - convenience_type
  - empty_string
  - file_name
  - first_where
  - modifier_order
  - toggle_bool
  - unused_declaration
  - fallthrough
  - identical_operands
  - joined_default_parameter
  - closure_spacing
  - closure_body_length
  - closure_end_indentation
  - discouraged_optional_boolean
  - explicit_init
  - fatal_error_message
  - file_header
  - function_default_parameter_at_end
  - implicit_return
  - literal_expression_end_indentation
  - multiline_function_chains
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - prefixed_toplevel_constant
  - quick_discouraged_call
  - quick_discouraged_pending_test
  - quick_discouraged_focused_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - static_operator
  - strong_iboutlet
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
file_length:
  warning: 500
  error: 800
identifier_name:
  excluded:
    - id
    - i
    - j
    - OK
large_tuple:
  - 5
  - 5
reporter: "xcode"

```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  NO
* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 13.4 - Build version 13F17a
