### ISSUE TITLE
Setting 'warning' in SeverityLevelsConfig should unset 'error'

### ISSUE THREAD

**Issue by mgrebenets** [realm/SwiftLint#409]
I am getting false positive error messages from `swiftlint` version `0.6.0`.

Here's a picture that describes it the best.
![image](https://cloud.githubusercontent.com/assets/350654/12539263/a8e743da-c342-11e5-83f3-c7253453a3d2.png)

`.swiftlint.yml` looks like this:

```yaml
disabled_rules: # Rule identifiers to exclude from running
  - nesting
  - todo
excluded: # Paths to ignore during linting. Overridden by `included`.
  - Carthage
  - Pods
file_length: 600
line_length: 250
type_body_length: 500
function_body_length: 200
variable_name_max_length:
  - 48 # warning
  - 64 # error
```

The error stays no matter what, even if I bump some values, for example, increasing `type_body_length` to `700`:
![image](https://cloud.githubusercontent.com/assets/350654/12539284/31560e22-c343-11e5-87f6-b389c01939ec.png)
