### ISSUE TITLE
Request: Can the Pre-commit hook apply fixes and stop commit?

### ISSUE THREAD

**Issue by trisco2001** [realm/SwiftLint#4483]
Working on a system by which we can use pre-commits to catch linter errors for us before we push. It's great the integration is there, but it looks like what's there right now just runs SwiftLint in quiet mode, which means only errors will stop the commit.

We like to run without warnings as well, AND we'd like to have the thing apply any fixes it can address automatically similar to behavior we see with Black in Python and dotnet format in C#. 

Is there a way I can configure pre-commit to call `SwiftLint lint --fix --strict` instead of `SwiftLint --quiet` like what seems to be in there today?

I know I could configure it to execute SwiftLint locally, and control it myself, but then I'd miss out on the pre-commit value of gathering and managing SwiftLint for me.

**Comment by trisco2001** [comment]
Nevermind! I figured out how I can customize the entry to get what I wanted. 

```yaml
-   repo: https://github.com/realm/SwiftLint
    rev: 0.49.1
    hooks:
    -   id: swiftlint
        entry: swiftlint --fix --strict
```
