### ISSUE TITLE
Azure Devops CI fails while executing script on application archive for version 0.49.1

### ISSUE THREAD

**Issue by zekax** [realm/SwiftLint#4538]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

Version 0.49.1 fails to execute on the pipeline build for version 0.49.1. The 0.48.0 version runs well with no issues (I had to downgrade to avoid the failed archive process).

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
${PODS_ROOT}/SwiftLint/swiftlint
```

### Environment

- Cocoapods installation (last version: 0.49.1 );
- Xcode script: "${PODS_ROOT}/SwiftLint/swiftlint";
- Azure DevOps CI;
- This build process was executed using '/Applications/Xcode_13.2.1.app';

```yml
disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Projname 2.x/Managers/Auth
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Projname 2.x/Managers/JSONManager
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self # configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 
  warning: 110
  error: 500
  ignores_comments: true
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
```
CmdLine Log from pipeline Job:
...
▸ Generating 'Projname.app.dSYM'
▸ Running script 'Run Script'
▸ Running script '[CP] Embed Pods Frameworks'
▸ Running script '[CP] Copy Pods Resources'
▸ Copying /Users/runner/Library/Developer/Xcode/DerivedData/Projname-hgguatwpbblkpqbovrbrspierero/Build/Intermediates.noindex/ArchiveIntermediates/Projname/BuildProductsPath/Debug\ (Development)-iphoneos/ProjnameOneSignalPushNotificationProd.appex
▸ Copying /Users/runner/Library/Developer/Xcode/DerivedData/Projname-hgguatwpbblkpqbovrbrspierero/Build/Intermediates.noindex/ArchiveIntermediates/Projname/BuildProductsPath/Debug\ (Development)-iphoneos/ProjnameOneSignalPushNotificationDev.appex
▸ Running script 'Run Script'   **[this is the script for swiftlint, also the last building phase in xcode]**
** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/runner/Library/Developer/Xcode/DerivedData/Projname-hgguatwpbblkpqbovrbrspierero/Build/Intermediates.noindex/ArchiveIntermediates/Projname/IntermediateBuildFilesPath/Projname.build/Debug\ (Development)-iphoneos/Projname\ 2.x.build/Script-AC0015C9291AD26900467A11.sh (in target 'Projname 2.x' from project 'Projname')
(1 failure)
[13:20:18]: Exit status: 65
...
[13:20:18]: 

+---------------+--------------------------------+
|               Build environment                |
+---------------+--------------------------------+
| xcode_path    | /Applications/Xcode_13.2.1.app |
| gym_version   | 2.210.1                        |
| export_method | development                    |
| sdk           | iPhoneOS15.2.sdk               |
+---------------+--------------------------------+

[13:20:19]: ▸ Command PhaseScriptExecution failed with a nonzero exit code
...
