### ISSUE TITLE
I guess SwiftLint is not checking error on Ventura 13.0.1

### ISSUE THREAD

**Issue by sungyeopTW** [realm/SwiftLint#4598]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

I used SwiftLint from `local` and `githubAction` when macOS was `Moterey 12.6.1`.

Recently I update local macOS to `Ventura 13.0.1`. 
Then SwiftLint is not checking error in `local` but just in `githubAction`.

For test, I added `line_length: 10` Rules. (because almost of my code's length is more then 10)
So SwiftLint in githubAction occured line lenghth error like below image.
But local has not error. (ofCourse all setting and configuration is same except macOS version and Xcode version)
![스크린샷 2022-11-28 오후 3 08 44](https://user-images.githubusercontent.com/83809841/204208407-2a165c5e-d129-4a38-832e-1f9943991f5d.png)

I was trying to find similar situation about this.
and I find https://github.com/realm/SwiftLint/issues/4208 but it's not useful to me.
What is a problem and how can I fix ??

### Environment

** local (not working)
macOS version: Ventura 13.0.1
Xcode version: 14.1
SwiftLint version: 0.50.1
Installation method used: CocoaPods

** githubAction (working)
macOS version: Monterey 12.6.1
Xcode version: 13.2.1
SwiftLint version: 0.50.1
Installation method used: CocoaPods

```yml
disabled_rules:
  - block_based_kvo
  - class_delegate_protocol
  - computed_accessors_order
  - cyclomatic_complexity
  - deployment_target
  - file_length
  - for_where
  - force_cast
  - function_body_length
  - inclusive_language
  - legacy_random
  - notification_center_detachment
  - nsobject_prefer_isequal
  - private_over_fileprivate
  - protocol_property_accessors_order
  - todo
  - trailing_whitespace
  - type_body_length
  - unused_closure_parameter
  - valid_ibinspectable
  - vertical_whitespace

line_length: 10 # for test
```
