### ISSUE TITLE
SourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed [1]    66032 trace trap  swiftlint

### ISSUE THREAD

**Issue by tahabebek** [realm/SwiftLint#4602]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

"swiftlint" command on terminal fails with error:
```
SourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
[1]    66032 trace trap  swiftlint
```

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
SourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
[1]    66439 trace trap  swiftlint lint
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
0.50.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
Homebrew
* Paste your configuration file:

```yml
# insert yaml contents here
only_rules:
    - trailing_newline
    - colon
    - comma
    - block_based_kvo
    - closing_brace
    - closure_parameter_position
    - comment_spacing
    - computed_accessors_order
    - control_statement
    - custom_rules
    - deployment_target
    - discouraged_direct_init
    - duplicate_imports
    - duplicated_key_in_dictionary_literal
    - dynamic_inline
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - generic_type_name
    - redundant_optional_initialization
    - statement_position
    - trailing_whitespace
    - vertical_whitespace
    - trailing_semicolon
    - void_return
    - unused_closure_parameter
    - trailing_comma
    - syntactic_sugar
    - legacy_constructor
    - switch_case_alignment
    - opening_brace
    - return_arrow_whitespace
    - redundant_void_return
    - redundant_objc_attribute
    - redundant_discardable_let
    - operator_whitespace
    - no_space_in_method_call
    - mark
    - leading_whitespace
excluded:
  - Pods

```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? NO
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check xcodebuild -version)?
```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```
Actually, using XCode 14.1
