### ISSUE TITLE
optional binding trigger explicit_type_interface

### ISSUE THREAD

**Issue by astroboy0803** [realm/SwiftLint#4752]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* SwiftLint version  0.50.3
* Installation method used Homebrew
* Paste your configuration file:

```yml
file_length:
  warning: 800
  error: 1200
  ignore_comment_only_lines: true

disabled_rules:
   - trailing_comma

opt_in_rules:
  - explicit_type_interface
  - modifier_order
  - strict_fileprivate
  - explicit_init
  - fatal_error_message
  - implicit_return
  - strong_iboutlet
  - yoda_condition
  - missing_docs
  - switch_case_on_newline
```

* Which Xcode version are you using? 14.2.0(14C18)
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
var opt: Int?

if let opt = opt {
    print(opt)
}

if let opt {
    print(opt)
}

// but guard let is correct

guard let opt else {
    return
}

```
