### ISSUE TITLE
identifier_name issue didn't show warning 

### ISSUE THREAD

**Issue by ilikerb0407** [realm/SwiftLint#4767]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

 In an exception to the above, variable names may start with a capital letter when they are **declared static and immutable.**
Above is the sentence on SwiftLint Rules, I found out that when I declared  `static var AbCvar = 0`, and Xcode didn't show the warning because I realize the rule mention static and immutable. What is the reason ?

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.50.3
* Installation method used (Homebrew, CocoaPods, building from source, etc)? Homebrew
* Paste your configuration file:

```yml
excluded:
  - Pods
disabled_rules:
  - trailing_whitespace
identifier_name:
  excluded: # excluded via string array
    - id
    - URL
    - url
    - app
file_length:
  warning: 500
  error: 800
type_body_length:
  - 500 # warning
  - 700 # error
```
