### ISSUE TITLE
Auto-fixing `trailing_semicolon` rule deletes trailing comments

### ISSUE THREAD

**Issue by JordanLongstaff** [realm/SwiftLint#4817]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When SwiftLint auto-fixes a `trailing_semicolon` violation, it also deletes any comment after the semicolon. It shouldn't.

#### Original line:
```
private let pulseVelocity: CGFloat = 878 / 2;  // 878 px / 2 seconds
```

#### Command:
```bash
$ swiftlint lint --fix
```

#### Expected:
```
private let pulseVelocity: CGFloat = 878 / 2  // 878 px / 2 seconds
```

#### Actual:
```
private let pulseVelocity: CGFloat = 878 / 2
```

### Environment

* 0.50.3
* Homebrew
* Paste your configuration file:

```yml
disabled_rules:
 - identifier_name
 - todo
 - trailing_comma
 - type_body_length
 - function_body_length

included:
 - Encircle

excluded:
 - Pods

# Rule configurations
force_cast: warning

class_delegate_protocol: error

cyclomatic_complexity:
  error: 34

identifier_name:
  min_length:
    error: 0
    warning: 3
  excluded:
    - id

line_length: 120
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No.
* Which Xcode version are you using (check `xcodebuild -version`)? 14.2
