### ISSUE TITLE
How to make a custom rule for *.strings files?

### ISSUE THREAD

**Issue by NikKovIos** [realm/SwiftLint#4963]
```
custom_rules:
    localizations_formatting:
        included: ".*.strings"
        name: "Localizations format"
        regex: '^[ a-z_]+ = \"[\w »«,]+\";$'
        message: "Localization format is incorrect"
        severity: error
```

I'm trying to check format of strings in localization files, but it seems that swiftlint ignoring them.
