### ISSUE TITLE
Auto-correct not working on SwiftLint 0.51.0

### ISSUE THREAD

**Issue by gianfilippocisternino** [realm/SwiftLint#4980]
### New Issue Checklist

- [X] Updated SwiftLint to the latest version
- [X] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I am facing an issue with the latest version of SwiftLint auto-fix.
In particular SwiftLint is deleting new lines that must not be removed.

For example this code:
```
    /// The information configuration object fetched from network.
    struct Information: Decodable {
      enum CodingKeys: String, CodingKey {
        case title
        case rows = "ui_rows"
      }

      /// The title of the information section.
      public let title: String?

      /// The list of the rows of the information section.
      public let rows: [Row]
```
Is corrected like this:
```
/// The information configuration object fetched from network.
    struct Information: Decodable {
      enum CodingKeys: String, CodingKey {
        case title
        case rows = "ui_rows"
      }let title: String?let rows: [Row]
```

I have tried the older version of SwiftLint (0.50.3) and that one seems to work fine.

### Environment

* SwiftLint version 0.51.0
* Installed using Homebrew

```yml
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_spacing
  - comment_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_none_name
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_fallthrough_only
  - number_separator
  - object_literal
  - optional_enum_case_matching
  - orphaned_doc_comment
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_set_access_control
  - self_in_property_initialization
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - test_case_accessibility
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_closure_parameter
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - yoda_condition

disabled_rules:
  - opening_brace
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - identifier_name
  - nesting
  - type_name
  - trailing_whitespace
  - inclusive_language
 ```
