### ISSUE TITLE
Feature Request: Mechanism to enable all analyzer rules by default

### ISSUE THREAD

**Issue by 417-72KI** [realm/SwiftLint#4999]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### New feature request
`all` "pseudo-rule" has been added to `opt_in_rules` in #4540.
It would be nice if this could be used in `analyzer_rules` as well.

```yml
opt_in_rules:
  - all # enabled in v0.51.0
analyzer_rules:
  - all # requesting in this issue
```
