### ISSUE TITLE
Force exclude doesn't work as expected when all the specified paths are excluded via the config file

### ISSUE THREAD

**Issue by revolter** [realm/SwiftLint#5062]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

If you use the `--force-exclude` option, but specify only excluded files, the `lint` command errors out.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint --strict --force-exclude Test.generated.swift
Linting Swift files at paths Test.generated.swift
Error: No lintable files found at paths: 'Test.generated.swift'
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 0.52.2
* Installation method used (Homebrew, CocoaPods, building from source, etc)? CocoaPods
* Paste your configuration file:

```yml
excluded:
  - '**/*.generated.swift'
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? No
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)? Xcode 14.2 Build version 14C18
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

```swift
// Nothing
```

**Comment by revolter** [comment]
In my case, I needed to use this `--force-exclude` option in a pre-commit hook (surprised that it's not `true` by default), because, if the only file that I want to commit is excluded, the default hook completely prevents the commit.

So, I found a workaround for this case:
- Replace
  ```yaml
  -   repo: https://github.com/realm/SwiftLint
      rev: 0.52.2
      hooks:
      -   id: swiftlint
          entry: swiftlint --quiet --strict --force-exclude
  ```
  with
  ```yaml
  -   id: swiftlint
      name: SwiftLint
      description: "Check Swift files for issues with SwiftLint"
      entry: swiftlint.sh
      language: script
      types: [swift]
  ```
- Add a `swiftlint.sh` file with the contents:
  ```bash
  #!/usr/bin/env bash

  # https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
  set -euo pipefail

  export GEM_HOME="$HOME/.gems"
  # https://github.com/Homebrew/brew/issues/7857#issuecomment-762994019
  export PATH="$GEM_HOME/bin:/usr/local/bin:/opt/homebrew/bin:$PATH"

  # https://unix.stackexchange.com/questions/445223/preventing-bash-script-from-exiting-after-command-error#comment807203_445223
  set +e
  # https://unix.stackexchange.com/a/132512/102128
  error_message=$(Pods/SwiftLint/swiftlint --quiet --strict --force-exclude "$@" 2>&1)
  set -e

  # https://stackoverflow.com/a/229606/865175
  if [[ $error_message == *'Error: No lintable files found at paths:'* ]]; then
	  exit 0
  fi

  echo "$error_message"
  exit 1
  ```
