### ISSUE TITLE
SwiftLintBinary checksum mismatch

### ISSUE THREAD

**Issue by stujfiter** [realm/SwiftLint#5069]
### Describe the bug

The checksum listed in Package.swift for the SwiftLintBinary does not match the actual checksum of the SwiftLintBinary-macos.artifactbundle.zip

Package.swift
```
...
.binaryTarget(
            name: "SwiftLintBinary",
            url: "https://github.com/realm/SwiftLint/releases/download/0.52.2/SwiftLintBinary-macos.artifactbundle.zip",
            checksum: "89651e1c87fb62faf076ef785a5b1af7f43570b2b74c6773526e0d5114e0578e"
        )
```
##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swift package compute-checksum ~/Downloads/SwiftLintBinary-macos.artifactbundle.zip
e2eea4a5f7516da0bcd3a0a220823c7efe1374ecdecd5327076d3207345dcc9c

$ shasum -a 256 ~/Downloads/SwiftLintBinary-macos.artifactbundle.zip
e2eea4a5f7516da0bcd3a0a220823c7efe1374ecdecd5327076d3207345dcc9c

```

### Environment

* SwiftLint version: 0.52.2
* Installation method used: n/a
* Paste your configuration file: n/a
* Which Xcode version are you using?: Xcode 14.3.1, Build version 14E300c

### Additional Details
When running `pre-commit` with the following `.pre-commit-config.yaml`
```yaml
repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
- hooks:
  - id: detect-secrets
  repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
- hooks:
  - id: swiftlint
  repo: https://github.com/realm/SwiftLint
  rev: 0.52.2
```

I receive the following error
```
Downloading https://github.com/realm/SwiftLint/releases/download/0.52.2/SwiftLintBinary-macos.artifactbundle.zip
    error: checksum of downloaded artifact of binary target 'SwiftLintBinary' (e2eea4a5f7516da0bcd3a0a220823c7efe1374ecdecd5327076d3207345dcc9c) does not match checksum specified by the manifest (89651e1c87fb62faf076ef785a5b1af7f43570b2b74c6773526e0d5114e0578e)
```
