### ISSUE TITLE
.swiftlint.yml not respected when using SPM 

### ISSUE THREAD

**Issue by vikdenic** [realm/SwiftLint#5178]
> ### New Issue Checklist
> * [x]  Updated SwiftLint to the latest version
> * [x]  I searched for [existing GitHub issues]

### Describe the bug

I recently removed the Swiftlint cocoapod and replaced it via Swift Package Manager (SPM). The issue is my project will not build now and Swiftlint is active for files that I am excluding in the yml file. I did the following steps.

1. Removed Swiftlint from podfile and ran pod install.
2. Added Swiftlint to project via SPM
3. Added Swiftlint **Run Build Tool Plug-In** to **Target** > **Build Phases**:

<img width="394" alt="Screenshot 2023-08-15 at 4 27 39 PM" src="https://github.com/realm/SwiftLint/assets/7085697/e245f6bd-4511-49e1-8f3e-43ea3802a021">

5. Added the Swiftlint run script:

<img width="793" alt="Screenshot 2023-08-15 at 4 29 18 PM" src="https://github.com/realm/SwiftLint/assets/7085697/e5d3d585-7c92-417a-bfe0-6990f32b3854">

6. Added `.swiftlint.yml` to the root of my project:

<img width="249" alt="Screenshot 2023-08-15 at 4 29 57 PM" src="https://github.com/realm/SwiftLint/assets/7085697/f13ad7c7-c072-450f-aa32-52bd819511c5">

7. Observe the project will not build / doesn't appear to respect the yml file:

<img width="495" alt="Screenshot 2023-08-15 at 4 31 02 PM" src="https://github.com/realm/SwiftLint/assets/7085697/cf976dc0-bb53-46f5-960c-f17e997575ba">

<img width="664" alt="Screenshot 2023-08-15 at 4 31 28 PM" src="https://github.com/realm/SwiftLint/assets/7085697/7956ea26-cc5e-4066-8b79-7b15ce38a32c">

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
```

### Environment

* Swiftlint version: 0.52.4
* Installation method: Swift Package Manager (SPM).
* Xcode 14.3.1

### yml
```yml
# To disable swiftlint in a file add the following
# swift comment to the top of the file:
# // swiftlint:disable all


excluded:
  - ${PWD}/Carthage
  - ${PWD}/Pods
  - ${PWD}/DerivedData
  - ${PWD}/ios-common/Classes/R.generated.swift

disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment
  - todo
  - unused_capture_list
  - private_over_fileprivate
  - strict_fileprivate

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon # promote to error
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition


custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: warning


attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

force_cast: warning
force_try: warning
function_body_length:
    warning: 60

legacy_hashing: error

identifier_name:
  excluded:
    - i
    - id
    - x
    - y
    - z

indentation_width:
  indentation_width: 4

line_length:
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true
  
trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

```
