### ISSUE TITLE
CI failed with `pre-commit`:  Program crashed: Illegal instruction at ...

### ISSUE THREAD

**Issue by kaankoken** [realm/SwiftLint#5262]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The error happens when we try to run `Swiftlint`, `v0.53.0`, on CI (github-action) with `pre-commit`.
We are using `ubuntu-latest` on `Github Action. It was working until yesterday.

Note: It works on local machine (m1 mac-mini)

##### Complete output when running SwiftLint, including the stack trace and command used
Error: **Program crashed: Illegal instruction at 0x00007fb3db563470**
<details>
  <summary>Error with stacktrace</summary>

```bash

 Run pre-commit/action@v3.0.0
  with:
    extra_args: --all-files
Run python -m pip install pre-commit
  python -m pip install pre-commit
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Defaulting to user installation because normal site-packages is not writeable
Collecting pre-commit
  Downloading pre_commit-3.4.0-py2.py3-none-any.whl (203 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 KB 4.2 MB/s eta 0:00:00
Collecting virtualenv>=20.10.0
  Downloading virtualenv-20.24.5-py3-none-any.whl (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 16.5 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from pre-commit) (5.4.1)
Collecting cfgv>=2.0.0
  Downloading cfgv-3.4.0-py2.py3-none-any.whl (7.2 kB)
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.8.0-py2.py3-none-any.whl (22 kB)
Collecting identify>=1.0.0
  Downloading identify-2.5.30-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.9/98.9 KB 20.2 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from nodeenv>=0.11.1->pre-commit) (59.6.0)
Collecting platformdirs<4,>=3.9.1
  Downloading platformdirs-3.11.0-py3-none-any.whl (17 kB)
Collecting filelock<4,>=3.12.2
  Downloading filelock-3.12.4-py3-none-any.whl (11 kB)
Collecting distlib<1,>=0.3.7
  Downloading distlib-0.3.7-py2.py3-none-any.whl (468 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 25.6 MB/s eta 0:00:00
Installing collected packages: distlib, platformdirs, nodeenv, identify, filelock, cfgv, virtualenv, pre-commit
Successfully installed cfgv-3.4.0 distlib-0.3.7 filelock-3.12.4 identify-2.5.30 nodeenv-1.8.0 platformdirs-3.11.0 pre-commit-3.4.0 virtualenv-20.24.5
Run python -m pip freeze --local
argcomplete==3.1.2
cfgv==3.4.0
distlib==0.3.7
filelock==3.12.4
identify==2.5.30
nodeenv==1.8.0
packaging==23.2
pipx==1.2.0
platformdirs==3.11.0
pre-commit==3.4.0
userpath==1.9.1
virtualenv==20.24.5
Run actions/cache@v3
Cache not found for input keys: pre-commit-3||389ef66d5ad40af641fc010afd314be94b37f855caca837849b251e37c968a28
Run pre-commit run --show-diff-on-failure --color=always --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/nicklockwood/SwiftFormat.
[INFO] Initializing environment for https://github.com/realm/SwiftLint.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/nicklockwood/SwiftFormat.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/realm/SwiftLint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
detect private key.......................................................Passed
check for merge conflicts................................................Passed
check toml...............................................................Passed
SwiftFormat..............................................................Passed
SwiftLint................................................................Failed
- hook id: swiftlint
- exit code: -4

SourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading libsourcekitdInProc.so failed

💣 Program crashed: Illegal instruction at 0x00007fb3db563470

Thread 0 "swiftlint":

0  0x00007fb3da44280a <unknown> in libc.so.6

Thread 1 crashed:

0  0x00007fb3db563470 _assertionFailure(_:_:file:line:flags:) + 384 in libswiftCore.so

Thread 2:

0  0x00007fb3da525fde <unknown> in libc.so.6

Thread 3:

0  0x00007fb3da491197 <unknown> in libc.so.6

Thread 4:

0  0x00007fb3da518e7e <unknown> in libc.so.6

Thread 5:

0  0x00007fb3da51b7ed <unknown> in libc.so.6

Thread 6:

0  0x00007fb3da491197 <unknown> in libc.so.6


Registers:

rax 0x0000000200000003  8589934595
rdx 0x00007fb3d010fe20  58 0d 96 db b3 7f 00 00 03 00 00 00 00 00 00 00  X··Û³···········
rcx 0xfffffffe00000000  18446744065119617024
rbx 0x0000000000000003  3
rsi 0x00007fb3d010fe28  03 00 00 00 00 00 00 00 40 00 00 00 00 00 00 00  ········@·······
rdi 0x00007fb3d00008e0  06 00 07 00 06 00 05 00 06 00 06 00 06 00 01 00  ················
rbp 0x0000000000000025  37
rsp 0x00007fb3d52c30a0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
 r8 0x00007fb3d008e730  ce be 2e 2b b4 7f 00 00 7a 9c 0b 7e 1d de fd c4  Î¾.+´···z··~·ÞýÄ
 r9 0x00007fb3d52c2df0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
r10 0x0000000000000000  0
r11 0xc4fdde1d7e0b9c7a  14194745818791779450
r12 0x0000000000000000  0
r13 0x0000000000000002  2
r14 0x00005601477b5579  46 61 74 61 6c 20 65 72 72 6f 72 00 6f 66 66 73  Fatal error·offs
r15 0x000000000000000b  11
rip 0x00007fb3db563470  0f 0b 48 83 ec 08 48 8d 05 b3 60 41 00 48 8d 3d  ··H·ì·H··³`A·H·=

rflags 0x0000000000010246  ZF PF

cs 0x0033  fs 0x0000  gs 0x0000


Images (52 omitted):

0x00007fb3da400000–0x00007fb3da5bc501 229b7dc509053fe4df5e29e8629911f0c3bc66dd libc.so.6       /usr/lib/x86_64-linux-gnu/libc.so.6
0x00007fb3db400000–0x00007fb3db93dd68 <no build ID>                            libswiftCore.so /usr/share/swift/usr/lib/swift/linux/libswiftCore.so

SourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading libsourcekitdInProc.so failed

💣 Program crashed: Illegal instruction at 0x00007fd9d2963470

Thread 0 "swiftlint":

0  0x00007fd9d164280a <unknown> in libc.so.6

Thread 1 crashed:

0  0x00007fd9d2963470 _assertionFailure(_:_:file:line:flags:) + 384 in libswiftCore.so

Thread 2:

0  0x00007fd9d1725fde <unknown> in libc.so.6

Thread 3:

0  0x00007fd9d1691197 <unknown> in libc.so.6

Thread 4:

0  0x00007fd9d1718e7e <unknown> in libc.so.6

Thread 5:

0  0x00007fd9d171b7ed <unknown> in libc.so.6

Thread 6:

0  0x00007fd9d1691197 <unknown> in libc.so.6


Registers:

rax 0x0000000200000003  8589934595
rdx 0x00007fd9c4138680  58 0d d6 d2 d9 7f 00 00 03 00 00 00 00 00 00 00  X·ÖÒÙ···········
rcx 0xfffffffe00000000  18446744065119617024
rbx 0x0000000000000003  3
rsi 0x00007fd9c4138688  03 00 00 00 00 00 00 00 40 00 00 00 00 00 00 00  ········@·······
rdi 0x00007fd9c40008e0  06 00 07 00 06 00 05 00 06 00 06 00 06 00 01 00  ················
rbp 0x0000000000000025  37
rsp 0x00007fd9cc4c30a0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
 r8 0x00007fd9c408e750  6e be 8e 39 de 7f 00 00 9f 37 b9 a4 16 f5 4c 28  n¾·9Þ····7¹¤·õL(
 r9 0x00007fd9cc4c2df0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ················
r10 0x0000000000000000  0
r11 0x284cf516a4b9379f  2903965337348814751
r12 0x0000000000000000  0
r13 0x0000000000000002  2
r14 0x0000562c8db00579  46 61 74 61 6c 20 65 72 72 6f 72 00 6f 66 66 73  Fatal error·offs
r15 0x000000000000000b  11
rip 0x00007fd9d2963470  0f 0b 48 83 ec 08 48 8d 05 b3 60 41 00 48 8d 3d  ··H·ì·H··³`A·H·=

rflags 0x0000000000010246  ZF PF

cs 0x0033  fs 0x0000  gs 0x0000


Images (52 omitted):

0x00007fd9d1600000–0x00007fd9d17bc501 229b7dc509053fe4df5e29e8629911f0c3bc66dd libc.so.6       /usr/lib/x86_64-linux-gnu/libc.so.6
0x00007fd9d2800000–0x00007fd9d2d3dd68 <no build ID>                            libswiftCore.so /usr/share/swift/usr/lib/swift/linux/libswiftCore.so
```
</details>

### Environment

* SwiftLint version: `0.53.0`
* Installation method used (Homebrew, CocoaPods, building from source, etc): `pre-commit` (I believe it uses the repo directly)
* Paste your configuration file:

```yml
ci:
  autofix_prs: false

exclude: '.*\.json$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.51.15
    hooks:
      - id: swiftformat
        args:
          - --lint
  - repo: https://github.com/realm/SwiftLint
    rev: 0.53.0
    hooks:
      - id: swiftlint
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)?
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.

You could create a workflow to try it.
```yaml
name: CI

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: set Python
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v3.0.0
```
