### ISSUE TITLE
Swift Package Plugin linting takes a long time

### ISSUE THREAD

**Issue by vladvlasov256** [realm/SwiftLint#5329]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

We have a relatively not very large project with 138k LOC.
SwiftLint needs about 2 seconds to lint it.
But when we added the SPM plugin linting time regressed to 180 seconds.

##### Complete output when running SwiftLint, including the stack trace and command used

```bash
$ swiftlint lint
Linting Swift files in current working directory
...
Done linting! Found 5 violations, 0 serious in 304 files.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure)?
  - 0.53.0
* Installation method used (Homebrew, CocoaPods, building from source, etc)?
  - Swift Package Plugin, brew, and building from source
* Paste your configuration file:

```yml
swiftlint_version: 0.53.0

disabled_rules:
  - trailing_whitespace
  - line_length
  - function_parameter_count
  - large_tuple
  
opt_in_rules:
  - attributes:
    - attributes_with_arguments_always_on_line_above: false
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet

identifier_name:
  min_length: 2

excluded:
  - ruby_env
  - "**/.build"
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  - No
* Which Xcode version are you using (check `xcodebuild -version`)?
  - Xcode 15.0.1
* Do you have a sample that shows the issue?

In Xcode logs I see the following command:
```bash
/Users/user/Library/Developer/Xcode/DerivedData/MyProject/SourcePackages/artifacts/swiftlint/SwiftLintBinary/SwiftLintBinary.artifactbundle/swiftlint-0.53.0-macos/bin/swiftlint lint --quiet --force-exclude --cache-path /Users/user/Library/Developer/Xcode/DerivedData/MyProject/SourcePackages/plugins/MyProject.output/MyTarget/SwiftLintPlugin --config /Users/user/myproject/.swiftlint.yml ...
```
All 164 swift files are specified as a command input.
