### ISSUE TITLE
Is blanket_disable_command really necessary?

### ISSUE THREAD

**Issue by tomhuettmann** [realm/SwiftLint#5450]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version (updated via brew, brew currently still uses `0.53.0`)
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Question / New rule request

I stumbled across the paragraph in the `README.md:L432-433`:

> ...
> The rules will be disabled until the end of the file or until the linter sees a matching enable comment:
> ...

and see a collision with the in https://github.com/realm/SwiftLint/pull/4731 introduced `blanket_disable_command` rule (https://realm.github.io/SwiftLint/blanket_disable_command.html).

My question now is if re-enabling rules before the end of file is really necessary or not? I tried it out in a simple project, and it seems like written in the README.md, all the disabled files are automatically enabled again before linting the next file.

If so, I would like to recommend a new rule to get rid of those introduced unnecessary enable commands at file endings:

```yaml
no_swiftlint_enable_at_end_of_file:
  name: 'No SwiftLint enable at end of file'
  message: 'There is no swiftlint:enable necessary at the end of a file'
  regex: 'swiftlint:enable[^\n]*\n*\Z'
```

Non triggering example:
```
// swiftlint:disable foo
... some code ...
// swiftlint:enable foo
... some code ...
```

Triggering example:
```
// swiftlint:disable foo
... some code ...
// swiftlint:enable foo

```
, where the `// swiftlint:enable foo` is the last thing before EOF.
