### ISSUE TITLE
There is a problem with allowed_symbols rule configuration after updating to 0.54.0

### ISSUE THREAD

**Issue by tema-tian** [realm/SwiftLint#5565]
#### Configuration of type_name

```
type_name:
  allowed_symbols: ['_']
  min_length: 3
  unallowed_symbols_severity: warning
  validates_start_with_lowercase: error
  severity: warning
```

#### Error message
```
Type Name Violation: Type name 'Tra_xxx_xxx' should only contain alphanumeric and other allowed characters (type_name)
```
