### ISSUE TITLE
Add a rule banning the use of viewWithTag

### ISSUE THREAD

**Issue by Noobish1** [realm/SwiftLint#559]
In one of our projects we have this defined in your `.swiftlint.yml`:
```
custom_rules:
  view_with_tag_usage:
    name: "View With Tag usage"
    regex: "(viewWithTag)"
    match_kinds:
      - identifier
    message: "A Kitten dies everytime you use viewWithTag, do not use viewWithTag"
    severity: error
```

I thought it might be nice to have it built in. `viewWithTag` is evil after all.
