### ISSUE TITLE
Report and Improvements on Swiftlint baseline

### ISSUE THREAD

**Issue by aiKrice** [realm/SwiftLint#5597]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

I played this week end on with the baseline feature. First of all thank @mildm8nnered  and all contributors, Amazing job and I am here also to help with my way, by trying hard.

I noticed several behavior that imho, are not exactly what I expected, as an Android developer as well, Detekt and AndroidLint baseline user.

1️⃣. I generate a baseline with this command: 
```bash
$ swiftlint --write-baseline config/swiftlint/baseline.json
```
I noticed a different behavior in the content of the baseline if I specifiy my config file
```bash
$ swiftlint --write-baseline config/swiftlint/baseline.json --config config/swiftlint/swifltint.yml
```

2️⃣. In both case above, I noticed that some rules some not ignored in the baseline so swiftlint failed. It was these rules :
- explicit_top_level_acl
- explicit_acl
- prefixed_toplevel_constant

It's maybe because this file was listed as excluded in my config file (see it below #githooks)

3️⃣. I generated a baseline with all rules enabled (as suggested in another issue opened) (but baseline should not be generated this way but against a configuration file), In this case "it works".

4️⃣. The baseline json file is a single 1 line file 😱 . In this case, Xcode (well, xcode...) cant read it. So I use a third party to format it: prettier -> https://github.com/prettier/prettier to format it. I think this should be opt-in because to compare this on a PR even to make it readable, it better. But by using prettier and an intermediate tool, there are some noises and too many illegitimates diffs.

Voila, hoping it can help, I am ready to kepp helping for improving it on my project 💪 .   

### Environment

version: 0.55.1
Homebrew, Mac M1PRO 14"
Xcode 15.4
Build version 15F31d

```yml
disabled_rules: # rule identifiers to exclude from running
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - attributes
  - balanced_xctest_lifecycle
  - closure_end_indentation
  - closure_spacing
  - closure_body_length
  - collection_alignment
  - conditional_returns_on_newline
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - explicit_type_interface
  - function_body_length
  - ibinspectable_in_extension
  - indentation_width
  - let_var_whitespace
  - literal_expression_end_indentation
  - missing_docs
  - number_separator # Swiftformat
  - object_literal
  - operator_usage_whitespace
  - one_declaration_per_file
  - period_spacing
  - prefer_nimble
  - prohibited_interface_builder
  - raw_value_for_camel_cased_codable_enum #Need to be reactivated when we will refactor the model
  - required_deinit
  - switch_case_on_newline # Swiftformat
  - switch_case_alignment # Swiftformat
  - trailing_whitespace #SwiftFormat
  - unneeded_parentheses_in_closure_argument # Swiftformat
  - vertical_parameter_alignment_on_call # Swiftformat
  - vertical_whitespace_between_cases # Swiftformat
  - vertical_whitespace_closing_braces # Swiftformat
  - vertical_whitespace_opening_braces # Swiftformat
  - xct_specific_matcher

analyzer_rules:
  - capture_variable
  - explicit_self
  - typesafe_array_init
  - unused_declaration
  - unused_import
 
opt_in_rules: # some rules are only opt-in
  - all
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Shopmium
  - Packages
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - build
  - Shopmium/Resources
  - Shopmium/AppConfig/Constants.swift
  - Shopmium/BuildGenerated/Sourcery/Generated
  - Packages/Foundation/ShopmiumSDK # Baseline: Please remove this line when the SDK will be ready to be linted
  - Packages/Foundation/Alamofire
  - Packages/Foundation/SparrowKit/Sources/SparrowKit/Classes/Constants
  - ShopmiumBATGenerator
  - Shopmium/UI/Feature/Explorer
  - ShopmiumUITests
  - ShopmiumUnitTests
  - Showcase/Showcase
  - githooks # <------------------------ my file is inside this folder 
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

file_name:
  excluded:
    - "AppearanceThemeDomainMapper.swift"
    - "BackgroundManager.swift"
    - "DeprecationAlert.swift"
    - "EventListenerContractExtension.swift"
    - "Factories.swift"
    - "FavoritesManager.swift"
    - "FavoritesRouter.swift"
    - "GenerateBarcode.swift"
    - "Loader.swift"
    - "LoginManager.swift"
    - "PiggyBankViewExtension.swift"
    - "OffersManager.swift"
    - "OffersListCellTypeExtension.swift"
    - "OffersTabUIItemTypeExtension.swift"
    - "OfferTagsLimitation.swift"
    - "OfferTagsLockedOrUnlocked.swift"
    - "OfferTagsRemainingCoupons.swift"
    - "OfferTagsShopmiumClub.swift"
    - "OfferTagsTimeStatus.swift"
    - "PaymentManager.swift"
    - "ReportManager.swift"
    - "SparrowAlias.swift"
    - "SubmissionsManager.swift"
    - "TabBarContentViews.swift"
    - "UIViewAnimations.swift"
    - "UserRepository.swift"
    - "UserStore.swift"
    - "WalletRouter.swift"
    - "XCAssets+Generated.swift"
    - "XibLoader.swift"


line_length: 120

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)

```
