### ISSUE TITLE
Enforce attributes to be on the same line only if they don't have arguments

### ISSUE THREAD

**Issue by Reyshawn** [realm/SwiftLint#5618]
### New Issue Checklist

- [x] Updated SwiftLint to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

When I set the `@objc` attribute always at the same line and set the option `attributes_with_arguments_always_on_line_above` to `true`.

It triggers a warning when I put the `@objc(addEpisodesObject:)`, which has arguments on its own line;

```swift
// MARK: Generated accessors for episodes
extension Season {
    @objc(addEpisodesObject:)
    @NSManaged public func addToEpisodes(_ value: Episode)
}
```

```yaml
opt_in_rules:
  - attributes
attributes:
  attributes_with_arguments_always_on_line_above: true
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
    - "@nonobjc"
```

How could I enforce attributes to be on their own line if they have arguments, and on the same line if they don't have arguments?

### Environment

* SwiftLint version (run `swiftlint version` to be sure)? 
0.55.1
* Installation method used (Homebrew, CocoaPods, building from source, etc)? 
Homebrew
* Paste your configuration file:

```yml
# insert yaml contents here
```

* Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)?
  If so, paste their relative paths and respective contents.
* Which Xcode version are you using (check `xcodebuild -version`)?
Xcode 15.4
Build version 15F31d
* Do you have a sample that shows the issue? Run `echo "[string here]" | swiftlint lint --no-cache --use-stdin --enable-all-rules`
  to quickly test if your example is really demonstrating the issue. If your example is more
  complex, you can use `swiftlint lint --path [file here] --no-cache --enable-all-rules`.
