### ISSUE TITLE
Custom rules as part of `only_rules` don't work (anymore?)

### ISSUE THREAD

**Issue by daniel-moh** [realm/SwiftLint#5689]
I have tried to add a custom rule to an `only_rules` setup. However, when running `swiftlint` (latest version 0.55.1) the custom rule doesn't get recognized in the `only_rules` list. 

I found a related issue indicating that this worked in the past (https://github.com/realm/SwiftLint/issues/5187). So I'm thinking either I am doing something terribly wrong (I tried my best to rule this out, see a reproducible example below) or this is a regression.

Of course, I also:
- [x] Updated SwiftLint to the latest version
- [x] Searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Minimal, reproducible example

Hers's my setup:

```
.
├── .swiftlint.yml
└── Ninja.swift

1 directory, 2 files
```

With a Swift file like so:

``` swift
// Ninja.swift

let name = "Ninja"
```

And a SwiftLint config file with the [exemplary custom rule from the readme](https://github.com/realm/SwiftLint?tab=readme-ov-file#2-regex-custom-rules) and the [`custom_rules` as an item under `only_rules`](https://github.com/realm/SwiftLint?tab=readme-ov-file#2-regex-custom-rules) as described in the docs:

``` yml
# swiftlint.yml

custom_rules:
  no_hiding_in_strings:
    regex: "([nN]inja)"
    match_kinds: string

only_rules:
  - no_hiding_in_strings
```

But it doesn't seem to work:

```
$ swiftlint --version
0.55.1

$ swiftlint lint --config .swiftlint.yml --no-cache Ninja.swift
warning: Found a configuration for 'custom_rules' rule, but it is not present in 'only_rules'.
Linting Swift files at paths Ninja.swift
Linting 'Ninja.swift' (1/1)
Done linting! Found 0 violations, 0 serious in 1 file.
```

For the record, [despite what the docs say](https://github.com/realm/SwiftLint?tab=readme-ov-file#2-regex-custom-rules), I also tried flipping the order in the config file with the `only_rules` item above the `custom_rules`:

``` yml
only_rules:
  - no_hiding_in_strings

custom_rules:
  no_hiding_in_strings:
    regex: "([nN]inja)"
    match_kinds: string
```

But no luck:

```
$  swiftlint --version
0.55.1

$ swiftlint lint --config .swiftlint.yml --no-cache Ninja.swift
warning: Found a configuration for 'custom_rules' rule, but it is not present in 'only_rules'.
Linting Swift files at paths Ninja.swift
Linting 'Ninja.swift' (1/1)
Done linting! Found 0 violations, 0 serious in 1 file.
```

### Environment

* SwiftLint version: 0.55.1
* Installation method: Homebrew

Any help is greatly appreciated! 🙏

**Comment by SimplyDanny** [comment]
The README states:

> If using custom rules in combination with `only_rules`, make sure to add `custom_rules` as an item under `only_rules`.

The output of `swiftlint` is similarly `Found a configuration for 'custom_rules' rule, but it is not present in 'only_rules'.`.

That means:

```yml
only_rules:
  - custom_rules
```

So while this seems to be unclear, I've no idea how to make crystal clear how it is meant. If you have ideas, please go ahead ... 😉

**Comment by mildm8nnered** [comment]
Naively, I kind of would have expected this to work:

```
only_rules:
  - no_hiding_in_strings

custom_rules:
  no_hiding_in_strings:
    regex: "([nN]inja)"
    match_kinds: string
```

and similarly

```
only_rules:
  - no_hiding_in_strings

custom_rules:
  no_hiding_in_strings:
    regex: "([nN]inja)"
    match_kinds: string
  no_yakuza_in_strings:
    regex: "([yY]akuza)"
    match_kinds: string
```

Maybe we should just change the behavior to match people's expectations (and retain `custom_rules` as a special case meaning all custom rules).

`custom_rules` are a bit funny - I'm still struggling to get `superfluous_disable_command` working properly with them - https://github.com/realm/SwiftLint/pull/5670

**Comment by daniel-moh** [comment]
Ok I see, thanks @SimplyDanny! 😄 

For anyone reading this in the future, the following configuration works:

``` yml
only_rules:
  - custom_rules

custom_rules:
  no_hiding_in_strings:
    regex: "([nN]inja)"
    match_kinds: string
```

Maybe all it takes is an example to clarify things. Opened a PR here https://github.com/realm/SwiftLint/pull/5712. Let me know what you think. 🙏
