### ISSUE TITLE
Substitution support in custom rules

### ISSUE THREAD

**Issue by dankinsoid** [realm/SwiftLint#5728]
### New Issue Checklist

- [ x ] I've Updated SwiftLint to the latest version.
- [ x ] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Feature Request or Enhancement Proposal

I suggest supporting substitutions in custom rules to provide contextual warnings and errors.

Example of the rule with a substitution:
```
    corner_radius_setter:
      name: "CornerRadius setter"
      regex: 'layer\.cornerRadius = (.+)'
      message: "Use setCornerRadius($1) instead"
      severity: warning
```
So for this line:
```swift
layer.cornerRadius = 34
```
We get the message:
Use setCornerRadius(34) instead
