### ISSUE TITLE
Disable no_magic_numbers for preview code

### ISSUE THREAD

**Issue by rberggreen** [realm/SwiftLint#5775]
### New Issue Checklist

- [x] I've Updated SwiftLint to the latest version.
- [x] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Feature or Enhancement Proposal
It would be useful to disable the rule no_magic_numbers for preview code, for the same reason that it's already disabled by default for test code. Previews typically use various hardcoded values. 

<img width="854" alt="Skärmavbild 2024-08-30 kl  14 03 04" src="https://github.com/user-attachments/assets/e811cf50-1ba3-44cc-a465-384932517f3a">

When expanding the `#Preview` macro, it can be observed that all preview code is in a struct implementing the protocol `DeveloperToolsSupport.PreviewRegistry`. However, adding this to the rule's configurable array of `test_parent_classes` does not silence magic number warnings in preview code. Perhaps SwiftLint is run before macro expansion and so perhaps we need a way to disable the rule for code inside certain macros. 

### Rule file example
```yml
only_rules:
  - no_magic_numbers

no_magic_numbers:
  test_parent_classes:
   - "QuickSpec"
   - "XCTestCase"
   - "DeveloperToolsSupport.PreviewRegistry"

```
