### ISSUE TITLE
Having any (non-deprecated) `opening_brace` option in `.swiftlint.yml` triggers deprecation warning

### ISSUE THREAD

**Issue by florianschulz** [realm/SwiftLint#5791]
### New Issue Checklist

- [x] I've Updated SwiftLint to the latest version.
- [x] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

If you include any `opening_brace` option in `.swiftlint.yml`, a warning is emitted right at the beginning of swiftlint's output:

```
% swiftlint
warning: Configuration option 'allow_multiline_func' in 'opening_brace' rule is deprecated. Use the option 'ignore_multiline_function_signatures' instead.
Linting Swift files in current working directory
Linting 'SwiftLintDemoApp.swift' (1/2)
Linting 'ContentView.swift' (2/2)
Done linting! Found 0 violations, 0 serious in 2 files.
```

### Environment

* SwiftLint version 0.57.0
* Installation method used: Homebrew
* Example configuration file:
```yml
opening_brace:
  ignore_multiline_statement_conditions: true
  ignore_multiline_function_signatures: true
```
