### ISSUE TITLE
Unable to set `type_body_length` `function_body_length` `file_length` only as warnings with no error.

### ISSUE THREAD

**Issue by uevs** [realm/SwiftLint#5822]
### New Issue Checklist

- [X] I've Updated SwiftLint to the latest version.
- [X] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

I'm trying to set `type_body_length` `function_body_length` `file_length` to be warning only with custom length. I want to have a warning if the length reaches a certain limit, but no errors. 

This is not clearly documented, but should be available #1647 #1691

I'm testing this by running:

```bash
swiftlint --quiet | grep -E 'error.*(type_body_length|function_body_length|file_length)'
```
And I would expect no errors in the output, but I do get errors using the default error limit of the respective rule.

I tried the following variations: 
```yml
type_body_length: 400
```

```yml
type_body_length:
  warning: 400
```

```yml
type_body_length:
  - 400
```

```yml
type_body_length:
  warning: 400
  error: null
```

```yml
type_body_length:
  warning: 400
  error: nil
```

```yml
type_body_length:
  warning: 400
  error: ~
```

but none is working. It either gets the defults value of the rule:
```
error: Type Body Length Violation: Type body should span 500 lines or less excluding comments and whitespace: currently spans 528 lines (type_body_length)
```

or gives me:

```
warning: Invalid configuration for 'type_body_length' rule. Falling back to default.
```

### Environment

* SwiftLint version: 0.57.0
* Xcode version: 16.0
* Installation method used: Homebrew
* Configuration file:

```yml
only_rules:
  - superfluous_disable_command
  - type_body_length
  - function_body_length
  - line_length
  - file_length
  # auto-correctable rules:
  - leading_whitespace
  - trailing_whitespace
  - trailing_comma
  - trailing_newline
  - colon
  - trailing_semicolon
  - opening_brace
  - closing_brace
  - return_arrow_whitespace
  - comma
  - empty_enum_arguments
  - empty_parameters
  - void_return

excluded:
  - fastlane/.tempbuild
  - Package/**/*/PreviewAssets.swift
  - Package/.build
type_body_length: 400
function_body_length: 91
file_length: 610
line_length:
  warning: 400
  error: 500
```
