### ISSUE TITLE
Adding a `custom_rules` `regex` rule, but not adding that rule to the `only_rules` section in `.swiftlint.yml` causes the SwiftLint to fall back to a default configuration.

### ISSUE THREAD

**Issue by blakemcanally** [realm/SwiftLint#5855]
### New Issue Checklist

- [ ] I've Updated SwiftLint to the latest version.
- [ ] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

Adding a `custom_rules` `regex` rule, but not adding that rule to the `only_rules` section in `.swiftlint.yml` causes the SwiftLint to fall back to a default configuration.

### Environment

* SwiftLint version (run `swiftlint version` to be sure)
* Xcode version (run `xcodebuild -version` to be sure)
* Installation method used (Homebrew, CocoaPods, building from source, etc)
* Configuration file:

```yml
only_rules:
  - attribute_name_spacing
  - blanket_disable_command
  #- block_based_kvo
  - colon
  - comment_spacing
  #- compiler_protocol_init
  #- computed_accessors_order
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - custom_rules
  - deployment_target
  #- discarded_notification_center_observer
  #- discouraged_direct_init
  - duplicate_conditions
  - duplicate_enum_cases
  #- duplicate_imports
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  #- empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  #- empty_string
  #- explicit_init
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_getter
  #- inclusive_language
  - invalid_swiftlint_command
  - is_disjoint
  - last_where
  - legacy_cggeometry_functions
  - legacy_constant
  #- legacy_constructor
  #- legacy_hashing
  - legacy_nsgeometry_functions
  #- legacy_random
  #- lower_acl_than_parent
  #- mark
  - no_space_in_method_call
  #- non_optional_string_data_conversion
  #- notification_center_detachment
  #- ns_number_init_as_function_reference
  #- nslocalizedstring_key
  #- nsobject_prefer_isequal
  - operator_whitespace
  #- optional_data_string_conversion
  #- optional_enum_case_matching
  #- orphaned_doc_comment
  #- overridden_super_call
  #- prefer_key_path
  #- prefer_self_type_over_type_of_self
  #- prefer_type_checking
  #- private_outlet
  #- private_over_fileprivate
  #- private_subject
  #- private_swiftui_state
  #- private_unit_test
  #- prohibited_super_call
  #- protocol_property_accessors_order
  #- reduce_boolean
  - reduce_into
  #- redundant_discardable_let
  #- redundant_nil_coalescing
  #- redundant_objc_attribute
  - redundant_set_access_control
  #- redundant_string_enum_value
  #- redundant_void_return
  - return_arrow_whitespace
  #- self_binding
  #- self_in_property_initialization
  #- shorthand_argument
  #- shorthand_operator
  #- shorthand_optional_binding
  - sorted_first_last
  #- statement_position
  #- static_operator
  #- static_over_final_class
  #- strong_iboutlet
  - superfluous_disable_command
  - switch_case_alignment
  - trailing_semicolon
  - unavailable_condition
  - unneeded_break_in_switch
  #- unneeded_override
  - unused_control_flow_label
  - unused_enumerated
  #- unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  #- void_function_in_ternary
  - void_return
excluded:
  - Pods
  - Packages
custom_rules:
  emtpy_workflow_did_change_implementation:
    regex: "func\s+workflowDidChange\(\s*from\s+previousWorkflow:\s*([^\s,]+(?:<[^>]+>)?),\s*state:\s+inout\s+(?:[a-zA-Z]+\.)?State\)\s*\{\s*\}"
    message: "Remove empty implementation of workflowDidChange(from previousWorkflow: state:)"
    severity: warning
deployment_target:
  iOS_deployment_target: 15
empty_count:
  only_after_dot: true
```
