### ISSUE TITLE
Custom rule - check only once

### ISSUE THREAD

**Issue by salvatoreboemia** [realm/SwiftLint#5873]
Hi 

I'm trying to add custom rules to send to Sonarqube. but first I tried locally with a brew in this way

 ```
custom_rules:
    my_custom_rule: 
      included:
      - ".*.swift"
      name: "My Custom Rule"
      regex: "// my_custom_rule:.*"
      message: "This is a custom rule for testing"
      severity: error
 ```

After that I ran in the terminal swift lint

 ```
swiftlint lint --config myRoot/.swiftlint.yml --reporter json > swiftlint_report.json 
 ```

File Swift

```

// my_custom_rule: Test 1234
import Foundation
import UIKit
// my_custom_rule: Test 12
final class MyClass: NSObject {
    // my_custom_rule: Test 1234
    ......
    // my_custom_rule: Test 1234
    private let .......
    ......
    // my_custom_rule: Test 1234
    var .....
    // my_custom_rule: Test 
  .....
```

JSON 

```
{
    "character" : 1,
    "file" : "/myFile.swift",
    "line" : 9,
    "reason" : "This is a custom rule for testing",
    "rule_id" : "my_custom_rule",
    "severity" : "Error",
    "type" : "My Custom Rule"
  },
```

Why only in the line 9? I added a lot of comment, Do you know somethings?

thanks
