### ISSUE TITLE
opening_braces allows some multiline if statements, others get flagged

### ISSUE THREAD

**Issue by dhoerl-lp** [realm/SwiftLint#5923]
### New Issue Checklist

- [x] I've Updated SwiftLint to the latest version.
- [x] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

Related issues: #5521, #5602

Some multiline if statements with a starting brace don't trigger an error, but more complicated lines do. For instance no warning:

```swift
// Instance variables
var foo = 5
var goo = 7

if
    self.foo == 9,
    self.goo == 10
{
    print("SUCCESS")
} else {
    fatalError()
}
```

More usual code triggers an `opening_brace` error:

```swift
    if
        let rootVC = AppDelegate.myDelegate.window?.rootViewController as? XYZ,
        let abcVC = rootVC.myArray.first as? ABC
    {
        ...
    } else {
        fatalError()
    }
```

### Environment

* SwiftLint version 0.57.1
* Xcode version 16.2
* Installation method used Swift Package
* Configuration file:

```yml
# Case-sensitive paths to include during linting. Directory paths supplied on the
# command line will be ignored.
included: 
  - abc
  - def
excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - 1111

# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - trailing_whitespace
  - line_length
  - force_cast
  - cyclomatic_complexity
  - function_body_length
  - identifier_name
  - file_length
  - function_parameter_count
  - large_tuple
  - type_name
  - type_body_length
  - todo
  - no_fallthrough_only
  - static_over_final_class
  - inclusive_language
  - legacy_random
  - nesting
  - nsobject_prefer_isequal
  - force_try
  - closure_parameter_position

opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # find all the available rules by running: `swiftlint rules`

analyzer_rules: # rules run by `swiftlint analyze`
  - explicit_self

# If true, SwiftLint will not fail if no lintable files are found.
allow_zero_lintable_files: false

# If true, SwiftLint will treat all warnings as errors.
strict: false

# If true, SwiftLint will treat all errors as warnings.
lenient: false

# If true, SwiftLint will check for updates after linting or analyzing.
check_for_updates: true

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)

colon:
  severity: error

comma:
  severity: error

control_statement:
  severity: error

trailing_comma:
  severity: error
  mandatory_comma: true

```

Are you using [nested configurations](https://github.com/realm/SwiftLint#nested-configurations)? If so, paste their
relative paths and respective contents. N/A
