### ISSUE TITLE
Binary in Docker Image for `0.58.0` reports version `0.57.1`

### ISSUE THREAD

**Issue by andrewdmontgomery** [realm/SwiftLint#5966]
### New Issue Checklist

- [x] I've Updated SwiftLint to the latest version.
- [x] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

The `swiftlint` binary in the `0.58.0` docker image reports that it is version `0.57.1`.  Note that I am running this on Apple Silicon, hence the `--platform` option in the `docker run` command below.  However, we also see the same thing in CI, which runs on `linux/amd64`.

**Apple Silicon**
```shell
$ docker run -it --platform linux/amd64 ghcr.io/realm/swiftlint:0.58.0 swiftlint --version
Unable to find image 'ghcr.io/realm/swiftlint:0.58.0' locally
0.58.0: Pulling from realm/swiftlint
de44b265507a: Pull complete
8718f4f5e50c: Pull complete
6e687c913312: Pull complete
b3d29ab723b4: Pull complete
cf3691679039: Pull complete
76e47102f2a9: Pull complete
6b3bcc82bc86: Pull complete
b4669235d0eb: Pull complete
537acf74a7a6: Pull complete
6431e8f7399a: Pull complete
d77fbf8071a1: Pull complete
39d62eca93cc: Pull complete
0b235ed03e37: Pull complete
d8961c0fcc94: Pull complete
953389c2006c: Pull complete
b2b2cca6f9e7: Pull complete
41a3c0af4e6c: Pull complete
d60384f06df9: Pull complete
f214275f516b: Pull complete
b530521e93c9: Pull complete
44522d4bf699: Pull complete
42ce554ae246: Pull complete
a2e7976b5aa5: Pull complete
69600c272f5e: Pull complete
1bda57782865: Pull complete
3cc7443e3f28: Pull complete
bc94a15fc249: Pull complete
5cfda18034e5: Pull complete
5817fb423b44: Pull complete
026259948dad: Pull complete
5cf5414d4378: Pull complete
4510959b5857: Pull complete
4f4fb700ef54: Pull complete
430b205bc580: Pull complete
Digest: sha256:27b2dc68fb35f554d5cebcb7b47345d95559f85011bc50ef511dab36d3ae1277
Status: Downloaded newer image for ghcr.io/realm/swiftlint:0.58.0
0.57.1
```

Since we specify `swiftlint_version: 0.58.0` in our `.swiftlint.yml`, this causes SwiftLint to exit with a warning:

```shell
$ docker run -it --platform linux/amd64 -v `pwd`:`pwd` -w `pwd` ghcr.io/realm/swiftlint:0.58.0
warning: Currently running SwiftLint 0.57.1 but configuration specified version 0.58.0.
```

**CI**
```shell
[2025-01-15T18:51:29Z] Status: Downloaded newer image for ghcr.io/realm/swiftlint:0.58.0
[2025-01-15T18:51:30Z] warning: Currently running SwiftLint 0.57.1 but configuration specified version 0.58.0.
```

### Environment

* SwiftLint version (run `swiftlint version` to be sure): `swiftlint version` reports `0.57.1`.  But the `docker run` invocation specifies `0.58.0`
* Xcode version (run `xcodebuild -version` to be sure): Xcode 16.2 (16C5032a)
* Installation method used (Homebrew, CocoaPods, building from source, etc): Docker Image
* Configuration file:

```yml
swiftlint_version: 0.58.0
only_rules: # Rules to run
  - custom_rules

# If true, SwiftLint will treat all warnings as errors.
strict: true

included:
  - Sources
  - Tests

custom_rules:
  no_ns_localized_string:
    included:
      - "Sources/.*\\.swift"
    name: "No NSLocalizedString"
    regex: "NSLocalizedString\\("
    match_kinds:
      - identifier
    message: "Use `SDKLocalizedString()` instead of `NSLocalizedString()`."
    severity: error
```
