### ISSUE TITLE
Custom rule plus symbol in excluded not working

### ISSUE THREAD

**Issue by NikKovIos** [realm/SwiftLint#5998]
Rule:

```
date_formatter_not_use:
        name: "AppInstances.shared.dateFormatter not use directly"
        excluded:
          - 'Date+DateFormatterStrings.swift'
        regex: '(AppInstances.shared.dateFormatter)'
        message: "Date formatter must be used via Date+DateFormatterStrings extension"
        severity: error
```

Looks like plus symbol not notified by lint.
If I rename file to DateFormatterStrings.swift and put in excluded 'DateFormatterStrings.swift', the rule works.
