### ISSUE TITLE
Usage of `exclude` with force_unwrapping

### ISSUE THREAD

**Issue by kostasniks** [realm/SwiftLint#6087]
```yml
opt_in_rules:
  - force_unwrapping

force_unwrapping: 
  severity: error
  excluded:
    - ".*Tests\\.swift"
```

Seels like excluded is not working to my expectations.
I want to exclude `force_unwrapping` from certain files that belong in the following folders pattern ⏬ 

```txt
📁Folders
Modules/PAM/Foo1/Tests
Modules/PAM/Foo2/Tests
Modules/PAM/Foo3/Tests
Modules/PAM/Foo4/Tests
Modules/PAM/Foo5/Tests
Modules/PAM/TwoFactorAuthentication/Tests
Modules/PAM/Wallet/Tests
Modules/PLATFORM/Analytics/Tests
Modules/PLATFORM/AppSecurity/Tests
Modules/PLATFORM/Core/Tests
Modules/PLATFORM/Debug/Tests
Modules/PLATFORM/Deeplinks/Tests
Modules/PLATFORM/DomainResolver/Tests
Modules/PLATFORM/ExecutableTask/Tests
```

I've come up with following questions 
1) Is `excluded` supported on non-custom rules?
2) Is there a guide on what excluded supports and what not? If someone can point me to a source code to take a look (is it a regex? a glob pattern?)
3) What would be the solution for this usecase, if exists 🤔

**Comment by kapitoshka438** [comment]
I hope all your tests are located in one folder. Then you can just create a child swiftlint.yml in this folder with the rule disabled.

**Comment by kostasniks** [comment]
Sure, I will take a look at this as plan_B as I am currently using swiftlint as Xcode build plugin so need to check if is supported there, anyways thank you @kapitoshka438 🙌

**Comment by SimplyDanny** [comment]
The main issue is that `excluded` is not a property of rules but of the whole configuration. Thus, your configuration should actually look more like:

```yml
excluded:
  - ".*Tests\\.swift"

force_unwrapping: 
  severity: error
```
