### ISSUE TITLE
False positive in "duplicate_imports" corner case

### ISSUE THREAD

**Issue by ptsochantaris** [realm/SwiftLint#6098]
### New Issue Checklist

- [x] I've Updated SwiftLint to the latest version.
- [x] I've searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues).

### Bug Description

SwiftLint produces a false positive in this case:

![Image](https://github.com/user-attachments/assets/f6a8e8a6-a946-448d-a4e6-6f76d2f5f1b0)

### Environment

* SwiftLint version - *0.59.1*
* Xcode version - *16.4*
* Installation method used - *Homebrew*
* Configuration file:

```yml
disabled_rules:
  - identifier_name
  - line_length
  - trailing_whitespace
  - force_cast
  - file_length
  - function_body_length
  - nesting
  - notification_center_detachment
  - unused_setter_value
  - cyclomatic_complexity
  - type_body_length
  - force_try
  - implicit_getter
  - large_tuple

excluded:
  - Pods

analyzer_rules:
  - unused_import
```
