### ISSUE TITLE
characters.count in matchesInString

### ISSUE THREAD

**Issue by s-aska** [realm/SwiftLint#664]
matchesInString requires a range specified by the utf16.count, but you find often a code that uses the characters.count. 😿
Is it possible to solve this problem?

**Not Preferred:**
```swift
.matchesInString(string, options: [], range: NSRange.init(location: 0, length: string.characters.count))
```

**Preferred:**
```swift
.matchesInString(string, options: [], range: NSRange.init(location: 0, length: string.utf16.count))
```

**Comment by norio-nomura** [comment]
Using `custom_rules`?
```yaml
  characters_count_in_nsrange:
    name: "Using characters.count in NSRange()"
    regex: "NSRange\([^)]*characters.count\s*\)"
    message: "Using String.characters.count in NSRange() may cause an issue."
    serverity: warning
```
