### ISSUE TITLE
Certain custom rule regular expressions aren't parsed properly

### ISSUE THREAD

**Issue by eyeballz** [realm/SwiftLint#717]
Hi,
i am trying to add custom warnings in my yaml to match `Void ->` and `-> ()`
The first rule to match `Void ->` and `Void->` works perfectly
```
custom_rules:
  void_as_parameter:
    included: "*.swift"
    name: "Void as Parameter"
    regex: "(Void ->)"
    message: "Use Void only as return type."
    severity: warning
```
but i cannot match `-> ()` and `->()`
i have tried `(->[ ]?\(\))` and `(\-\>[ ]?\(\))` but nothing works
Am I doing something wrong?
