### ISSUE TITLE
Regex only matches in comments

### ISSUE THREAD

**Issue by xzoky** [realm/SwiftLint#726]
I created a custom rule to find instances of spaces inside parentheses.
For some reason, the rule only works inside comments, not in the rest of the code. I have no idea why.

Here's my custom rule:
```
parenthesis_spacing:
  name: "Parenthesis Spacing"
  message: "Don't put a space inside a parenthesis."
  regex: "\(\s|\s\)"
```

![screen shot 2016-07-15 at 2 17 39 pm](https://cloud.githubusercontent.com/assets/339784/16884436/58eafcbe-4a97-11e6-86df-5f5f9df9b367.png)
