### ISSUE TITLE
Expiring TODO/FIXMEs

### ISSUE THREAD

**Issue by msanders** [realm/SwiftLint#727]
It would be cool if there were a way to add expiring TODOs with SwiftLint.

I.e. `// TODO [2016-06-01]`, which would only warn after the given date.

Right now there isn't a great way of making use of TODOs with SwiftLint without either turning the warning off or adding noise to the project.

**Comment by yonaskolb** [comment]
This is a great idea! You could remind yourself to remove some outdated API when a new version of iOS comes out for example

**Comment by jpsim** [comment]
Great idea!

**Comment by jeremy-w** [comment]
Unless things have changed, Xcode only picks up `TODO:` as a group, so the proposed syntax would stop it from surfacing it in the method list popup. I recommend `[before: 2016-06-01] TODO: Something` as the format.

I use a variation of [Google's TODO comment recommendation](https://google.github.io/styleguide/cppguide.html#TODO_Comments) that works around this by prefixing the author info, like so:

```
(jeremy-w/2016-08-03)TODO: Maybe this should be FIXME?
```

(I stamp it with the current date so I get an implicit "oh that must not have been terribly urgent" read on a comment without having to hit up version control history to track when the TODO landed in the source.)

I handle this simple formatting with a custom rule:

```yaml
    todo_format:
        match_kinds: comment
        message: >
            Prefix TODO/FIXME/etc with email prefix and date,
            so if you're <name@example.com>, then you'd write:
            // (name/2016-07-28)TODO: Document custom rule
        # This isn't a perfect check, but it should guide folks the right
        # direction for common cases.
        regex: "[^)](TODO|FIXME|XXX|HACK|!{3}|[?]{3}):"
```

(That should probably be a non-capturing group, come to think.)
