### ISSUE TITLE
vertical_whitespace to be configurable with a maxEmptyLines parameter that defaults to 1

### ISSUE THREAD

**Issue by masters3d** [realm/SwiftLint#769]
https://github.com/realm/SwiftLint/pull/747#issuecomment-241284190

**Comment by carlosypunto** [comment]
Awesome tool and rule, but now I have it so, please do not forget it

```yml
disabled_rules: 
  - vertical_whitespace # enable it when maxEmptyLines configuration exists

maxEmptyLines: 4
```
