### ISSUE TITLE
Custom rules regex

### ISSUE THREAD

**Issue by vicemice** [realm/SwiftLint#790]
Hi,

I'm using swiftlint v0.12.0 and have an issue with the following custom rule:

```
custom_rules:
  avoid_author_mentions:
    include: "*.swift"
    name: "Author Mention"
    regex: "(Created\s+by.*on\s+\S+)"
    match_kinds:
      - comment
    message: "Avoid mentioning file author"
```

It only works for a small number of files in the directory. And if there is more than 1 match in a single file, it only reports the first one.

Thanks.
