### ISSUE TITLE
VerticalWhitespaceRule not triggering

### ISSUE THREAD

**Issue by rajohns08** [realm/SwiftLint#793]
Using SwiftLint 0.12.0

**Comment by BluMist** [comment]
It is an opt-in rule in 0.12.0, can you share your configuration (.yml)?

**Comment by rajohns08** [comment]
This commit says it was moved back to default: https://github.com/realm/SwiftLint/commit/2eaac54c51af8acc72014c60f68f41858d6ec766.

I tried both opt_in setting in my config file and without it.

**Comment by BluMist** [comment]
It was only moved back on master (per [changelog](https://github.com/realm/SwiftLint/blob/master/CHANGELOG.md)), you said you are using 0.12.0

would you share portion of your .yml?

**Comment by rajohns08** [comment]
```yml
# Disable some rules that are turned on by default that we don't like
disabled_rules:
  - trailing_whitespace
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - todo
  - type_body_length

# Customize existing rules to our liking
line_length:
  warning: 150
  error: 200

opt_in_rules:
  - vertical_whitespace
```
