### ISSUE TITLE
Document exact setup required for a custom rule

### ISSUE THREAD

**Issue by brynjar** [realm/SwiftLint#797]
I'm trying to create a custom rule, but it isn't working.

Is it necessary to add my new rule to opt_in_rules or does the presence of a custom rule in the .swiftlint.yml file automatically include it?

Here is my yml file - I have a test rule, but the rule doesn't match anything, although other rules are working (so my basic setup is fine) and the string 'offset' does exist in my code:

```
disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - trailing_newline
  - type_name
  - line_length
  - force_cast
  - variable_name
  - legacy_constant
  - force_try
  - cyclomatic_complexity
  - function_body_length
  - function_parameter_count
  - todo
  - valid_docs
  - legacy_constructor
  - statement_position
  - control_statement
  - file_length
  - type_body_length

custom_rules:
  use_void_keyword:
    included: "*.swift"
    name: "Testing this stuff"
    regex: "(offset)"

opt_in_rules:
  - use_void_keyword

excluded:
  - Pods
```
